#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file config-change
# brief manage the config changes of oaisim-enb-ue service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr and A. B. Molini   


set -ex
source $CHARM_DIR/utils/common
set_env_paths

EPC_UNIT_RUNNING=0



###############################################################################
###############################################################################
juju-log "Setting up configuration in the "$file_config" file"
###############################################################################
###############################################################################

#Both the name and the id are sent in the s1 link request setup 

enb_name=`config-get enb_name`
enb_id=`config-get enb_id`
if [ -n "$enb_name" ] && [ -n "$enb_id" ]; then
   #ENB NAME
   sed -r -i  "s/(Active_eNBs[ ]*=[^\"]*)\".*\"/\1\"$enb_name\"/" $conf_path/$file_config
   sed -r -i  "s/(eNB_name[ ]*=[ ]*)\".*\"/\1\"$enb_name\"/" $conf_path/$file_config
   #go in a file and see whether inside the network there is already this name
   #if not, you can change and we need to run again to establish the s1 link

   #ENB ID
   sed -r -i  "s/(eNB_ID[ ]*=[ ]*)[^ ;]*/\1$enb_id/" $conf_path/$file_config
   #go in a file and see whether inside the network there is already this name
else
   juju-log -l WARNING "The ENB identifiers have to be specified because maybe the default ones inside the conf file have already been assigned to another ENB. So specify it before proceeding"
fi

###############################################################################
frame_type=`config-get frame_type`
tdd_config=`config-get tdd_config`
tdd_config_s=`config-get tdd_config_s`
eutra_band=`config-get eutra_band`
downlink_frequency=`config-get downlink_frequency`
uplink_frequency_offset=`config-get uplink_frequency_offset`
N_RB_DL=`config-get N_RB_DL`
nb_antennas_tx=`config-get nb_antennas_tx`
nb_antennas_rx=`config-get nb_antennas_rx`
tx_gain=`config-get tx_gain`
rx_gain=`config-get rx_gain`

[ -z "$frame_type" ] || (sed -r -i  "s/(frame_type[ \t]*=[ \t]*)\"[a-zA-Z]+\"/\1\"$frame_type\"/" $conf_path/$file_config)
[ -z "$tdd_config" ] || (sed -r -i  "s/(tdd_config[ \t]*=[ \t]*)[0-9]+/\1$tdd_config/" $conf_path/$file_config)
[ -z "$tdd_config_s" ] || (sed -r -i  "s/(tdd_config_s[ \t]*=[ \t]*)[0-9]+/\1$tdd_config_s/" $conf_path/$file_config)
[ -z "$eutra_band" ] || (sed -r -i  "s/(eutra_band[ \t]*=[ \t]*)[0-9]+/\1$eutra_band/" $conf_path/$file_config)
[ -z "$downlink_frequency" ] || (sed -r -i  "s/(downlink_frequency[ \t]*=[ \t]*)[0-9a-zA-Z]+/\1$downlink_frequency/" $conf_path/$file_config)

[ -z "$uplink_frequency_offset" ] || (sed -r -i  "s/(uplink_frequency_offset[ \t]*=[ \t]*)[-0-9]+/\1$uplink_frequency_offset/" $conf_path/$file_config)
[ -z "$N_RB_DL" ] || (sed -r -i  "s/(N_RB_DL[ \t]*=[ \t]*)[0-9]+/\1$N_RB_DL/" $conf_path/$file_config)
[ -z "$nb_antennas_tx" ] || (sed -r -i  "s/(nb_antennas_tx[ ]*=[ ]*)[0-9]+/\1$nb_antennas_tx/" $conf_path/$file_config)
[ -z "$nb_antennas_rx" ] || (sed -r -i  "s/(nb_antennas_rx[ ]*=[ ]*)[0-9]+/\1$nb_antennas_rx/" $conf_path/$file_config)
[ -z "$tx_gain" ] || (sed -r -i  "s/(tx_gain[ ]*=[ ]*)[0-9]+/\1$tx_gain/" $conf_path/$file_config)
[ -z "$rx_gain" ] || (sed -r -i  "s/(tx_gain[ ]*=[ ]*)[0-9]+/\1$tx_gain/" $conf_path/$file_config)

#for the empty config options there will not be problems becasue in the coinfig file there are
#the default values set by the OAI developers.

#############################################################################

##I should change the s1-u and s1-mme
iface=`config-get eth`

if [ -n "$iface" ]; then
   ipv4=`ifconfig $iface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`
   #INTERFACES
   sed -r -i "/ENB_INTERFACE_NAME_FOR_S1_MME/ s/\".+\"/\"$iface\"/" $conf_path/$file_config
   sed -r -i "/ENB_INTERFACE_NAME_FOR_S1U/ s/\".+\"/\"$iface\"/" $conf_path/$file_config

   #ADDRESSES
   sed -r -i "/ENB_IPV4_ADDRESS_FOR_S1_MME/ s-\".+\"-\"$ipv4/24\"-" $conf_path/$file_config
   sed -r -i "/ENB_IPV4_ADDRESS_FOR_S1U/ s-\".+\"-\"$ipv4/24\"-" $conf_path/$file_config
else
   juju-log -l WARNING "The ethernet interface has to be specified before the relation with epc can be added"
fi

############################################################################
TAC=`config-get TAC`
#TAC in config file
[ -z "$TAC" ] || (sed -r -i  "s/(tracking_area_code[ ]*=[ ]*)\"[0-9]+\"/\1\"$TAC\"/" $conf_path/$file_config)
#if it empty we keep the default already present in the conf file set by the OAI developers

############################################################################


if [ -n "$(relation-ids epc)" ]; then
   #we start the service only if we have a relation
   
   for epc_id in $(relation-ids epc); do
       juju-log ""$epc_id""
       #if the TAC is the same as before, the local setting won't change and so the relation-changed hook 
       #won't be called
       relation-set -r "$epc_id" TAC=$TAC
       for unit in $(relation-list -r $epc_id); do
          epc_running=`relation-get -r $epc_id epc_running $unit`
          if [ "$epc_running" == "yes" ]; then
             EPC_UNIT_RUNNING=$((EPC_UNIT_RUNNING + 1))
             #at least one epc is running among the ones connected to oaisim
             #so let's run oaisim...beacuse we have changed some configuration
          fi
       done
   done

   if [ $EPC_UNIT_RUNNING -gt 0 ]; then
      juju-log "Running OAISIM"
      $CHARM_DIR/hooks/start
      status-set active "OAISIM is running"
   else
      juju-log "Service reconfigured but cannot be run"
      status-set blocked "Add hss or db relation"
   fi

else
   juju-log "Need a relation to run"
   status-set maintenance "Waiting for active connection to EPC to gather the last info to run OAISIM"
fi



