options:
   snap:
     default: "edge"
     description: |
      snap indicates which channel to use for installation hook. 
     type: string
   bind_addr:
     default: "0.0.0.0"
     description: |
       defines the address to which the LL-MEC is binded. By default, the LL-MEC is listening across all the interfaces. 
     type: string
   bind_sbi_port: 
     default: 6653  
     description: |
       defines the network interface port to connect to openVirtualSwitch or any other OpenFlow-enabled switch with OF1.3 or higher.
     type: int
   bind_nbi_port:
     default: 9998
     description: |
       defines the network interface port for the REST API to issue a command to the controller.
     type: int
   gw_mac_addr:
     default: "00:24:9b:23:33:a6"
     description: |
       defines the network interface port for the REST API to issue a command to the controller.
     type: string

