#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file hss-relation-departed
# brief called when the hss-epc relation is removed 
# author  navid.nikaein@eurecom.fr and A. B. Molini 

set -ex
mme_fqdn=`relation-get mme_hostname`

sed -r -i "/$mme_fqdn/ d" /etc/hosts

db_id=`relation-ids db`
#could be that the relation is up but the unit has been already gone
if [ -z "$db_id" ]; then
   juju-log "Database relation broken!!!...failed MME removal from db"
   exit 0
else
   db_unit=$(relation-list -r $db_id)
   if [ -z "$db_unit" ]; then
      exit 0
   fi
fi


#No cycle, only one database master.
db_user=`relation-get -r "$db_id" user $db_unit`
db_password=`relation-get -r "$db_id" password $db_unit`
db_host=`relation-get -r "$db_id" host $db_unit`
db_database=`relation-get -r "$db_id" database $db_unit`
#if [ -z "$db_user" ]; then
#
#   exit 0
#fi

if [ -n "$(/usr/bin/mysql -u $db_user --password=$db_password -h $db_host $db_database -e "select mmehost from mmeidentity where mmehost='$mme_fqdn'";)" ]; then

      /usr/bin/mysql -u $db_user --password=$db_password -h $db_host $db_database -e "delete from mmeidentity where mmehost='$mme_fqdn'";
fi
juju-log "MME departure"
status-set active "HSS is running"

#WATCH OUT: HSS can be connected to many MME(EPC) so we don't stop the service.


