#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file hss-relation-joined 
# brief called when the hss-epc relation is created 
# author navid.nikaein@eurecom.fr and A. B. Molini  

set -eux
source $CHARM_DIR/utils/common

juju-log "Setting up HSS relation info for EPC"
relation-set hss_hostname=`hostname --fqdn`

hss_iface=`config-get eth`
hss_public_unit_ip=`unit-get public-address`
hss_public_ip=`get_eth_ip $hss_iface`

get_ip_address $hss_public_ip
status=$?
if [ "$status" == "1" ] ; then
    status-set error "nslookup failed for the mme host name ($hss_public_ip)"
    relation-set ip_address=$hss_public_ip
else
    relation-set ip_address=$validated_hss_public_ip
fi 

#if there is already a db relation, check whether hss is already running
#if [ -n "$(relation-ids db)" ]; then
    #add a check if it is really running
    #maybe we add a hss relation and right after a db relation and so
    #we have the db relation, but not HSS running yet.
    check_hss_process
    if [ "$status" -eq 0 ]; then
       relation-set hss_running=yes
    else
       relation-set hss_running=no
    fi
#fi

relation-set trigger_restart=0
relation-set mme_in_db=no


