#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file cu-relation-joint
# brief manage the F1 interface between CU and DU 
# author navid.nikaein@eurecom.fr 

set -eux
source $CHARM_DIR/utils/common
set_env
status-set maintenance "cu-relation-joint hook"
oai-ran.enb-conf-set $cu_conf
#node_func=`config-get node_function`
#if [ "$node_func" == "cu" ] || [ "$node_func" == "CU" ] ; then
    cu_ip_addr=`unit-get public-address`
    cu_iface_name="none"
    #cu_iface_name=`config-get cu_if_name`
    if [ "$cu_iface_name" == "none" ] ; then
        for interface in $(ls /sys/class/net); do
            if [ `ifconfig $interface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"` != "" ]; then
                ip_addr=`ifconfig $interface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`
                if [ "$ip_addr" == $cu_ip_addr ] ; then
                    cu_iface_name=$interface
                    break
                fi
            fi
        done
    fi
    #cu_ip_addr=`ifconfig $(config-get cu_if_name) | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`
    #relation-set CUIP=`config-get cu_ip_addr`
    relation-set CUIP=$cu_ip_addr
    relation-set CUIF=$cu_iface_name
    #relation-set CUIF=`config-get cu_if_name`
    relation-set CUPORTC=`config-get cu_portc`
    relation-set CUPORTD=`config-get cu_portd`


    
#else
#    disable_f1
#    echo "no" > $CHARM_DIR/.rru_active
    
#fi 
