#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file cudu-relation-changed
# brief manage the config changes of oai-enb service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr 

set -eux
source $CHARM_DIR/utils/common
set_env
status-set maintenance "cudu-relation-changed hook"

if [ "$node_func" == "cu" ] || [ "$node_func" == "CU" ] ; then

    DUIP=`relation-get du_ip_addr`
    DUIF=`relation-get du_if_name`
    DUPORTC=`relation-get du_portc`
    DUPORTD=`relation-get du_portd`
    
    if [ -z "$DUIP" ]; then
	juju-log "DU IP addr not yet available"
	exit 0
    fi
    if [ -z "$DUIF" ]; then
	juju-log "DU IF name not yet available"
	exit 0
    fi
    if [ -z "$DUPORTC" ]; then
	juju-log "DU PORTC not yet available"
	exit 0
    fi
    if [ -z "$DUPORTD" ]; then
	juju-log "DU PORTD not yet available"
	exit 0
    fi
    
    
    enable_cu_f1 `config-get cu_if_name` `config-get cu_ip_addr` $DUIP `config-get cu_portc` $DUPORTC `config-get cu_portd` $DUPORTD
    
    juju-log "CU config done"
fi 


if [ "$node_func" == "du" ] || [ "$node_func" == "DU" ] ; then
    
    
    CUIP=`relation-get cu_ip_addr`
    CUIF=`relation-get cu_if_name`
    CUPORTC=`relation-get cu_portc`
    CUPORTD=`relation-get cu_portd`
    
    if [ -z "$CUIP" ]; then
	juju-log "CU IP addr not yet available"
	exit 0
    fi
    if [ -z "$CUIF" ]; then
	juju-log "CU IF name not yet available"
	exit 0
    fi
    if [ -z "$CUPORTC" ]; then
	juju-log "CU PORTC not yet available"
	exit 0
    fi
    if [ -z "$CUPORTD" ]; then
	juju-log "CU PORTD not yet available"
	exit 0
    fi
    
    enable_du_f1  `config-get du_if_name` `config-get du_ip_addr` $CUIP `config-get du_portc` $CUPORTC `config-get du_portd` $CUPORTD

    juju-log "DU config done"
fi 
