#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file install hook
# brief install the oai-enb for different RF target
# author  navid.nikaein@eurecom.fr

install_packages(){
    apt update
    
    gitAlreadyInstalled=$(dpkg --get-selections snapd 2>/dev/null | grep -c 'install') || true
    if [ ! $gitAlreadyInstalled -eq 1 ]; then # If git is NOT installed
	    apt-get install -y --force-yes snapd # Ensure necessary git dependency exist.
    fi

    gitAlreadyInstalled=$(dpkg --get-selections git 2>/dev/null | grep -c 'install') || true
    if [ ! $gitAlreadyInstalled -eq 1 ]; then # If git is NOT installed
	    apt-get install -y --force-yes git # Ensure necessary git dependency exist.
    fi
    atAlreadyInstalled=$(dpkg --get-selections at 2>/dev/null | grep -c 'install') || true
    if [ ! $atAlreadyInstalled -eq 1 ]; then 
        # If at command is NOT installed
        apt-get install -y --force-yes at
        # Ensure at command exists to let juju reschedule this hook after rebooting the machine.
    fi
    virtwhatAlreadyInstalled=$(dpkg --get-selections virt-what 2>/dev/null | grep -c 'install') || true
    if [ ! $virtwhatAlreadyInstalled -eq 1 ]; then 
    	apt-get install -y --force-yes virt-what || true 
    fi
    cpufreqAlreadyInstalled=$(dpkg --get-selections cpufrequtils 2>/dev/null | grep -c 'install') || true
    if [ ! $cpufreqAlreadyInstalled -eq 1 ]; then 
	    apt-get install -y --force-yes cpufrequtils
    fi
}

clone_repro(){
    juju-log  "Fetching the Mosaic5G repository"
    
    echo -n | openssl s_client -showcerts -connect gitlab.eurecom.fr:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt

    #everytime refresh the installation 
    if [ -d "$mosaic_path" ]; then  
        cd $mosaic_path
        git reset --hard HEAD
        cd - 
    else
    	git clone https://gitlab.eurecom.fr/mosaic5g/mosaic5g.git $mosaic_path
    fi
}

optimize_cpu_for_ran_split(){
    # required optimizations for RAN split
    if [ "$machine_type" != "lxc" ] ; then
        ipv4=`unit-get public-address`
        iface="none"
        if [ "$iface" == "none" ] ; then
            for interface in $(ls /sys/class/net); do
                if [ `ifconfig $interface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"` != "" ]; then
                    ip_addr=`ifconfig $interface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`
                    if [ "$ip_addr" == $ipv4 ] ; then
                        iface=$interface
                        break
                    fi
                fi
            done
        fi
        apt-get update  -y
        apt-get install auditd -y
        # install the cpuspeed
        wget https://carlthompson.net/downloads/cpuspeed/cpuspeed-1.5.tar.bz2
        tar -xvf cpuspeed-1.5.tar.bz2
        cd cpuspeed-1.5
        make install_debian
        cd ../
        service cpuspeed stop
        service auditd stop
        update-rc.d ondemand disable
        #Disable pause frames on Ethernet
        /sbin/ethtool -A  $iface  autoneg off rx off tx off || true

        #Increase Ethernet Buffer rings
        sudo /sbin/ethtool -G  $iface   rx  4096 tx  4096 || true
        
        #Set Ethernet interrupt coalescence mode (dynamic conservative mode is recommended)
        sudo /sbin/ethtool -C  $iface  rx-usecs 3 || true
        
        #Increase interface queue length
        ifconfig  $iface txqueuelen 1000

        #Increase kerenl socket buffer
        sysctl -w net.core.rmem_max=8388608
        sysctl -w net.core.wmem_max=8388608
        sysctl -w net.core.rmem_default=65536
        sysctl -w net.core.wmem_default=65536
    fi
}

set_cpu_freq(){
#getconf _NPROCESSORS_CONF
    num_cpu=`nproc`
    num_cpu=$((num_cpu-1))
    for i in `seq 0 $num_cpu`; do
	    cpufreq-set -g performance -c $i || true 
    done 
    #lsmod | grep intel_powerclamp
    #[ $? -eq 0 ] && (rmmod intel_powerclamp || true)
    rmmod intel_powerclamp || true
    
}


build_oai_ran(){

    #sudo snap remove oai-ran

    #if [ ! -d $mosaic_path ] ; then 
#	mkdir $mosaic_path
 #   fi
    
    if [ "$snap" == "edge" ] || [ "$snap" == "beta" ] ; then
	    juju-log "Installing OAI-RAN snap"
    else
        juju-log "channel $snap is not supported, use edge or beta"
        snap="edge"
    fi

    if [ -z "$(snap list oai-ran)" ] ; then
        op="install"
    else
        op="refresh"
    fi
    sudo snap $op oai-ran --channel=$snap --devmode

}

init_oai_ran(){
    oai-ran.stop-all || true 

    #check oai ran func 
    if [ "$node_func" != "cu" -o  "$node_func" != "CU" ]; then
        echo "cu" > $CHARM_DIR/.node_func
        echo "yes"  > $CHARM_DIR/.cu_active
        
        echo "no"  > $CHARM_DIR/.du_active
        echo "no"  > $CHARM_DIR/.rru_active
        echo "no"  > $CHARM_DIR/.rcc_active
        echo "no"  > $CHARM_DIR/.enb_active
    elif [ "$node_func" != "du" -o  "$node_func" != "DU" ] ; then
        echo "du" > $CHARM_DIR/.node_func
        echo "yes"  > $CHARM_DIR/.du_active

        echo "no"  > $CHARM_DIR/.cu_active
        echo "no"  > $CHARM_DIR/.rru_active
        echo "no"  > $CHARM_DIR/.rcc_active
        echo "no"  > $CHARM_DIR/.enb_activ
    elif [ "$node_func" != "rru" -o  "$node_func" != "RRU" ] ; then
        echo "rru" > $CHARM_DIR/.node_func
        echo "yes"  > $CHARM_DIR/.rru_active

        echo "no"  > $CHARM_DIR/.du_active
        echo "no"  > $CHARM_DIR/.cu_active
        echo "no"  > $CHARM_DIR/.rcc_active
        echo "no"  > $CHARM_DIR/.enb_activ
    elif [ "$node_func" != "rcc" -o  "$node_func" != "RCC" ] ; then
        echo "rcc" > $CHARM_DIR/.node_func
        echo "yes"  > $CHARM_DIR/.rcc_active

        echo "no"  > $CHARM_DIR/.du_active
        echo "no"  > $CHARM_DIR/.cu_active
        echo "no"  > $CHARM_DIR/.rru_active
        echo "no"  > $CHARM_DIR/.enb_activ
    else 
        juju-log "The requested $node_func is not supported, reverting to enb."
        echo "enb" > $CHARM_DIR/.node_func
        echo "yes"  > $CHARM_DIR/.enb_active

        echo "no"  > $CHARM_DIR/.du_active
        echo "no"  > $CHARM_DIR/.cu_active
        echo "no"  > $CHARM_DIR/.rru_active
        echo "no"  > $CHARM_DIR/.rcc_active
    fi
    
    # just a flag for start script to run the service
    echo "yes" > $CHARM_DIR/.oairan_running_flag
}

status-set maintenance "Install hook"

set -eux
export DEBIAN_FRONTEND=noninteractive
source /$CHARM_DIR/utils/common
#set_env
echo "no" > $CHARM_DIR/.oairan_running_flag


open-port 2152/udp  # S1-U
open-port 36412/tcp # S1-C

open-port 50000/udp  # local_portc
open-port 50001/udp # local_portd
#default port 
#open-port 2210/tcp  # FlexRAN
#echo "2210" > $CHARM_DIR/.rtc_port

#general params 
snap=`config-get snap`

# node params 
node_func=`config-get node_function`
hw=`config-get target_hardware`

# MME IP ADD
mme_ip=`config-get mme_ip_addr`

# RRU params 
#fh_tr_mode=`config-get fh_transport_mode`
#fh_if_name=`config-get fh_if_name`
#fh_local_port=`config-get fh_local_port`
#open-port $fh_local_port/udp
#rru_tx_shift=`config-get rru_tx_shift`
#rru_tx_sampleadvance=`config-get rru_tx_sampleadvance`
#rru_tx_schedadvance=`config-get rru_tx_schedadvance`


# used to set the config file for this node
band=`config-get eutra_band`
bw=`config-get N_RB_DL`


echo "$snap" > $CHARM_DIR/.snap
echo "$hw" > $CHARM_DIR/.hw
echo "$node_func" > $CHARM_DIR/.node_func
echo "$mme_ip" >  $CHARM_DIR/.mme_ip

echo "no"  > $CHARM_DIR/.rtc_running
echo "no"  > $CHARM_DIR/.enb_running
echo "no"  > $CHARM_DIR/.cu_running
echo "no"  > $CHARM_DIR/.du_running
echo "no"  > $CHARM_DIR/.rru_running
echo "no"  > $CHARM_DIR/.rcc_running
echo "no"  > $CHARM_DIR/.mme_running

exec_args=""
build_oai_for_hw=""
config_oai_for_hw=""
config_file_name=""
config_file_lmsdr="null"

install_packages
machine_type=`virt-what`

optimize_cpu_for_ran_split

set_cpu_freq

build_oai_ran

init_oai_ran
