#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file mme-relation-changed 
# brief called when the enb-mme relation is changed 
# author  navid.nikaein@eurecom.fr 

set -ex
source $CHARM_DIR/utils/common
set_env

if [ "$(cat $CHARM_DIR/.mme_running)" == "remote" ] ; then 
    exit 0 
fi 

#tracking_area_code=`relation-get TAC`
mobile_country_code=`relation-get MCC`
mobile_network_code=`relation-get MNC`
mmeipv4=`relation-get mme_ip`
trigger_restart=`relation-get trigger_restart`
mme_running=`relation-get mme_running`
# keep the status of mme_running for rrh-relation-changed

echo "$mme_running" >  $CHARM_DIR/.mme_running


if [ -z "$mobile_country_code" ]; then
   juju-log "MCC not available yet, exit silently"
   exit 0
fi

if [ -z "$mobile_network_code" ]; then
   juju-log "MNC not available yet, exit silently"
   exit 0
fi

if [ -z "$mmeipv4" ]; then
   juju-log "MME IP address not available yet, exit silently"
   exit 0
fi

if [ -z "$mme_running" ]; then
   juju-log "MME is not running yet, exit silently"
   exit 0
fi

if [ -z "$trigger_restart" ]; then
   juju-log "Trigger Restart is not available yet, exit silently"
   exit 0
fi


   #sed -r -i "/mme_ip_address/ s-\"[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\"-\"$mmeipv4\"-" $conf_path/$file_config
if [ -z "$(grep "$mmeipv4" $CHARM_DIR/mme_ips)"  ]; then
    add_mme_ip $mmeipv4
fi

if [ -z "$(grep "$mobile_network_code" $CHARM_DIR/plmn_list)"  ]; then
    add_plmn $mobile_country_code $mobile_network_code
fi

#when integrer
#sed -r -i "s/(mnc[ ]*=[ ]*)[0-9]+/\$mobile_network_code/" $conf_file
#sed -r -i "s/(mcc[ ]*=[ ]*)[0-9]+/\$mobile_country_code/" $conf_file

# when the value is string
#sed -r -i  "s/(mobile_country_code[ ]*=[ ]*)\"[0-9]+\"/\1\"$mobile_country_code\"/" $conf_file
#sed -r -i  "s/(mobile_network_code[ ]*=[ ]*)\"[0-9]+\"/\1\"$mobile_network_code\"/" $conf_file


#if [ ! -f $CHARM_DIR/.trigger_restart ]; then
#    echo "0" > $CHARM_DIR/.trigger_restart
#fi  


#for mme_id in $(relation-ids mme); do
#    juju-log ""$mme_id""
#    for unit in $(relation-list -r $mme_id); do
#       mme_running=`relation-get -r $mme_id mme_running $unit`
#       if [ "$mme_running" == "yes" ]; then
#          break;
           #at least one mme is running among the ones connected to oaisim
           #so let's run oaisim...beacuse we have changed some configuration
#       fi
#    done
#done

$CHARM_DIR/hooks/config-changed

