#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file mme-relation-departed
# brief called when the enb-epc relation is removed 
# author  navid.nikaein@eurecom.fr 

set -eux
source $CHARM_DIR/utils/common
set_env

status-set maintenance "mme-relation-departed hook"

juju-log "stopping eNB service and waiting for a MME relation to be restablished"
stop_enb

#I can remove from Hss the entry of the IMSI in the case we put from here and not from 
#PHPOMYADMIN
#I could remove mnc mcc tai and mme_address from the config file

juju-log "Deleting MME relation info from the config file in use"
echo "no" > $CHARM_DIR/.mme_running
rm -f $CHARM_DIR/.trigger_restart
sed -r -i  "s/(mobile_country_code[ ]*=[ ]*)\"[0-9]*\"/\1\"0\"/" $conf_file
sed -r -i  "s/(mobile_network_code[ ]*=[ ]*)\"[0-9]*\"/\1\"0\"/" $conf_file
#sed -r -i "/mme_ip_address/ s-\"[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\"-\"0.0.0.0\"-" $conf_file
mmeipv4=`relation-get mme_ip`
remove_mme_ip $mmeipv4

mcc=`relation-get MCC`
mnc=`relation-get MNC`
remove_plmn $mcc $mnc  
