#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file rru-relation-changed
# brief manage the config changes of oai-enb service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr 

set -eux
source $CHARM_DIR/utils/common
set_env

node_func=`config-get node_function`
if [ "$node_func" == "rru" ] || [ "$node_func" == "RRU" ] ; then
    status-set maintenance "rru-relation-changed hook"

    RCCIP=`relation-get RCCIP`
    RCCIF=`relation-get RCCIF`
    RCCPORTC=`relation-get RCCPORTC`
    RCCPORTD=`relation-get RCCPORTD`

    if [ -z "$RCCIP" ]; then
    juju-log "RCC IP addr not yet available"
    exit 0
    fi
    if [ -z "$RCCIF" ]; then
    juju-log "RCC IF name not yet available"
    exit 0
    fi
    if [ -z "$RCCPORTC" ]; then
    juju-log "RCC PORTC not yet available"
    exit 0
    fi
    if [ -z "$RCCPORTD" ]; then
    juju-log "RCC PORTD not yet available"
    exit 0
    fi
    rru_ip_addr=`unit-get public-address`
    rru_iface_name="none"
    if [ "$rru_iface_name" == "none" ] ; then      
        for interface in $(ls /sys/class/net); do
            if [ `ifconfig $interface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"` != "" ]; then
                ip_addr=`ifconfig $interface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`
                if [ "$ip_addr" == $rru_ip_addr ] ; then
                    rru_iface_name=$interface
                    break
                fi
            fi
        done
    fi
    #rru_ip_addr=`ifconfig $(config-get rru_if_name) | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`
    enable_rru_ecpri  $rru_iface_name $rru_ip_addr $RCCIP `config-get rru_portc` $RCCPORTC `config-get rru_portd` $RCCPORTD
    #enable_rru_f1  `config-get rru_if_name` $rru_ip_addr $RCCIP `config-get rru_portc` $RCCPORTC `config-get rru_portd` $RCCPORTD
    #enable_rru_f1  `config-get rru_if_name` `config-get rru_ip_addr` $RCCIP `config-get rru_portc` $RCCPORTC `config-get rru_portd` $RCCPORTD

    juju-log "RRU config done"
else
    status-set blocked "Error, function $node_func does not have rru relation"
fi