#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file rtc-relation-changed
# brief called when a relation between an eNB and RTC is changed 
# author  navid.nikaein@eurecom.fr

set -ex
source $CHARM_DIR/utils/common
set_env

if [ -f $CHARM_DIR/.rtc_port ]; then
  rtc_port_config=`cat $CHARM_DIR/.rtc_port`
else
  rtc_port_config=""
fi

rtc_running=`relation-get RTC_RUNNING`
rtc_port=`relation-get RTC_PORT`
rtc_ip=`relation-get RTC_PUBLIC_IP`
agnet_if=`config-get flexran_if_name`

if [ -z "$rtc_running" ]; then
   juju-log "rtc is not running yet, exit silently"
   exit 0
fi
if [ -z "$rtc_port" ]; then
   juju-log "rtc port not available yet, exit silently"
   exit 0
fi
if [ -z "$rtc_ip" ]; then
   juju-log "rtc ip not available yet, exit silently"
   exit 0
fi

echo "$rtc_running" >  $CHARM_DIR/.rtc_running

if [ "$rtc_port_config" != "$rtc_port" ] ; then 
  if [ "$rtc_port_config" != "" ] ; then 
     close-port $rtc_port_config/tcp || true
  fi
  open-port $rtc_port/tcp 
  echo "2210" > $CHARM_DIR/.rtc_port
fi   

#echo "$rtc_port" > $CHARM_DIR/.rtc_port 

add_rtc_ip $agnet_if $rtc_ip $rtc_port

#if [ -z "$(grep "$rtc_ip" $CHARM_DIR/rtc_ip)"  ]; then
#    add_rtc_ip $agnet_if $rtc_ip $rtc_port
#fi 

stop_enb
$CHARM_DIR/hooks/config-changed

