name: oai-ue
version: '1.4' 
summary: OpenAirInterface UE entity 
description: |
    OAI UE is the openairinterface-based UE that allows you to connect to any commercial eNB. 
grade: stable
type: app
architectures:
  - amd64
  - i386
confinement: devmode

apps:
  test:
    command: test all
  info:
    command: run info
  ue:
    command: run ue
  uesim:
    command: run uesim
  usim-gen:
    command: run usim-gen
  usim-print:
    command: run usim-print
  nvram-print:
    command: run nvram-print
  init:
    command: init
  oip:
    command: run oip
  ued:
    command: run ue 
    daemon: simple
    stop-command: run stop
    stop-timeout: 7s
  uesimd:
    command: run uesim
    daemon: simple
    stop-command: run stop uesimd
    stop-timeout: 7s
  ue-start:
    command: run start ued
  ue-stop:
    command: run stop ued
  ue-restart:
    command: run restart ued
  ue-status:
    command: run status ued
  ue-journal:
    command: run journal ued
  uesim-start:
    command: run start uesimd
  uesim-stop:
    command: run stop uesimd
  uesim-restart:
    command: run restart uesimd 
  uesim-status:
    command: run status uesimd
  uesim-journal:
    command: run journal uesimd
  help:
    command: run help
  debug:
    command: run gdb
  ue-conf-set:
    command: conf set-ue
  ue-conf-get:
    command: conf echo-ue
  ue-conf-show:
    command: conf cat-ue
  ue-conf-list:
    command: conf ls-ue
  ue-cmd-set:
    command: conf set-ue-cmd
  ue-cmd-get:
    command: conf echo-ue-cmd
  ue-cmd-show:
    command: conf cat-ue-cmd
  ue-cmd-list:
    command: conf ls-ue-cmd
  uesim-cmd-set:
    command: conf set-uesim-cmd
  uesim-cmd-get:
    command: conf echo-uesim-cmd
  uesim-cmd-show:
    command: conf cat-uesim-cmd
  uesim-cmd-list:
    command: conf ls-uesim-cmd
  usim-set:
    command: conf set-usim
  usim-get:
    command: conf echo-usim
  usim-show:
    command: conf cat-usim
  usim-list:
    command: conf ls-usim
  uesim-conf-set:
    command: conf set-uesim
  uesim-conf-get:
    command: conf echo-uesim
  uesim-conf-show:
    command: conf cat-uesim
  uesim-conf-list:
    command: conf ls-uesim
hooks:
  install:
    plugs: [home, network]
  configure:
    plugs: [home, network]
  remove:
    plugs: [home, network]

parts:
  gdb:
    plugin: nil
    override-build: |
      sudo apt install gdb -y
      mkdir $SNAPCRAFT_PART_INSTALL/share 
      cp -r /usr/share/gdb $SNAPCRAFT_PART_INSTALL/share
      cp /usr/bin/gdb* $SNAPCRAFT_PART_INSTALL
    prime:
      - gdb*
      - share/*

  tools:
    plugin: nil
    #stage-packages:
    #  - libgcc-5-dev
    #  - libgcc1
    #  - libisl-dev
    #  - make
    #  - gcc
    #  - g++
    #  - build-essential
    override-build: |
      sudo apt install make gcc g++ build-essential -y
      mkdir $SNAPCRAFT_PART_INSTALL/tools 
      cp /usr/bin/make $SNAPCRAFT_PART_INSTALL/tools
      cp /usr/bin/gcc $SNAPCRAFT_PART_INSTALL/tools
      cp /usr/bin/g++ $SNAPCRAFT_PART_INSTALL/tools
      cp /usr/bin/cc $SNAPCRAFT_PART_INSTALL/tools

    prime:
      - tools/
      - usr/lib/*
      - lib/*
      
  oai-ue:
    plugin: cmake
    source: https://gitlab.eurecom.fr/oai/openairinterface5g.git
    source-branch: develop
    build-packages: [build-essential, ]
    override-build: |
      cd cmake_targets
      ./build_oai -I -w USRP --uhd-images-dir ../common/uhd_images
      ./build_oai --UE -w USRP -c -C 
      cd -   
      mkdir -p $SNAPCRAFT_PART_INSTALL/ue
      cp  targets/bin/* $SNAPCRAFT_PART_INSTALL/ue
      cp -r common/uhd_images $SNAPCRAFT_PART_INSTALL/ 
      cp targets/PROJECTS/GENERIC-LTE-EPC/CONF/* $SNAPCRAFT_PART_INSTALL/ue
      cp cmake_targets/snap_environment.sh $SNAPCRAFT_PART_INSTALL/ue
    stage:
      - ue/*
      - usr/lib/*
      - lib/*
      - uhd_images/*
    prime:
      - ue/*
      - usr/lib/*
      - lib/*
      - uhd_images/*
    organize:
      ue/liboai_usrpdevif.so.Rel14: usr/lib/liboai_device.so
      ue/libcoding.so: usr/lib/libcoding.so
      ue/libparams_libconfig.so: usr/lib/libparams_libconfig.so
      #ue/lte-uesoftmodem.Rel14: ue/oai-ue
      #usr/lib/lapack/liblapack.so.3: usr/lib/liblapack.so.3 

  uesim:
    plugin: cmake
    source: https://gitlab.eurecom.fr/oai/openairinterface5g.git
    source-branch: develop
    build-packages: [build-essential, ]
    override-build: |
      cd cmake_targets
      ./build_oai -I 
      ./build_oai --UE -t ETHERNET -c -C 
      cd -
      mkdir -p $SNAPCRAFT_PART_INSTALL/uesim
      cp  targets/bin/* $SNAPCRAFT_PART_INSTALL/uesim
      cp targets/PROJECTS/GENERIC-LTE-EPC/CONF/* $SNAPCRAFT_PART_INSTALL/uesim
      cp cmake_targets/snap_environment.sh $SNAPCRAFT_PART_INSTALL/uesim
    stage:
      - uesim/*
      - usr/lib/*
      - lib/*
    prime:
      - uesim/*
      - usr/lib/*
      - lib/*
    organize:
      uesim/liboai_eth_transpro.so.Rel14: usr/lib/liboai_transpro.so  

  frontend:
    plugin: dump
    source: frontend
