#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file common
# brief common functions and variables
# author  navid.nikaein@eurecom.fr

ubuntu_dist=$(lsb_release -si)$(lsb_release -sr)


set_env(){
    
    mosaic_path=/srv/mosaic5g
    export PATH=$PATH:/snap/bin
    conf_dir=/var/snap/oai-cn/current
    hss_conf=$conf_dir/hss.conf
    hss_fd_conf=$conf_dir/hss_fd.conf
    acl_conf=$conf_dir/acl.conf

    snap_dir=/snap/oai-cn/current
    oai_db_sql=$snap_dir/hss/oai_db.sql
    oai_op_key="11111111111111111111111111111111"
    oai_opc_key="8E27B6AF0E692E750F32667A3B14605D"
}


db_data_in_config_file(){

set_env

sed -r -i "s/(MYSQL_server[^\"]*)\".*\"/\1\"$1\"/" $hss_conf
sed -r -i "s/(MYSQL_user[^\"]*)\".*\"/\1\"$2\"/" $hss_conf
sed -r -i "s/(MYSQL_pass[^\"]*)\".*\"/\1\"$3\"/" $hss_conf
sed -r -i "s/(MYSQL_db[^\"]*)\".*\"/\1\"$4\"/" $hss_conf

}

check_hss_process(){

    #IS_RUNNING=`systemctl status oai_hss.service`
    #if [[ $IS_RUNNING =~ .*running.* ]]; then
    #fi
    
    IS_ACTIVE=`systemctl is-active snap.oai-cn.hssd.service`
    
    if [ "$IS_ACTIVE" == "active" ]; then
	juju-log "OAI HSS is running"
	status=0
    else
	juju-log "OAI HSS is not running"
	status=1
    fi
}

start_hss(){
    oai-cn.hss-start
}

stop_hss(){
    oai-cn.hss-stop || true 
}
restart_hss(){
    oai-cn.hss-restart
}

check_hss_connection_to_db(){
set_env
juju-log "Establishing connection to db"
COUNTER=0

db_id=`relation-ids db`
db_unit=`relation-list -r $db_id`
db_host=`relation-get -r "$db_id" user $db_unit`

while [ $COUNTER -lt 30 ]; do
   sleep 1
   if [ "$(grep -c ".*db.*DONE" /srv/.out)" -gt 0 ]; then
      juju-log "Connection to db...Established"
      break
   fi
   COUNTER=$((COUNTER+1))
done

if [ "$COUNTER" -eq 30 ]; then
   if [ "$(netstat -tpn | grep -c "$db_host:3306.*ESTABLISHED.*$hss_exec_name")" ]; then
      juju-log "OAI_HSS/db/db_connector.c can actually to connect to db...but HSS output is not consistent with the check..report the bug"
      status-set active "HSS is connected...a problem has been detected...the HSS output is not consistent with the check..report the bug"
   else
      status-set blocked "HSS cannot connect to db...try to upgrade the charm"
      exit 1
   fi
fi

}

check_hss_s6a_layer(){

COUNTER=0
juju-log "Checking s6a layer initialization"
while [ $COUNTER -lt 30 ]; do
   sleep 1
   if [ "$(grep -c "Core state: 1 -> 2" /srv/.out)" -gt 0 ]; then
      juju-log "s6a layer initialized......HSS ready"
      status-set active "OAI HSS is running"
      break
   fi
   COUNTER=$((COUNTER+1))
done

if [ "$COUNTER" -eq 30 ]; then
   juju-log "HSS cannot initialize s6a layer...make sure the db relation is established...or trouble with freediameter...try to upgrade the charm"
   status-set blocked "HSS cannot initialize s6a layer...maybe a problem with freediameter...try to upgrade the charm"
   exit 1
fi

}



install_required_kernel(){
version=3.19
wget -r -e robots=off --accept-regex "(.*generic.*amd64)|(all).deb" http://kernel.ubuntu.com/~kernel-ppa/mainline/v${version}-vivid/
dpkg -i kernel.ubuntu.com/*/*/*/*deb
}

check_current_kernel(){

#required_kern_release=$(cat $tools_path/build_helper | egrep -o "check_kernel_release_and_install_xtables_addons_oai .+" | cut -d ' ' -f2)
required_kern_release=3.19
required_kern_version=`echo $required_kern_release | cut -d '.' -f1`
required_kern_major_revision=`echo $required_kern_release | cut -d '.' -f2`
current_kern_release=`uname -r`
current_kern_version=`echo $current_kern_release | cut -d '.' -f1`
current_kern_major_revision=`echo $current_kern_release | cut -d '.' -f2`
if [ "$current_kern_version" -gt "$required_kern_version" ]; then
     REQUIRED_KERNEL_IS_INSTALLED="true"
elif [ "$current_kern_version" -eq "$required_kern_version" ] && [ "$current_kern_major_revision" -ge "$required_kern_major_revision" ]; then
     REQUIRED_KERNEL_IS_INSTALLED="true"
else
     REQUIRED_KERNEL_IS_INSTALLED="false"
fi

}

# get from http://www.linuxjournal.com/content/validating-ip-address-bash-script
validate_ip() {

local  ip=$1
local  stat=1

if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    OIFS=$IFS
    IFS='.'
    ip=($ip)
    IFS=$OIFS
    [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
        && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
    stat=$?
fi
return $stat
}

get_ip_address(){

local  ip=$1
local  status=1
local  status_after=1

if ! validate_ip $ip; then
    ip=`host $ip | awk '{ print $4 }'`
fi

validate_ip $ip
status=$?
if [ "$status" == "1" ] ; then 
    echo "doing nslookup for the mme host name $ip"
    juju-log "perfroming nslookup for the mme host name ($ip)"
    validated_hss_public_ip=$(nslookup $ip | awk ' FNR == 5 {print $2 }')
    status_after=$(validate_ip $ip)
    if [ "$status_after" == "1" ] ; then 
	echo "nslookup failed for the mme host name $ip"
	juju-log "nslookup failed for the mme host name ($ip)"
	return $status_after
    else 
	echo "MME ip address is $validated_hss_public_ip"
	return 0
    fi
else 
    validated_hss_public_ip=$ip
    echo "MME ip address is $validated_hss_public_ip"
    return 0
fi 

}

get_eth_ip(){
  echo `ip addr show $1 | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | grep -o [0-9].*`
}

get_eth_ip_net(){
  echo `ip addr show $1 | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+/[0-9]\+' | grep -o [0-9].*`
}
