options:
   branch:
     default: "master"
     description: |
       branch indicates which installation you want to do. If you want an stable installation, change this option to "master". 
     type: string
   revision: 
     default: "6a6ee500ce13df3ae37dc6671ffc9e144df92f45"   
     description: get a specific revison from the openair-cn git repository. 
     type: string
   realm:
     default: "openair4G.eur"
     description: |
       Diameter realm of the MME. HSS and EPC have to have the same. NO empty value.
     type: string
   eth:
     default: "eth0"
     description: |
       This is usefull especially when you are in manual environment so you have your own machines. The default value is eth0. NO empty value.
     type: string
