#!/bin/bash

revision=$1

#declare -a charms=("flexran-rtc" "oai-enb" "oai-mme" "oai-spgw" "oai-hss" "oai-rru" "oai-rru-snap")
declare -a charms=("oai-hss" "oai-mme" "oai-spgw")
declare -a charms=("oai-enb")
declare -a series=("xenial")

for s in "${series[@]}"
do 
    cd ./xenial  #$s
    echo "series: " $s
    for k in "${charms[@]}"
    do
	if [ -d $k ] ; then 	
          cd $k
	  echo "charm: " $k
	  url=`charm push . cs:~navid-nikaein/$s/$k | grep url | cut -f2 -d' '`
	  echo "pushed url: $url"
	  charm release  $url
	  charm grant $url everyone
	  cd ..
	fi 
    done
    cd .. 
    
done 


