#!/bin/bash

revision=$1

#declare -a bundles=("oai-5G-cran-mwc17" "oai-5G-cran-slice-mwc17" "oai-5G-cran-snap-mwc17")
declare -a bundle=("oai-5G-cran" "oai-5g-cran-slice" "oai-5g-cran-snap"  "oai-nfv-4g")

cd bundle
#for k in "${charms[@]}"
for k in "${bundle[@]}"
do
    echo "bundle: " $k
    url=`charm push . cs:~navid-nikaein/bundle/$k | grep url | cut -f2 -d' '`
    echo "pushed url: $url"
    #/usr/bin/charm release $url
    charm release $url
    charm grant $url everyone
    cd ..
done
cd .. 
    


