#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file config-change
# brief manage the config changes of oai-mme service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr and A. B. Molini  

set -ux
source $CHARM_DIR/utils/common
set_env
status-set maintenance "Config-Changed hook"

if [ ! -f $mme_conf ] ; then
    juju-log "MME config file does not exist $mme_conf"
fi

if [ "$(config-get snap)" != "$(cat $CHARM_DIR/.snap)" ]; then
    juju-log "snap channel changed, upgrade charm"
    echo "$(config-get snap)" > $CHARM_DIR/.snap
    $CHARM_DIR/hooks/upgrade-charm
fi


realm=`config-get realm`
iface=`config-get eth`
max_enb=`config-get maxenb`
max_ue=`config-get maxue`
relative_capacity=`config-get relative_capacity`
mme_statistic_timer=`config-get mme_statistic_timer`
emergency_attach_supported=`config-get emergency_attach_supported`
authenticated_imsi_supported=`config-get authenticated_imsi_supported`
verbosity=`config-get verbosity`
gummei_tai_mcc=`config-get gummei_tai_mcc`
gummei_tai_mnc=`config-get gummei_tai_mnc`
#gummei_tai_tac=`config-get gummei_tai_tac` 
ipv4_list_start=`config-get ipv4_list_start`
ipv4_list_end=`config-get ipv4_list_end`
ipv6_list=`config-get ipv6_list`
DEFAULT_DNS_IPV4_ADDRESS=`config-get DEFAULT_DNS_IPV4_ADDRESS`
DEFAULT_DNS_SEC_IPV4_ADDRESS=`config-get DEFAULT_DNS_SEC_IPV4_ADDRESS`
hss_fqdn=`cat $CHARM_DIR/.hss_fqdn`
spgw_s11_ipv4=`cat $CHARM_DIR/.spgw_s11_ipv4`
##############################################################################################

user_conf
stop_mme
oai-cn.mme-init || true

if [ "$realm" != "$(cat $CHARM_DIR/.realm)"  ]; then
    
    fqdn=`hostname --fqdn`
    
    sed -i "s/`hostname --fqdn`/`hostname`.$realm/" /etc/hosts
    
    #keep track of the last realm
    echo "$realm" > $CHARM_DIR/.realm 
fi

if [ -z "$(relation-ids hss)" ]; then
    juju-log "MME is built, but is waiting for active connection to gather the last info"
    juju-log "no HSS is found, so MME is not going to be run"
else
    hss_id=`relation-ids hss`
    hss_unit=`relation-list -r $hss_id`
    if [ "$(relation-get -r $hss_id hss_running $hss_unit)" == "yes" ]; then
        juju-log "Relation with HSS exists and it is running, try to run MME"
        $CHARM_DIR/hooks/start
        #status-set active "MME is running and connected to HSS"
        #if hss relation exists
        for mme_id in $(relation-ids mme); do
           restart=`relation-get -r $mme_id trigger_restart $JUJU_UNIT_NAME`
           relation-set -r $mme_id trigger_restart=$(($((restart + 1)) % 10))
           relation-set -r $mme_id mme_running=yes
        done
    else
        juju-log "HSS relation exists, but it is not running because there no database"
        #status-set blocked "Add db relation to hss to get MME run.."
    fi
fi
