#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file hss-relation-joined 
# brief called when the hss-mme relation is created 
# author navid.nikaein@eurecom.fr

set -eux
source $CHARM_DIR/utils/common

juju-log "Setting up MME relation info for HSS"
relation-set  mme_hostname=`hostname --fqdn`

mme_iface=`config-get eth`
ip_address_mme=`get_eth_ip $mme_iface`

get_ip_address $ip_address_mme
status=$?
if [ "$status" == "1" ] ; then
    status-set error "nslookup failed for the mme host name ($ip_address_mme)"
    relation-set ip_address_mme=$ip_address_mme
else
    relation-set ip_address_mme=$validated_mme_public_ip
fi 

#this need to be passed to hss in order to add a mmeidentity in the table of
#database, this will be done in hss-relation-change in HSS charm.



