#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file hss-relation-departed
# brief called when the hss-mme relation is removed 
# author  navid.nikaein@eurecom.fr and A. B. Molini 

set -eux
source $CHARM_DIR/utils/common
set_env

rm -f $CHARM_DIR/.trigger

juju-log "Stopping OAI MME"

#if hss stops running, MME shouldn't be running because functionalities and procedures
#rely on the HSS.(auth,....)
stop_mme 

juju-log "Delete any relation data trace"
hss_fqdn=`relation-get hss_hostname`
sed -r -i "/$hss_fqdn/ d" /etc/hosts
echo "hss" > $CHARM_DIR/.hss_fqdn
./hooks/config-changed

status-set blocked "waiting for HSS relation"

#stop every enodeB attached to this mme service unit
if [ -n "$(relation-ids mme)" ]; then
    for mme_id in $(relation-ids mme); do
        juju-log ""$mme_id""
        relation-set -r "$mme_id" mme_running=no
    done
fi
