#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file hss-relation-changed 
# brief called when the hss-mme relation is changed 
# author  navid.nikaein@eurecom.fr and A. B. Molini 
set -eux
source $CHARM_DIR/utils/common
set_env_paths
status-set maintenance "Running hss-relation-changed hook"

#Gather everything HSS charm puts on the wire on S6a-mme interface
juju-log "Retrieving HSS relation info"
ip_address_hss=`relation-get ip_address`
hss_fqdn=`relation-get hss_hostname`
hss_running=`relation-get hss_running`
mme_in_db=`relation-get mme_in_db`
trigger_restart=`relation-get trigger_restart`

if [ ! -f $CHARM_DIR/.trigger ]; then
   echo "0" > $CHARM_DIR/.trigger
fi

if [ -z "$ip_address_hss" ]; then 
     juju-log "Data not sent yet"
     exit 0 # exit silently to safely interrupt the execution of the hook without error
fi

if [ "$hss_running" == "no" ]; then
    check_mme_process || true
    if [ $status -eq 0 ]; then
	stop_mme 
       juju-log "The database relation is broken...MME is stopped...and waiting for db"
       #status-set blocked "Add the db relation"
       if [ -n "$(relation-ids mme)" ]; then
          for mme_id in $(relation-ids mme); do
              juju-log ""$mme_id""
              relation-set -r "$mme_id" mme_running=no
          done
       fi
    else
       juju-log "Wait for db relation before starting MME software"
       #status-set blocked "Add the db relation"
    fi
    exit 0
fi

if [ "$mme_in_db" == "no" ]; then
    juju-log "Waiting for the mme insertion in the db......"
    exit 0
elif [ "$mme_in_db" == "yes" ]; then
    juju-log "Mme has been inserted so let's run MME!!!"
fi

#Define entry to link the HSS IP to its FQDN
if [ -z "$(grep -o "$hss_fqdn" /etc/hosts)" ]; then
   echo "$ip_address_hss $hss_fqdn hss" >> /etc/hosts
fi

#sed -r -i "s/No_SCTP/No_TCP/g" $mme_conf_path/freeDiameter/mme_fd.conf
#sed -r -i "s/Prefer_TCP/#Prefer_TCP/" $mme_conf_path/freeDiameter/mme_fd.conf
#sed -r -i "s/Prefer_TCP;/ /" $mme_conf_path/freeDiameter/mme_fd.conf
#sed -r -i "s/Prefer_TCP/ /" $mme_conf_path/freeDiameter/mme_fd.conf

echo "$hss_fqdn" > $CHARM_DIR/.hss_fqdn
./hooks/config-changed

if [ "$trigger_restart" != "$(cat $CHARM_DIR/.trigger)" ]; then
   #update the trigger value in the file
   echo "$trigger_restart" > $CHARM_DIR/.trigger

   #restart the MME software for sure because it means that the config-changed of HSS has been run
   # and so the HSS software has been rerun
   $CHARM_DIR/hooks/start

   if [ -n "$(relation-ids mme)" ]; then
       for mme_id in $(relation-ids mme); do
           juju-log ""$mme_id""
           restart=`relation-get -r $mme_id trigger_restart $JUJU_UNIT_NAME`
           #questo trigger serve solo nel caso in cui faccio juju set di un option di
               #hss.
           relation-set -r $mme_id trigger_restart=$(($((restart + 1)) % 10))
           
           ###
           #relation-set -r "$mme_id" mme_running=yes
           ###this is not needed, but to be sure I leave it, it doesn't bother
       done
   fi
else
    #if the trigger_restart hasn't changed means that if this is hook is running is because
    #the db relation has been added or the hss relation has been added. So for sure the 
    #MME software is not running unless this hook is queued multiple times.

   check_mme_process || true
   #this check is to avoid that every time this hook is called the MME software
   #is restarted even if it is already running and connected to HSS software.


   if [ $status -eq 1 ]; then
       $CHARM_DIR/hooks/start
       if [ -n "$(relation-ids mme)" ]; then
          for mme_id in $(relation-ids mme); do
              juju-log ""$mme_id""
              relation-set -r "$mme_id" mme_running=yes
          done
       fi
   fi

fi
    


