#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
# 
################################################################################
# file install
# brief install the oai-mme from the openairinterface git repository
# author  navid.nikaein@eurecom.fr 

install_packages(){
    
    gitAlreadyInstalled=$(dpkg --get-selections snapd 2>/dev/null | grep -c 'install') || true
    if [ ! $gitAlreadyInstalled -eq 1 ]; then # If git is NOT installed
	apt-get install -y --force-yes snapd # Ensure necessary git dependency exist.
    fi
    
    gitAlreadyInstalled=$(dpkg --get-selections git 2>/dev/null | grep -c 'install') || true
    if [ ! $gitAlreadyInstalled -eq 1 ]; then # If git is NOT installed
       apt-get install -y git # Ensure necessary git dependency exist.
    fi

    atAlreadyInstalled=$(dpkg --get-selections at 2>/dev/null | grep -c 'install') || true
    if [ ! $atAlreadyInstalled -eq 1 ]; then 
       apt-get install -y at
    fi

    mySQLClientInstalled=$(dpkg --get-selections mysql-client 2>/dev/null | grep -c 'install') || true
    if [ ! $mySQLClientInstalled -eq 1 ]; then 
	apt-get install -y --force-yes mysql-client
    fi 

    #Mysql-server simply because we want resolveip tool
    PASSWORD="linux"
    echo "mysql-server mysql-server/root_password password $PASSWORD" | debconf-set-selections
    echo "mysql-server mysql-server/root_password_again password $PASSWORD" | debconf-set-selections

}

clone_repo(){

    juju-log  "Fetching the Mosaic5G repository"
    
    echo -n | openssl s_client -showcerts -connect gitlab.eurecom.fr:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt

    #everytime refresh the installation 
    if [ -d "$mosaic_path" ]; then  
	cd $mosaic_path
	git reset --hard HEAD
	cd - 
    else
	git clone https://gitlab.eurecom.fr/mosaic5g/mosaic5g.git $mosaic_path
    fi

}

update_hostname(){
  HOSTNAME=`echo $JUJU_UNIT_NAME | sed 's|/|-|'`
  echo "$HOSTNAME" > /etc/hostname
  hostname $HOSTNAME
  echo "127.0.0.1 `hostname`" > /etc/hosts
}

configure_hosts(){
  realm=`config-get realm`
  #define fqdn for MME
  if [ -z "$(grep -o "`hostname`.$realm" /etc/hosts)" ]; then
     echo 127.0.0.1 localhost > /etc/hosts
     echo 127.0.0.1 `hostname`.$realm `hostname` mme >> /etc/hosts
  fi
}

build_mme(){
    if [ ! -d $mosaic_path ] ; then 
	mkdir $mosaic_path
    fi
    
    if [ "$snap" == "edge" ] || [ "$snap" == "beta" ] ; then
	juju-log "Installing and building the HSS from OAI-CN snap"
    else
	juju-log "channel $snap is not supported, use edge or beta"
	snap="edge"
    fi

     if [ -z "$(snap list oai-cn)" ] ; then
        op="install"
    else
        op="refresh"
    fi
    sudo snap $op oai-cn --channel=$snap --devmode
    
}

init_mme(){
    oai-cn.stop-all || true

    # this is performed by the snap itself in configure hook
    #oai-cn.mme-init || true 
    # just a flag for start script to run the service
    #echo "yes" > $CHARM_DIR/.oaimme_running_flag
}

configure_network(){
    #allow dhcp
    local eth=$1
    if [ "$eth" = "eth0" ]; then
        echo "Ignore interface eth0"
        return
    fi
    local file=/etc/network/interfaces.d/${eth}.cfg
    cp ./files/eth1_tpl.cfg $file
    sed -i -e "s/eth1/$eth/g" $file

    #prevent dhcp gateway
    local hook=/etc/dhcp/dhclient-enter-hooks.d/net-${eth}
    cp ./files/dhclient_hook_tpl $hook
    sed -i -e "s/eth1/$eth/g" $hook
    chmod +x $hook
}

set -eux

status-set maintenance "Install hook"
export DEBIAN_FRONTEND=noninteractive
source $CHARM_DIR/utils/common
set_env
#echo "no"  > $CHARM_DIR/.oaimme_running_flag

open-port 2152/udp
open-port 2123/udp
open-port 36412/tcp

snap=`config-get snap`
echo "$snap"           >  $CHARM_DIR/.snap

update_hostname

install_packages

configure_network `config-get eth`

#clone_repo

configure_hosts

build_mme

init_mme
