#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file mme-relation-joined 
# brief called when the enb-mme relation is created 
# author navid.nikaein@eurecom.fr and A. B. Molini  
set -eux
source $CHARM_DIR/utils/common

juju-log "Setting up relation settings for OAISIM charm"
#relation-set TAC=`config-get gummei_tai_tac`

#we choose the plmn when we deploy the mme and based on which
#mme we link this oaisim, it will belong to a certain TA.
relation-set MCC=`config-get gummei_tai_mcc`
relation-set MNC=`config-get gummei_tai_mnc`
relation-set trigger_restart=0

mme_iface=`config-get eth`
mme_public_ip=`get_eth_ip $mme_iface`

get_ip_address $mme_public_ip
status=$?
if [ "$status" == "1" ] ; then
    status-set error "nslookup failed for the mme host name ($mme_public_ip)"
    relation-set mme_ip=$mme_public_ip
else
    relation-set mme_ip=$validated_mme_public_ip
fi 


relation-set mme_running=no
#we say a priori that mme is not running just to force
#enb to actually run only if the tac is in the tai list or 
#after having verified that is so.

