#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file mme-relation-changed 
# brief called when the enb-mme relation is changed 
# author  navid.nikaein@eurecom.fr and A. B. Molini 
set -ex
source $CHARM_DIR/utils/common
set_env
status-set maintenance "mme-relation-changed hook"

DEBUG_RESTART=`relation-get DEBUG_RESTART`

if [ -n "$DEBUG_RESTART" ]; then
  juju-log "mme restart is requested"
  stop_mme 
  $CHARM_DIR/hooks/start
  exit 0
fi

TAC=`relation-get TAC`
if [ -z "$TAC" ]; then
   juju-log "Data not available yet, exit silently"
   exit 0
fi
if [ ! -f $CHARM_DIR/tac ]; then
    echo "$TAC" > $CHARM_DIR/tac
fi
#I add the juju unit name because I have to keep this trace for more than
#one oaisim

name=$(echo "$JUJU_REMOTE_UNIT" | sed -r "s/(.*)\//\1-/")

if [ ! -f $CHARM_DIR/tac_$name ]; then
    echo "$TAC" > $CHARM_DIR/tac_$name
fi

#if the TAC is different , is because we have changed the TAC option in
#oaisim during the active relation towards the MME
if [ "$TAC" != "$(cat $CHARM_DIR/tac_$name)" ]; then
   tac_deleted=0
   #$CHARM_DIR/hooks/mme-relation-departed
   old_tac=$(cat $CHARM_DIR/tac_$name)
   tac_line=$(egrep "^$old_tac [0-9]+$" $CHARM_DIR/.tac_list)
   tac_num=$(echo "$tac_line" | cut --delimiter=" " -f 2)
    if [ "$tac_num" -gt 1 ]; then
        tac_num=$((tac_num - 1))
        sed -r -i "s/$tac_line/$TAC $tac_num/" $CHARM_DIR/.tac_list
        sed -r -i "s^$JUJU_REMOTE_UNIT^^" $CHARM_DIR/.tac_list
    else
        tac_deleted=1
        sed -r -i "/$tac_line/ d" $CHARM_DIR/.tac_list
        sed -r -i "s^$JUJU_REMOTE_UNIT^^" $CHARM_DIR/.tac_list
        if [ "$(egrep -c "MCC[ ]*=[ ]*\"$(config-get gummei_tai_mcc)\"[ ]*;[ ]*MNC[ ]*=[ ]*\"$(config-get gummei_tai_mnc)\"[ ]*;[ ]*TAC[ ]*=[ ]*\"[0-9]*\"" $mme_conf)" -gt 1 ]; then
            sed -r -i "/MCC[ ]*=[ ]*\"$(config-get gummei_tai_mcc)\"[ ]*;[ ]*MNC[ ]*=[ ]*\"$(config-get gummei_tai_mnc)\"[ ]*;[ ]*TAC[ ]*=[ ]*\"$old_tac\"/ d" $mme_conf
        fi
    fi

    echo "$TAC" > $CHARM_DIR/tac_$name

fi


#put the tac in the tai list
#max 32 values comma separated 
#the TAC is used to query the dns to pick one S-GW inside the S-GW pool, normally
#In our case the S-gw is not selected in a pool but is
#always the same, like the P-GW............(see SP-GW selection, during initial #attachment  )


#this 'if' is for idempotency
if [ -z "$(grep "$JUJU_REMOTE_UNIT" $CHARM_DIR/.tac_list)"  ]; then
 
   tac_line=$(egrep "^$TAC [0-9]+$" $CHARM_DIR/.tac_list) || true
   if [ -z "$tac_line" ]; then
       #I have to stop the process and run again in order to take into account the new tai list

       echo "$TAC 1" >> $CHARM_DIR/.tac_list
       echo "$JUJU_REMOTE_UNIT" >> $CHARM_DIR/.tac_list
       sed -r -i  "s/MNC=[^;]*;/MNC=\"$(config-get gummei_tai_mnc)\";/" $mme_conf
       sed -r -i  "s/MCC=[^;]*;/MCC=\"$(config-get gummei_tai_mcc)\";/" $mme_conf
       # this is not good practice: bette sed -i "/TAC = \"$TAC\"/!d", but ! expansion does not work in bash
       sed -r -i  "s/TAC = [^;]*;/TAC=\"$TAC\";/" $mme_conf

       if [ -z "$(egrep "MCC[ ]*=[ ]*\"$(config-get gummei_tai_mcc)\"[ ]*;[ ]*MNC[ ]*=[ ]*\"$(config-get gummei_tai_mnc)\"[ ]*;[ ]*TAC[ ]*=[ ]*\"$TAC\"" $mme_conf)" ]; then
	   
	   sed -r -i "/TAI_LIST/a {MCC=\"$(config-get gummei_tai_mcc)\" ; MNC=\"$(config-get gummei_tai_mnc)\";  TAC = \"$TAC\";}" $mme_conf
	   #sed -r -i "/GUMMEI_LIST/a {MCC=\"$(config-get gummei_tai_mcc)\" ; MNC=\"$(config-get gummei_tai_mnc)\";  MME_GID = \"4\"; MME_CODE =\"1\"; }," $mme_conf
	   
       fi
       
       #dovrei fare anche qua il controllo sull'unita perche gli mme and hss relation hooks possono runnare intrecciati come avveniva per l hss charm con
       #hss and db relation hooks
       hss_id=`relation-ids hss`
       
       if [ -n "$hss_id" ]; then
            hss_unit=`relation-list -r $hss_id`
            if [ -n "$hss_unit" ]; then
                 #start
                 if [ "$(relation-get -r $hss_id hss_running $hss_unit)" == "yes" ]; then
                    check_mme_process || true
                    if [ "$status" -eq 0 ]; then

                       for mme_id in $(relation-ids mme); do
                            restart=`relation-get -r $mme_id trigger_restart $JUJU_UNIT_NAME`
                            if [ -n "$restart" ]; then
                               relation-set -r $mme_id trigger_restart=$(($((restart + 1)) % 10))
                            fi
                        done
                        #make sure mme_running var is yes
                        #mme_running=yes
                        
#posso mettere a yes l mme_running della current remote unit e nn anche delle altre
#metterei a yes remote unit per cui il changed (mme) non è ancora stato runnato
#quindi fallirebbero perche il Tac non e ancora stato inserito.
                         
                        relation-set mme_running=yes
                          
                 
                        
                
                    fi
             
             ##################################
                fi
           fi
       fi
    else
      
       tac_num=$(echo "$tac_line" | cut --delimiter=" " -f 2)
       tac_num=$((tac_num + 1))
       sed -r -i "s/$tac_line/$TAC $tac_num/" $CHARM_DIR/.tac_list
       sed -r -i "/^[0-9]+ [0-9]+$/a $JUJU_REMOTE_UNIT" $CHARM_DIR/.tac_list
       

       #in this case we want to start the enb in the current relation only. Because
       #we force enb not to run, but now we have proven that mme doesn't have to be rerun
       #and enb can be run without any problem.
       hss_id=`relation-ids hss`

       if [ -n "$hss_id" ]; then
          hss_unit=`relation-list -r $hss_id`
          if [ -n "$hss_unit" ]; then
             if [ "$(relation-get -r $hss_id hss_running $hss_unit)" == "yes" ]; then
                check_mme_process || true
                if [ "$status" -eq 0 ]; then
   
                #if the tac is different means that we changed the option in the the enb charm
                #and maybe we change the tac to the same of another one, but the mme has to be rerun
                #anyway
                   if [ "$TAC" != "$(cat $CHARM_DIR/tac_$name)" ]; then
                           if [ $tac_deleted -eq 0 ]; then
                               $CHARM_DIR/hooks/start   
                               #qui dovrei fare relation-set restarting=$restaring+1 mod n
                               #per triggerare un restart dell'oaisim
                               for mme_id in $(relation-ids mme); do
                        
                                   restart=`relation-get -r $mme_id trigger_restart $JUJU_UNIT_NAME`
                                   #if the restart is empty means that for another relation between oaisim and mme
                                   #the mme-joined non e stato eseguito, quindi non  devo triggerare
                                   if [ -n "$restart" ]; then
                                       relation-set -r $mme_id trigger_restart=$(($((restart + 1)) % 10))
                                   fi
                           
                               done 
                           else
                               #In this case the mme.conf has not been changed and so no need to restart MME
                               #and so no need to restart all the OAISIM services but,
                               #we only need to restart the current remote OAISIM for which the TAC has been changed
                               restart=`relation-get -r $JUJU_RELATION_ID trigger_restart $JUJU_UNIT_NAME`
                               if [ -n "$restart" ]; then
                                  relation-set trigger_restart=$(($((restart + 1)) % 10))
                               fi
                           fi
                           
                   else
                       relation-set mme_running=yes 
                   fi
                fi
             fi
          fi
       fi
   fi
fi
