#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file mme-relation-departed
# brief called when the enb-mme relation is removed 
# author  navid.nikaein@eurecom.fr and A. B. Molini 
set -ex
source $CHARM_DIR/utils/common
set_env

TAC=`relation-get TAC`

remote_unit=${JUJU_REMOTE_UNIT//\//-}

rm -f $CHARM_DIR/tac_$remote_unit
#rm -f $CHARM_DIR/.$JUJU_RELATION_ID


if [ -n "$(grep "$JUJU_REMOTE_UNIT" $CHARM_DIR/.tac_list)" ]; then

    tac_line=$(egrep "^$TAC [0-9]+$" $CHARM_DIR/.tac_list)
    tac_num=$(echo "$tac_line" | cut --delimiter=" " -f 2)
    if [ "$tac_num" -gt 1 ]; then
        tac_num=$((tac_num - 1))
        sed -r -i "s/$tac_line/$TAC $tac_num/" $CHARM_DIR/.tac_list
        sed -r -i "s^$JUJU_REMOTE_UNIT^^" $CHARM_DIR/.tac_list
    else
        sed -r -i "/$tac_line/ d" $CHARM_DIR/.tac_list
        sed -r -i "s^$JUJU_REMOTE_UNIT^^" $CHARM_DIR/.tac_list
        if [ "$(egrep -c "MCC[ ]*=[ ]*\"$(config-get gummei_tai_mcc)\"[ ]*;[ ]*MNC[ ]*=[ ]*\"$(config-get gummei_tai_mnc)\"[ ]*;[ ]*TAC[ ]*=[ ]*\"[0-9]*\"" $mme_conf)" -gt 1 ]; then


            sed -r -i "/MCC[ ]*=[ ]*\"$(config-get gummei_tai_mcc)\"[ ]*;[ ]*MNC[ ]*=[ ]*\"$(config-get gummei_tai_mnc)\"[ ]*;[ ]*TAC[ ]*=[ ]*\"$TAC\"/ d" $mme_conf
            TAI=$(cat $mme_conf | egrep "MCC[ ]*=[ ]*\"[0-9]+\"[ ]*;[ ]*MNC[ ]*=[ ]*\"[0-9]+\"[ ]*;[ ]*TAC[ ]*=[ ]*\"[0-9]+\"" | tail -1 | egrep -o "MCC[ ]*=[ ]*\"[0-9]+\"[ ]*;[ ]*MNC[ ]*=[ ]*\"[0-9]+\"[ ]*;[ ]*TAC[ ]*=[ ]*\"[0-9]+\"[^,]*,") || true
            if [ -n "$TAI" ]; then
                TAI=${TAI%\},}
                sed -r -i "/$TAI/ s/([^,]*),/\1/" $mme_conf
            fi
        fi

        #now I have to restart the MME software to take into account the new config file
        hss_id=`relation-ids hss` 
        #FOR THE TIME BEING CONSIDER only one hss service and only one unit
        
        if [ -z "$hss_id" ]; then
           
           juju-log "Can't restart the MME because of the departure of hss "
           exit 0
          
        else
          
           hss_unit=`relation-list -r $hss_id`
           if [ -n "$hss_unit" ]; then
               if [ "$(relation-get -r $hss_id hss_running $hss_unit)" == "no" ]; then
                  exit 0
               fi
           else
                  exit 0
           fi
        fi
        #se ce hss relation e il mme.conf is changed , restart mme but first stop every
        #enb and after mme software is running , start every enb attached to this mme

        #for mme_id in $(relation-ids mme); do
        #    juju-log ""$mme_id""
        #    if [ "$mme_id" != "$JUJU_RELATION_ID" ]; then
        #        relation-set -r "$mme_id" mme_running=no
        #    fi
        #done

        $CHARM_DIR/hooks/start

        for mme_id in $(relation-ids mme); do
           juju-log ""$mme_id""
           #this because we can't set relation  data for the current departing relation anylonger
           if [ "$mme_id" != "$JUJU_RELATION_ID" ]; then
              restart=`relation-get -r $mme_id trigger_restart $JUJU_UNIT_NAME`
              relation-set -r $mme_id trigger_restart=$(($((restart + 1)) % 10))
              relation-set -r $mme_id mme_running=yes
           fi
        done
    #this is to establish a new s1 link in order to comunicate the new TAI list to the enodeb
    fi
fi

