#! /bin/bash
################################################################################
# Licensed to the Mosaic5G under one or more contributor license
# work for additional information regarding copyright ownership.
# Apache License, Version 2.0  (the "License");
# You may obtain a copy of the License at
#  
#    	http://www.apache.org/licenses/LICENSE-2.0
#  
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# -------------------------------------------------------------------------------
#   For more information about the Mosaic5G:
#   	contact@mosaic-5g.io
#
#
################################################################################
# file conf
# brief conf scripts and variables for oai-ran Snap
# author Navid Nikaein (navid.nikaein@eurecom.fr, navid.nikaein@mosaic-5g.io)


. $SNAP/common
. $SNAP/util

case "$1" in
    "set-enb" )
	CONFIG_FILE=$2
	if [ "$CONFIG_FILE" != "${CONFIG_FILE#/}" -a  -f "$CONFIG_FILE" ]; then
	    echo_success "Setting the default config file to: $CONFIG_FILE"
	    
	elif [ -f "$CONF_DIR/$CONFIG_FILE" ]; then
	    CONFIG_FILE=$CONF_DIR/$CONFIG_FILE
	    echo_info "Config file found in the $CONF_DIR!"
	    echo_info "Resetting to the default config file: $CONFIG_FILE"

	else
	    echo_error "[ERR] Config file $CONFIG_FILE not found, please provide an absolute path!"
	    echo_info "Reset to default config file: $ENB_CONF_FILE"
	    CONFIG_FILE=$ENB_CONF_FILE
	fi
	snapctl set conf.enb=$CONFIG_FILE
	echo "ENB_CONF_FILE2=$CONFIG_FILE" > $SNAP_DATA/config_enb.sh
	echo "ENB_CONF_FILE2=$CONFIG_FILE"  > $SNAP_USER_DATA/config_enb.sh
	;;

    "set-gnb" )
	CONFIG_FILE=$2
	if [ "$CONFIG_FILE" != "${CONFIG_FILE#/}" -a  -f "$CONFIG_FILE" ]; then
	    echo_success "Setting the default config file to: $CONFIG_FILE"
	    
	elif [ -f "$CONF_DIR/$CONFIG_FILE" ]; then
	    CONFIG_FILE=$CONF_DIR/$CONFIG_FILE
	    echo_info "Config file found in the $CONF_DIR!"
	    echo_info "Resetting to the default config file: $CONFIG_FILE"

	else
	    echo_error "[ERR] Config file $CONFIG_FILE not found, please provide an absolute path!"
	    echo_info "Reset to default config file: $GNB_CONF_FILE"
	    CONFIG_FILE=$GNB_CONF_FILE
	fi
	snapctl set conf.gnb=$CONFIG_FILE
	echo "GNB_CONF_FILE2=$CONFIG_FILE" > $SNAP_DATA/config_gnb.sh
	echo "GNB_CONF_FILE2=$CONFIG_FILE"  > $SNAP_USER_DATA/config_gnb.sh
	;;

    "set-bbu" )
	CONFIG_FILE=$2
	if [ "$CONFIG_FILE" != "${CONFIG_FILE#/}" -a  -f "$CONFIG_FILE" ]; then
	    echo_success "Setting the default config file to: $CONFIG_FILE"
	    
	elif [ -f "$CONF_DIR/$CONFIG_FILE" ]; then
	    CONFIG_FILE=$CONF_DIR/$CONFIG_FILE
	    echo_info "Config file found in the $CONF_DIR!"
	    echo_info "Resetting to the default config file: $CONFIG_FILE"

	else
	    echo_error "[ERR] Config file $CONFIG_FILE not found, please provide an absolute path!"
	    echo_info "Reset to default config file: $BBU_CONF_FILE"
	    CONFIG_FILE=$BBU_CONF_FILE
	fi
	snapctl set conf.enb-bbu=$CONFIG_FILE
	echo "BBU_CONF_FILE2=$CONFIG_FILE" > $SNAP_DATA/config_bbu.sh
	echo "BBU_CONF_FILE2=$CONFIG_FILE"  > $SNAP_USER_DATA/config_bbu.sh
	;;

    "set-rru" )
	CONFIG_FILE=$2
	if [ "$CONFIG_FILE" != "${CONFIG_FILE#/}" -a  -f "$CONFIG_FILE" ]; then
	    echo_success "Setting the default config file to: $CONFIG_FILE"
	    
	elif [ -f "$CONF_DIR/$CONFIG_FILE" ]; then
	    CONFIG_FILE=$CONF_DIR/$CONFIG_FILE
	    echo_info "Config file found in the $CONF_DIR!"
	    echo_info "Resetting to the default config file: $CONFIG_FILE"

	else
	    echo_error "[ERR] Config file $CONFIG_FILE not found, please provide an absolute path!"
	    echo_info "Reset to default config file: $RRU_CONF_FILE"
	    CONFIG_FILE=$RRU_CONF_FILE
	fi
	snapctl set conf.enb-rru=$CONFIG_FILE
	echo "RRU_CONF_FILE2=$CONFIG_FILE" > $SNAP_DATA/config_rru.sh
	echo "RRU_CONF_FILE2=$CONFIG_FILE"  > $SNAP_USER_DATA/config_rru.sh
	;;
    
    "ls-enb" )
	if [ -r $SNAP_DATA/config_enb.sh ]; then
	    . $SNAP_DATA/config_enb.sh
	fi
	
	# default config file is (unless set in above config)
	ENB_CONFIG=${ENB_CONF_FILE2:-$ENB_CONF_FILE}
	ls $(dirname $ENB_CONFIG)/enb*.conf
	
	;;
    
    "ls-gnb" )
	if [ -r $SNAP_DATA/config_gnb.sh ]; then
	    . $SNAP_DATA/config_gnb.sh
	fi
	
	# default config file is (unless set in above config)
	GNB_CONFIG=${GNB_CONF_FILE2:-$GNB_CONF_FILE}
	ls $(dirname $GNB_CONFIG)/gnb*.conf
	
	;;
    "ls-cudu" )
	if [ -r $SNAP_DATA/config_cudu.sh ]; then
	    . $SNAP_DATA/config_cudu.sh
	fi
	
	# default config file is (unless set in above config)
	CUDU_CONFIG=${CUDU_CONF_FILE2:-$CUDU_CONF_FILE}
	ls $(dirname $CUDU_CONFIG)/r*.conf
	;;

    
    "ls-rru" )
	if [ -r $SNAP_DATA/config_rru.sh ]; then
	    . $SNAP_DATA/config_rru.sh
	fi
	
	# default config file is (unless set in above config)
	RRU_CONFIG=${RRU_CONF_FILE2:-$RRU_CONF_FILE}
	ls $(dirname $RRU_CONFIG)/rru*.conf
	;;

    
    "echo-enb" | "cat-enb" )
	
	if [ -r $SNAP_DATA/config_enb.sh ]; then
	    . $SNAP_DATA/config_enb.sh
	fi
	
	# default config file is (unless set in above config)
	ENB_CONFIG=${ENB_CONF_FILE2:-$ENB_CONF_FILE}
	# echo (get), cat (show)
        `echo $1 | cut -d"-" -f1` $ENB_CONFIG
	;;

    "echo-gnb" | "cat-gnb" )
	
	if [ -r $SNAP_DATA/config_gnb.sh ]; then
	    . $SNAP_DATA/config_gnb.sh
	fi
	
	# default config file is (unless set in above config)
	GNB_CONFIG=${GNB_CONF_FILE2:-$GNB_CONF_FILE}
	# echo (get), cat (show)
        `echo $1 | cut -d"-" -f1` $GNB_CONFIG
	;;

    "echo-cudu" | "cat-cudu" )
	
	if [ -r $SNAP_DATA/config_cudu.sh ]; then
	    . $SNAP_DATA/config_cudu.sh
	fi
	
	# default config file is (unless set in above config)
	CUDU_CONFIG=${CUDU_CONF_FILE2:-$CUDU_CONF_FILE}
	# echo (get), cat (show)
        `echo $1 | cut -d"-" -f1` $CUDU_CONFIG
	;;
      
     "echo-rru" | "cat-rru" )
	
	if [ -r $SNAP_DATA/config_rru.sh ]; then
	    . $SNAP_DATA/config_rru.sh
	fi
	
	# default config file is (unless set in above config)
	RRU_CONFIG=${RRU_CONF_FILE2:-$RRU_CONF_FILE}
	# echo (get), cat (show)
        `echo $1 | cut -d"-" -f1` $RRU_CONFIG
	;;

     *)
	 echo_error "unknown command $1"
	 
	;;
esac

#cat >$SNAP_USER_DATA/config.sh <<EOF
#CONFIG=$CONFIG_FILE
#EOF
    
