#! /bin/bash
################################################################################
# Licensed to the Mosaic5G under one or more contributor license
# work for additional information regarding copyright ownership.
# Apache License, Version 2.0  (the "License");
# You may obtain a copy of the License at
#  
#    	http://www.apache.org/licenses/LICENSE-2.0
#  
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# -------------------------------------------------------------------------------
#   For more information about the Mosaic5G:
#   	contact@mosaic-5g.io
#
#
################################################################################
# file init
# brief init scripts and variables for oai-ran Snap
# author Navid Nikaein (navid.nikaein@eurecom.fr, navid.nikaein@mosaic-5g.io)


. $SNAP/common
. $SNAP/util

if_sudo

if [ ! -f $CONF_DIR/rru.conf ] ; then
    cp $SNAP/etc/* $CONF_DIR
else
    #overwriting 
    cp $SNAP/etc/* $CONF_DIR
fi

snapctl set conf.node="enb"

# set the conf
snapctl set conf.enb=$ENB_CONF_FILE #$CONF_DIR/enb.band7.tm1.50PRB.usrpb210.conf
$SNAP/conf set-enb $(snapctl get conf.enb) # $CONF_DIR/enb.band7.tm1.50PRB.usrpb210.conf

snapctl set conf.enb-nsa=$ENB_NSA_CONF_FILE
snapctl set conf.enb-cu=$CU_CONF_FILE
snapctl set conf.enb-du=$DU_CONF_FILE

snapctl set conf.enb-bbu=$BBU_CONF_FILE #$CONF_DIR/rcc.band7.tm1.if4p5.50PRB.conf
$SNAP/conf set-bbu $(snapctl get conf.enb-bbu) 

snapctl set conf.enb-rru=$RRU_CONF_FILE #$CONF_DIR/rru.conf
$SNAP/conf set-rru $(snapctl get conf.enb-rru)


snapctl set conf.gnb=$GNB_CONF_FILE #$CONF_DIR/gnb.band78.tm1.106PRB.usrpn300.conf
snapctl set conf.gnb-nsa=$GNB_NSA_CONF_FILE

$SNAP/conf set-gnb $(snapctl get conf.gnb-nsa) 


snapctl set conf.usrp=$SNAP/uhd_images
snapctl set conf.rfnoc=$SNAP/usr/share/uhd/rfnoc
echo_info "Default USRP images:"  $(snapctl get conf.usrp)
echo_info "Default USRP RFNOC:"  $(snapctl get conf.rfnoc)

apiport=$(grep -m1 "api_port_default" $SNAP/apivars.py | cut -f3 -d " ")
mgrport=$(grep -m1 "api_manager_port_default" $SNAP/apivars.py | cut -f3 -d " ")
apiaddr=$(grep -m1 "api_host_default" $SNAP/apivars.py | cut -f3 -d " " | cut -f3 -d " " | tr -d "'")
mgraddr=$(grep -m1 "api_manager_host_default" $SNAP/apivars.py | cut -f3 -d " " | cut -f3 -d " " | tr -d "'")

if [ ! -z "$apiport" ] ; then 
    snapctl set conf.apiport=$apiport
    echo_info "Default API port :"  $(snapctl get conf.apiport)
else
    echo_error "Could not read api_port_default in apivars.py!"
fi

if [ ! -z "$mgrport" ] ; then 
    snapctl set conf.mgrport=$mgrport
    echo_info "Default MGR port :"  $(snapctl get conf.mgrport)
else
    echo_error "Could not read  api_manager_port_default in apivars.py!"
fi

if [ ! -z "$apiaddr" ] ; then 
    snapctl set conf.apiaddr=$apiaddr
    echo_info "Default API addr :"  $(snapctl get conf.apiaddr)
else
    echo_error "Could not read api_host_default in apivars.py!"
fi

if [ ! -z "$mgraddr" ] ; then 
    snapctl set conf.mgraddr=$mgraddr
    echo_info "Default MGR addr :"  $(snapctl get conf.mgraddr)
else
    echo_error "Could not read api_manager_host_default in apivars.py!"
fi

openapi="http://"$(snapctl get conf.apiaddr)":"$(snapctl get conf.apiport)
snapctl set conf.openapi=$openapi

# a copy all the config files for the user
cp $CONF_DIR/* $SNAP_USER_DATA

echo ""
echo_success "OAI-SIM init: done"

echo ""
echo "$SNAP_NAME snap info:"
snap_info 
