#!/bin/bash

. $SNAP/common
. $SNAP/util

waiting_time=1
check_string="No USRP Device Found"
enb_conf=$(snapctl get conf.enb)
gnb_conf=$(snapctl get conf.gnb)
d="d"
node="enb"

$SNAP/run status-all
sleep $waiting_time 
echo_info "Start $node$d"
$SNAP/run start "$node$d" 
sleep $waiting_time
echo_info "Stop $node$d"
$SNAP/run stop "$node$d"
sleep $waiting_time
$SNAP/run status-all

sleep $waiting_time 
$SNAP/run status-all
sleep $waiting_time 

echo_info "Stop All"
$SNAP/run stop-all
sleep $waiting_time

echo_info "Check and set enb conf"
$SNAP/conf ls-$node
$SNAP/conf set-$node $enb_conf
snapctl get conf.$node

echo_info "Init"
$SNAP/init

echo_info "Start OpenAPI"
$SNAP/run start apid
$SNAP/run journal apid -e -n20 |  egrep -i "Starting Open API|Starting OpenAPI" > /dev/null 2>&1

if [ $? -eq 0 ] ; then
    echo_success "apid test: passed"
else
    echo_error   "apid test: failed"
fi

echo_info "Snap Info"
$SNAP/run info

echo_info "Check $node exec"
$SNAP/run $node -O $enb_conf | grep "$check_string" > /dev/null 2>&1
if [ $? -eq 0 ] ; then
    echo_success "$node Exec: passed"
else
    echo_error   "$node exec: failed"
    exit 1
fi

node="gnb"

$SNAP/run $node  -O $gnb_conf | grep "$check_string" > /dev/null 2>&1
if [ $? -eq 0 ] ; then
    echo_success "$node Exec: passed"
else
    echo_error   "$node exec: failed"
    exit 1
fi



	

