#!/bin/bash

. $SNAP/common
. $SNAP/util

waiting_time=1
check_string="No USRP Device Found"
conf="/var/snap/oai-ran/current/enb.band38.tm1.100PRB.usrpx310.conf"
d="d"
case "$1" in
    "api" )

    ;;
    
    "enb")
	
	$SNAP/run status-all
	sleep $waiting_time 
	echo_info "Start $1$d"
	$SNAP/run start "$1$d" 
	sleep $waiting_time
	echo_info "Stop $1$d"
	$SNAP/run stop "$1$d"
	sleep $waiting_time
	$SNAP/run status-all
	
	sleep $waiting_time 
	$SNAP/run status-all
	sleep $waiting_time 
	
	echo_info "Stop All"
	$SNAP/run stop-all
	sleep $waiting_time

	echo_info "Check and set $1 conf"
	$SNAP/conf ls-$1
	$SNAP/conf set-$1 $conf
	snapctl get conf.$1

	echo_info "Init"
	$SNAP/init
	
	echo_info "Start OpenAPI"
	$SNAP/run start apid
	#echo "curl -Is localhost:$(snapctl get conf.apiport)"
	#curl -Is localhost:$(snapctl get conf.apiport) | head -n 1

	echo_info "Snap Info"
	$SNAP/run info

	echo_info "Check $1 exec"
	$SNAP/run $1 | grep "$check_string" > /dev/null 2>&1
	if [ $? -eq 0 ] ; then
	    echo_success "$1 Exec: passed"
	else
	    echo_error   "$1 exec: failed"
	fi
	
	;;

   
esac

	

