#!/bin/bash

. $SNAP/common
. $SNAP/util

waiting_time=1
waiting_time2=30
check_string="No USRP Device Found"
check_string_sdr="got sync"
d="d"
node="enb"

echo_info "Init"
$SNAP/init

enb_conf=$(snapctl get conf.enb)
gnb_conf=$(snapctl get conf.gnb)

echo ""
echo_info "Services"
$SNAP/run status-all
sleep $waiting_time 
echo_info "Start $node$d"
$SNAP/run start "$node$d" 
sleep $waiting_time
echo_info "Stop $node$d"
$SNAP/run stop "$node$d"
sleep $waiting_time
$SNAP/run status-all

sleep $waiting_time 
$SNAP/run status-all
sleep $waiting_time 

echo_info "Stop All"
$SNAP/run stop-all
sleep $waiting_time

echo ""
echo_info "Check and set enb conf"
$SNAP/conf ls-$node
$SNAP/conf set-$node $enb_conf

echo ""
echo_info "Start OpenAPI"
$SNAP/run start apid
$SNAP/run journal apid -e -n20 |  egrep -i "Starting Open API|Starting OpenAPI" > /dev/null 2>&1

if [ $? -eq 0 ] ; then
    echo_success "apid test: passed"
else
    echo_error   "apid test: failed"
fi

echo ""
echo_info "Snap Info"
$SNAP/run info

echo ""
echo_info "Check $node exec"
$SNAP/conf set-$node $enb_conf
$SNAP/run start "$node$d"
sleep $waiting_time2
$SNAP/run stop "$node$d"

$SNAP/run journal enbd -e -n 500 | egrep "$check_string_sdr|$check_string" > /dev/null 2>&1
if [ $? -eq 0 ] ; then
    echo_success "$node Exec: passed"
else
    echo_error   "$node exec: failed"
    exit 1
fi

node="gnb"
echo ""
echo_info "Check $node exec"
$SNAP/conf set-$node $gnb_conf
$SNAP/run start "$node$d"
sleep $waiting_time2
$SNAP/run stop "$node$d"

$SNAP/run journal gnbd -e -n 500 | egrep "$check_string_sdr|$check_string" > /dev/null 2>&1
if [ $? -eq 0 ] ; then
    echo_success "$node Exec: passed"
else
    echo_error   "$node exec: failed"
    exit 1
fi

#$SNAP/run $node | grep "$check_string" > /dev/null 2>&1
#if [ $? -eq 0 ] ; then
#    echo_success "$node Exec: passed"
#else
#    echo_error   "$node exec: failed"
#    exit 1
#fi

#node="gnb"
#echo_info "Check $node exec"
#$SNAP/conf set-$node "$node"_conf
#$SNAP/run $node  | grep "$check_string" > /dev/null 2>&1
#if [ $? -eq 0 ] ; then
#    echo_success "$node Exec: passed"
#else
#    echo_error   "$node exec: failed"
#    exit 1
#fi



	

