options:
   branch:
     default: "develop"
     description: |
       branch indicates which installation you want to do. If you want an stable installation, change this option to "default". 
     type: string
   revision: 
     default: "head"   
     description: get a specific revison from the openairinterface5G git repository. 
     type: string
   target_hardware:
     default: "usrp"
     description: |
       defines the target RF hardware. Available Options: usrp, bladerf, and sodera. Setting this option will require different configuration file and wil trigger different building process. 
     type: string
   config_file:
     default: "default"
     description: |
       takes the default configuration file based on the target hardware. It defines the specific enb configuration file, see openairinterface5g/targets/PROJECTS/GENERIC-LTE-EPC/CONF. 
     type: string
   eth:
     default: "eth0"
     description: |
       defines the interface to the EPC. Set this option to the interface the machine onto you deploy this charm has. 
     type: string
   TAC:
     default: 1
     description: |
       Set this option to the tracking area code you want this eNB to belong. Possible values are...Tracking area code, 0x0000 and 0xfffe are reserved values
     type: int
   enb_name:
     default: "eNB_Eurecom_LTEBox"
     description: |
       Set this option with the name you want for this eNodeB deployment. 
     type: string
   enb_id:
     default: "0xe00"
     description: |
       Set this option with the id number you want for this eNodeB deployment. 
     type: string
   frame_type:
     default: "FDD"
     description: |
       Setting the frame type, FDD or TDD.
     type: string
   tdd_config:
     default: 3
     description: |
       Setting the TDD frame configuration. Valid values, 0,1,2,3,4,5,6.
     type: int
   tdd_config_s:
     default: 0
     description: |
       Setting the TDD special subframe configuration. Valid values, 0-9.
     type: int
   eutra_band:
     default: 7
     description: |
       Setting the LTE  EUTRA frequency band.
     type: int
   downlink_frequency:
     default: "2680000000L"
     description: |
       Setting the downlink frequency band.
     type: string
   uplink_frequency_offset:
     default: "-120000000"
     description: |
       Setting the uplink frequency offset.
     type: string
   N_RB_DL:
     default: 25
     description: |
       Setting the bandwidth in terms of number of available PRBS, 5MHz (25), 10MHz(50), and 20MHz(100).
     type: int
   nb_antennas_tx:
     default: 1
     description: |
       Setting the number of tx antennas.
     type: int
   nb_antennas_rx:
     default: 1
     description: |
       Setting the number of rx antennas.
     type: int
   tx_gain:
     default: 90
     description: |
       Setting the tx antenna gain.
     type: int
   rx_gain:
     default: 110
     description: |
       Setting the rx antenna gain.
     type: int
   rrh_active:
     default: "no"
     description: |
        activates fronthaul interface to the RRH gateway.
     type: string
   rrh_if_name:
     default: "lo"
     description: |
        defines the network interface name to connect to the RRH. This required a dedicated fronthaul link between eNB and RRH and must not use the same interface as for the EPC.  
     type: string
   rrh_local_port: 
     default: 50000  
     description: |
        defines the network interface port to connect to the RRH
     type: int
   rrh_transport_mode:
     default: "raw"
     description: |
        defines the I/Q sample transport mode. Available mode are udp and raw. If udp, the ip address is expected
     type: string
   rrh_tx_shift: 
     default: 4  
     description: |
        defines the shift in is samples in tx
     type: int
   rrh_tx_sampleadvance:
     default: 113
     description: |
        defines the tx i/q sample advace
     type: int
   rrh_tx_schedadvance:
     default: 9
     description: |
        defines the tx i/q scheduling advance
     type: int



