#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file config-change
# brief manage the config changes of oai-enb service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr 

set -eux

source $CHARM_DIR/utils/common
set_env_paths

node_func=`config-get node_function`
file_config=`cat $CHARM_DIR/.config_file`

if [ "$(config-get branch)" != "$(cat $CHARM_DIR/.branch)" ]; then
    juju-log "branch name changed"
    $CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get revision)" != "$(cat $CHARM_DIR/.revision)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
    juju-log "revision changed"
fi

if [ "$(config-get kernel)" != "$(cat $CHARM_DIR/.kernel)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
    juju-log "kernel changed"
fi
if [ "$node_func" != "$(cat $CHARM_DIR/.node_func)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
    juju-log "node function changed"
fi

if [ "$(config-get target_hardware)" != "$(cat $CHARM_DIR/.hw)" ]; then
    juju-log "hw name changed"
    $CHARM_DIR/hooks/upgrade-charm
fi



# The installation runs unnecessarily multiple times for default config file
if [ "$(config-get config_file)" != "default" ] ; then
  if [ "$file_config" != "$(config-get config_file)" ]; then 
    # we don't know what is changed 
      $CHARM_DIR/hooks/upgrade-charm
      juju-log "config_file changed"
  fi  
fi


fh_tr_mode=`config-get fh_transport_mode`
if [ "$fh_tr_mode" != "$(cat $CHARM_DIR/.fh_tr_mode)" ]; then 
    juju-log "fronthaul $fh_tr_mode changed"
    $CHARM_DIR/hooks/upgrade-charm
fi 

fh_if_name=`config-get fh_if_name`
if [ "$fh_if_name" != "$(cat $CHARM_DIR/.fh_if_name)" ]; then
    sed -r -i "/local_if_name/ s/\".+\"/\"$fh_if_name\"/" $conf_path/$file_config
    if [ "$fh_tr_mode" == "raw" ] || [ "$fh_tr_mode" == "raw_if4p5" ]; then 
	check_ifup $fh_if_name
        status=$?
        if [ "$status" == "0" ] ; then
	   read mac_addr </sys/class/net/$fh_if_name/address
	   echo "$mac_addr"  > $CHARM_DIR/.fh_address
	   sed -r -i "/local_address/ s/\".+\"/\"$mac_addr\"/" $conf_path/$file_config
	else
           juju-log -l WARNING "fh_if_name interface $fh_if_name does not exist"
           status-set blocked "fh_if_name interface $fh_if_name does not exist"
        fi

    elif [ "$fh_tr_mode" == "udp" ] || [ "$fh_tr_mode" == "udp_if4p5" ]; then 
	enb_public_ip=`unit-get public-address`
	get_ip_address $enb_public_ip
	status=$?
	if [ "$status" == "1" ] ; then
	    status-set blocked "nslookup failed for the eNB host name ($enb_public_ip)"
	else
	    echo "$validated_public_ip"  > $CHARM_DIR/.fh_address
	    sed -r -i "/local_address/ s/\".+\"/\"$validated_public_ip\"/" $conf_path/$file_config
	fi 
	
    else 
	status-set blocked "unsupported/invalid fronthaul transport mode"
    fi        
fi
    

###############################################################################
###############################################################################
juju-log "Setting up configuration in the "$file_config" file"
###############################################################################
###############################################################################
frame_type=`config-get frame_type`
tdd_config=`config-get tdd_config`
tdd_config_s=`config-get tdd_config_s`
eutra_band=`config-get eutra_band`
downlink_frequency=`config-get downlink_frequency`
uplink_frequency_offset=`config-get uplink_frequency_offset`
N_RB_DL=`config-get N_RB_DL`
nb_antennas_tx=`config-get nb_antennas_tx`
nb_antennas_rx=`config-get nb_antennas_rx`
tx_gain=`config-get tx_gain`
rx_gain=`config-get rx_gain`

fh_local_port=`config-get fh_local_port`
rru_tx_shift=`config-get rru_tx_shift`
rru_tx_sampleadvance=`config-get rru_tx_sampleadvance`
rru_tx_schedadvance=`config-get rru_tx_schedadvance`

[ -z "$frame_type" ] || (sed -r -i  "s/(frame_type[ \t]*=[ \t]*)\"[a-zA-Z]+\"/\1\"$frame_type\"/" $conf_path/$file_config)
[ -z "$tdd_config" ] || (sed -r -i  "s/(tdd_config[ \t]*=[ \t]*)[0-9]+/\1$tdd_config/" $conf_path/$file_config)
[ -z "$tdd_config_s" ] || (sed -r -i  "s/(tdd_config_s[ \t]*=[ \t]*)[0-9]+/\1$tdd_config_s/" $conf_path/$file_config)
[ -z "$eutra_band" ] || (sed -r -i  "s/(eutra_band[ \t]*=[ \t]*)[0-9]+/\1$eutra_band/" $conf_path/$file_config)
[ -z "$downlink_frequency" ] || (sed -r -i  "s/(downlink_frequency[ \t]*=[ \t]*)[0-9a-zA-Z]+/\1$downlink_frequency/" $conf_path/$file_config)

[ -z "$uplink_frequency_offset" ] || (sed -r -i  "s/(uplink_frequency_offset[ \t]*=[ \t]*)[-0-9]+/\1$uplink_frequency_offset/" $conf_path/$file_config)
[ -z "$N_RB_DL" ] || (sed -r -i  "s/(N_RB_DL[ \t]*=[ \t]*)[0-9]+/\1$N_RB_DL/" $conf_path/$file_config)
[ -z "$nb_antennas_tx" ] || (sed -r -i  "s/(nb_antennas_tx[ ]*=[ ]*)[0-9]+/\1$nb_antennas_tx/" $conf_path/$file_config)
[ -z "$nb_antennas_rx" ] || (sed -r -i  "s/(nb_antennas_rx[ ]*=[ ]*)[0-9]+/\1$nb_antennas_rx/" $conf_path/$file_config)
[ -z "$tx_gain" ] || (sed -r -i  "s/(tx_gain[ ]*=[ ]*)[0-9]+/\1$tx_gain/" $conf_path/$file_config)
[ -z "$rx_gain" ] || (sed -r -i  "s/(rx_gain[ ]*=[ ]*)[0-9]+/\1$rx_gain/" $conf_path/$file_config)

[ -z "$fh_local_port" ] || (sed -r -i "/local_port/ s/\".+\"/\"$fh_local_port\"/" $conf_path/$file_config)
[ -z "$rru_tx_shift" ] ||  (sed -r -i  "s/(iq_txshift[ ]*=[ ]*)[0-9]+/\1$rru_tx_shift/" $conf_path/$file_config)
[ -z "$rru_tx_sampleadvance" ] || ( sed -r -i  "s/(tx_sample_advance[ ]*=[ ]*)[0-9]+/\1$rru_tx_sampleadvance/" $conf_path/$file_config)
[ -z "$rru_tx_schedadvance" ] || ( sed -r -i  "s/(tx_scheduling_advance[ ]*=[ ]*)[0-9]+/\1$rru_tx_schedadvance/" $conf_path/$file_config)


pdsch_referenceSignalPower_b13=-27
pusch_p0_Nominal_b13=-96
pucch_p0_Nominal_b13=-100
rach_preambleInitialReceivedTargetPower_b13=-104

case $eutra_band in
    13)
	sed -r -i  "s/(pdsch_referenceSignalPower[ \t]*=[ \t]*)[0-9]+/\1$pdsch_referenceSignalPower_b13/" $conf_path/$file_config	
	sed -r -i  "s/(pusch_p0_Nominal[ \t]*=[ \t]*)[0-9]+/\1$pusch_p0_Nominal_b13/" $conf_path/$file_config	
	sed -r -i  "s/(pucch_p0_Nominal[ \t]*=[ \t]*)[0-9]+/\1$pucch_p0_Nominal_b13/" $conf_path/$file_config	
	sed -r -i  "s/(rach_preambleInitialReceivedTargetPower[ \t]*=[ \t]*)[0-9]+/\1$rach_preambleInitialReceivedTargetPower_b13/" $conf_path/$file_config	
	;;
    *)
	juju-log "Calibration parameters might not be optimal for band $eutra_band"
	;;
esac
