#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file rru-relation-changed
# brief called when a relation between an eNB and RRU is changed 
# author  navid.nikaein@eurecom.fr 

set -ex
source $CHARM_DIR/utils/common
set_env_paths

juju-log "RRU relation changed for $node_func"

node_func=`config-get node_function`
file_config=`cat $CHARM_DIR/.config_file`

rel_ids=`relation-ids rru`
if [ -z "$rel_ids" ];then
    juju-log "Data not available yet, exit silently"
    exit 0
fi

hw=`relation-get -r $rel_ids TARGET_HARDWARE`
fh_tr_mode=`relation-get -r $rel_ids TRANSPORT_MODE`
# RCC or RAU address
fh_address=`relation-get -r $rel_ids FH_ADDRESS`

if [ -z "$hw" ]; then
    juju-log "HW not available yet, exit silently"
    exit 0
fi

if [ -z "$fh_tr_mode" ]; then
    juju-log "FH TR Mode not available yet, exit silently"
    exit 0
fi

if [ -z "$fh_address" ]; then
    juju-log "FH address not available yet, exit silently"
    exit 0
fi

sed -r -i "/remote_address/ s/\".+\"/\"$fh_address\"/"  $conf_path/$file_config

tr_mode_config=`cat $CHARM_DIR/.fh_tr_mode`
if [ "$tr_mode_config" != "$fh_tr_mode" ]; then
    juju-log "FH transport mode does not match"
    status-set blocked "FH transport mode does not match, change the oai-rru config"
    cat $fh_tr_mode > $CHARM_DIR/.fh_tr_mode
fi



#locally selected hardware target
hw_config=`cat $CHARM_DIR/.hw`

# this happens when the enb changes the target hardware
if [ "$hw_config" != "$hw" ]; then
    juju-log "Configured RF ($hw) does not corresponds ($hw_config), change the config file"
    status-set blocked "Configured RF ($hw) does not corresponds the remote RF ($hw_config), change the oai-rru config file"
    cat $hw_config > $CHARM_DIR/.hw
fi 

cp  $CHARM_DIR/.fh_tr_mode $openair_path
cp  $CHARM_DIR/.hw      $openair_path

# start the RRU
$CHARM_DIR/hooks/start

# now start the eNB if rru is running
if [ -f $CHARM_DIR/.rru_running ]; then
  rru_running=`cat $CHARM_DIR/.rru_running`
else
  rru_running="no"
  #$CHARM_DIR/hooks/upgrade-charm
  if [ "$(cat $CHARM_DIR/.rru_running_flag)" == "yes" ]; then
      status-set maintenance "Trouble with rru upstart file...reconfiguring the charm"
      $CHARM_DIR/hooks/config-changed
  else
      status-set maintenance "Trouble with rru upstart file...upgrading the charm"
      $CHARM_DIR/hooks/upgrade-charm
  fi 
fi

if [ -f $CHARM_DIR/.fh_address ]; then
    fh_address=`cat $CHARM_DIR/.fh_address`
else
    fh_address="no"
fi

relation-set RRU_RUNNING=$rru_running
relation-set RRU_PORT=`config-get fh_local_port`
relation-set RRU_ADDRESS=$fh_address
