#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file rtc-relation-changed
# brief called when a relation between an eNB and RTC is changed 
# author  navid.nikaein@eurecom.fr

set -ex
source $CHARM_DIR/utils/common
set_env_paths

rel_ids=`relation-ids rtc`

if [ -z "$rel_ids" ];then
   juju-log "Data not available yet, exit silently"
   exit 0
fi

agent_active=`relation-get -r $rel_ids AGENT_ACTIVE`

if [ -z "$agent_active" ]; then
   juju-log "Agent is not active yet, exit silently"
   exit 0
fi


if [ "$agent_active" == "yes" ]; then  

    echo "$agent_active" >  $CHARM_DIR/.agent_active
    relation-set RTC_PORT=`config-get bind_port`
    
    rtc_public_ip=`unit-get public-address`
    get_ip_address $rtc_public_ip
    status=$?
	  
    if [ "$status" == "1" ] ; then
	status-set error "nslookup failed for the rru host name ($rtc_public_ip)"
	relation-set RTC_PUBLIC_IP=$rtc_public_ip
    else
	relation-set RTC_PUBLIC_IP=$validated_public_ip
	status-set maintenance "Joined the RTC relation"
    fi 
    
    $CHARM_DIR/hooks/start

else 
    status-set blocked "RAN/eNB Agent is not yet active"
fi
