name: oai-ran
version: '1.3' 
summary: OpenAirInterface RAN entity with FlexRAN Agent/Runtime 
description: |
    OAI RAN is the openairinterface-based RAN with different deployment flavor (eNB,C-RAN, CU,DU, RRU) with FlexRAN agent/runtime allowing to connect any commercial UEs with the band of your choice. It is one of the projects of Mosaic5G inititive.
grade: stable
type: app
architectures:
  - amd64
  - i386
confinement: devmode

apps:
  test:
    command: test all
  info:
    command: run info
  status-all:
    command: run status-all
  stop-all:
    command: run stop-all
  enb:
    command: run enb
  cudu:
    command: run cudu
  rru:
    command: run rru
  init:
    command: init
  enbd:
    command: run enb
    daemon: simple
    stop-command: run stop enbd
    stop-timeout: 7s
  cudud:
    command: run cudu
    daemon: simple
    stop-command: run stop cudud
    stop-timeout: 7s
  rrud:
    command: run rru
    daemon: simple
    stop-command: run stop rrud
    stop-timeout: 7s
  enb-start:
    command: run start enbd
  enb-stop:
    command: run stop enbd
  enb-restart:
    command: run restart enbd 
  enb-status:
    command: run status enbd
  enb-journal:
    command: run journal enbd
  cudu-start:
    command: run start cudud
  cudu-stop:
    command: run stop cudud
  cudu-restart:
    command: run restart cudud 
  cudu-status:
    command: run status cudud
  cudu-journal:
    command: run journal cudud 
  rru-start:
    command: run start rrud 
  rru-stop:
    command: run stop rrud
  rru-restart:
    command: run restart rrud 
  rru-status:
    command: run status rrud
  rru-journal:
    command: run journal rrud
  help:
    command: run help
  enb-debug:
    command: run gdb-enb
  cudu-debug:
    command: run gdb-cudu  
  cudu-conf-set:
    command: conf set-cudu
  cudu-conf-get:
    command: conf echo-cudu
  cudu-conf-show:
    command: conf cat-cudu
  cudu-conf-list:
    command: conf ls-cudu
  enb-conf-set:
    command: conf set-enb
  enb-conf-get:
    command: conf echo-enb
  enb-conf-show:
    command: conf cat-enb
  enb-conf-list:
    command: conf ls-enb
  rru-conf-set:
    command: conf set-rru
  rru-conf-get:
    command: conf echo-rru
  rru-conf-show:
    command: conf cat-rru
  rru-conf-list:
    command: conf ls-rru
hooks:
  install:
    plugs: [home, network]
  configure:
    plugs: [home, network]

parts:
  gdb:
    plugin: nil
    override-build: |
      sudo apt install gdb -y
      mkdir $SNAPCRAFT_PART_INSTALL/share 
      cp -r /usr/share/gdb $SNAPCRAFT_PART_INSTALL/share
      cp /usr/bin/gdb* $SNAPCRAFT_PART_INSTALL
    prime:
      - gdb*
      - share/*
  enb:
    plugin: cmake
    source: https://gitlab.eurecom.fr/oai/openairinterface5g.git
    source-branch: develop
    build-packages: [build-essential, ]
    override-build: |
      cd cmake_targets
      ./build_oai -I -w USRP --uhd-images-dir ../common/uhd_images
      ./build_oai --eNB -w USRP -c -C 
      cd -   
      mkdir -p $SNAPCRAFT_PART_INSTALL/enb
      cp  targets/bin/* $SNAPCRAFT_PART_INSTALL/enb
      cp -r common/uhd_images $SNAPCRAFT_PART_INSTALL/ 
      cp targets/PROJECTS/GENERIC-LTE-EPC/CONF/* $SNAPCRAFT_PART_INSTALL/enb
      cp cmake_targets/snap_environment.sh $SNAPCRAFT_PART_INSTALL/enb
    stage:
      - enb/*
      - usr/lib/*
      - lib/*
      - uhd_images/*
    prime:
      - enb/*
      - usr/lib/*
      - lib/*
      - uhd_images/*
    organize:
      enb/liboai_usrpdevif.so.Rel14: usr/lib/liboai_device.so
      enb/libcoding.so: usr/lib/libcoding.so
      enb/libparams_libconfig.so: usr/lib/libparams_libconfig.so
      enb/lte-softmodem.Rel14: enb/oai-ran

  cudu:
    plugin: cmake
    source: https://gitlab.eurecom.fr/oai/openairinterface5g.git
    source-branch: develop
    build-packages: [build-essential, ]
    override-build: |
      cd cmake_targets
      ./build_oai -I -w USRP --uhd-images-dir ../common/uhd_images
      ./build_oai --eNB -w USRP -t ETHERNET -c -C 
      cd -
      mkdir -p $SNAPCRAFT_PART_INSTALL/cudu
      cp  targets/bin/* $SNAPCRAFT_PART_INSTALL/cudu
      cp -r common/uhd_images $SNAPCRAFT_PART_INSTALL/ 
      cp targets/PROJECTS/GENERIC-LTE-EPC/CONF/* $SNAPCRAFT_PART_INSTALL/cudu
      cp cmake_targets/snap_environment.sh $SNAPCRAFT_PART_INSTALL/cudu
    stage:
      - cudu/*
      - usr/lib/*
      - lib/*
      - uhd_images/*
    prime:
      - cudu/*
      - usr/lib/*
      - lib/*
      - uhd_images/*
    organize:
      cudu/liboai_eth_transpro.so.Rel14: usr/lib/liboai_transpro.so
      cudu/lte-softmodem.Rel14: cudu/oai-ran

  frontend:
    plugin: dump
    source: frontend
