#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file config-change
# brief manage the config changes of flexran-rtc service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr

set -eux

source $CHARM_DIR/utils/common
set_env_paths

RTC_UNIT_RUNNING=0

if [ "$(config-get branch)" != "$(cat $CHARM_DIR/.branch)" ]; then
    juju-log "branch name changed"
    $CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get revision)" != "$(cat $CHARM_DIR/.revision)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
    juju-log "revision changed"
fi

if [ "$(config-get kernel)" != "$(cat $CHARM_DIR/.kernel)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
    juju-log "kernel changed"
fi

bind_if=`config-get bind_if`
if [ "$bind_if" != "$(cat $CHARM_DIR/.bind_if)" ]; then
    juju-log "changing bind if is not yet supported for RTC" 
    #service rtc restart
fi

bind_port=`config-get bind_port`
if [ "$bind_port" != "$(cat $CHARM_DIR/.bind_port)" ]; then
    juju-log "changing bind port number is not yet supported for RTC" 
    #service rtc restart
fi

iface=`config-get eth`

if [ -n "$iface" ]; then
   ipv4=`ifconfig $iface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`
   
   juju-log "eth interface is $iface"

fi


