#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file rrh-relation-changed
# brief called when a relation between an eNB and RRH is changed 
# author  navid.nikaein@eurecom.fr, kostas.katsalis@eurecom.fr

set -ex
source $CHARM_DIR/utils/common
set_env_paths

rel_ids=`relation-ids rtc`

if [ -z "$rel_ids" ];then
   juju-log "Data not available yet, exit silently"
   exit 0
fi

rtc_active=`relation-get -r $rel_ids RTC_ACTIVE`

if [ -z "$rtc_active" ]; then
   juju-log "Data not available yet, exit silently"
   exit 0
fi


if [ "$rtc_active" == "yes" ]; then  

    relation-set RTC_GW_PORT=`config-get bind_port`

    fh_if=`config-get rtc_if`
    echo "$fh_if"  >  $CHARM_DIR/.rtc_if
    cp  $CHARM_DIR/.rtc_if      $openair_path


    rtc_public_ip=`unit-get public-address`
    get_ip_address $rtc_public_ip
    status=$?
	  
    if [ "$status" == "1" ] ; then
      status-set error "nslookup failed for the rrh host name ($rtc_public_ip)"
      relation-set RTC_GW_PUBLIC_IP=$rtc_public_ip
    else
      relation-set RTC_GW_PUBLIC_IP=$validated_public_ip
      status-set maintenance "Joined the RTC relation"
    fi 


    echo "$rtc_active" >  $CHARM_DIR/.rtc_active

    
    $CHARM_DIR/hooks/start
    #check the result
    status=$?
    if [ $status -eq 0 ]; then
	relation-set RTC_GW_RUNNING=yes
    echo "yes" > $CHARM_DIR/.rtc_running
	status-set active "OAI RTC GW is running"
    else 
	#relation-set RTC_GW_RUNNING=no
	status-set blocked "OAI RTC GW is not running"
    fi  
else 
    status-set blocked "RTC is not set to be active by eNB. Set the rtc_active"
fi
