#!/bin/sh

export DEBIAN_FRONTEND=noninteractive
set -e

CONF_DIR="$SNAP_DATA"

FLEXRAN_DIR="$SNAP"
LOG_CONF_FILE="$CONF_DIR/basic_log"
FLEXRAN_SBI_PORT="$CONF_DIR/sbi_config.sh"
FLEXRAN_NBI_PORT="$CONF_DIR/nbi_config.sh"
FLEXRAN_EXEC="$FLEXRAN_DIR/bin/$SNAP_NAME"
