#!/bin/sh

. $SNAP/common

case "$1" in
    "sbi" )
	echo "SBI_PORT=$2" > $CONF_DIR/sbi_config.sh
	echo "SBI_PORT=$2" > $SNAP_USER_DATA/sbi_config.sh
	;;
    "nbi" )
	echo "NBI_PORT=$2" > $CONF_DIR/nbi_config.sh
	echo "NBI_PORT=$2" > $SNAP_USER_DATA/nbi_config.sh
	;;
    
    "ports" )
	. $CONF_DIR/sbi_config.sh
	. $CONF_DIR/nbi_config.sh
	echo "SBI_PORT:  $SBI_PORT"
	echo "NBI_PORT:  $NBI_PORT"
 	;;
    * )
	echo "unknow option: $1"
	;;
    
esac
    

  
