#!/bin/bash

. $SNAP/common
. $SNAP/util

snapctl set port.sbi=2210 port.nbi=9999

sbi="$(snapctl get port.sbi)"
nbi="$(snapctl get port.nbi)"

if [ -z "$sbi" -o -z "$nbi" ]; then
    echo_error "SBI or NBI are not set!"
    exit -1 
fi
echo "NBI_PORT=$nbi" > $CONF_DIR/nbi_config.sh
echo "SBI_PORT=$sbi" > $CONF_DIR/sbi_config.sh

$SNAP/conf sbi $sbi
$SNAP/conf nbi $nbi
    

# show the conf
$SNAP/conf ports


echo_success "FlexRAN init: done"
