#!/bin/sh -e

. $SNAP/common

snapctl set port.sbi=2210 port.nbi=9999

sbi="$(snapctl get port.sbi)"
nbi="$(snapctl get port.nbi)"

if [ -z "$sbi" -o -z "$nbi" ]; then
    echo "SBI and NBI are not set!"
    exit -1 
fi


echo "SBI $sbi and NBI $nbi are properly set!"
$SNAP/conf sbi $sbi
$SNAP/conf nbi $nbi
    

# show the conf
$SNAP/conf ports


echo "FlexRAN init: done "
