#!/bin/sh

. $SNAP/common

if [ ! -e $FLEXRAN_EXEC ]; then
    echo "Command $FLEXRAN_EXEC not found"
    exit 127
fi		   	   

if [ -r $CONF_DIR/sbi_config.sh ] ; then 
    . $CONF_DIR/sbi_config.sh
else
    . $FLEXRAN_DIR/etc/sbi_config.sh 
    cp $FLEXRAN_DIR/etc/sbi_config.sh $CONF_DIR
fi

if [ -r $CONF_DIR/nbi_config.sh ] ; then 
    . $CONF_DIR/nbi_config.sh
else
    . $FLEXRAN_DIR/etc/nbi_config.sh 
    cp $FLEXRAN_DIR/etc/nbi_config.sh $CONF_DIR
fi
    
FLEXRAN_EXEC_ARGS=" -p $SBI_PORT -n $NBI_PORT"

case "$1" in
    "gdb" )
        cd $SNAP/bin
	echo "Running $SNAP_NAME with the gdb"
	touch      $SNAP_DATA/.gdb_$SNAP_NAME
	chmod 777  $SNAP_DATA/.gdb_$SNAP_NAME
	echo "file $FLEXRAN_EXEC"           > $SNAP_DATA/.gdb_$SNAP_NAME
	echo "set args $FLEXRAN_EXEC_ARGS" >> $SNAP_DATA/.gdb_$SNAP_NAME
	echo "run"                         >> $SNAP_DATA/.gdb_$SNAP_NAME
	cat $SNAP_DATA/.gdb_$SNAP_NAME
	exec $SNAP/gdb --data-directory=$SNAP_DATA  -n -x $SNAP_DATA/.gdb_$SNAP_NAME
	;;
    "start"  )
	snap start $SNAP_NAME
	;;
    "stop" )
	snap stop $SNAP_NAME
	;;
    "restart" )
	snap restart $SNAP_NAME
	;;
    "status" )
	systemctl status  snap.$SNAP_NAME.daemon.service
	;;
    "journal" )
	journalctl -u snap.$SNAP_NAME.daemon.service
	;;
    "help" )
	echo "Usage:            sudo $SNAP_NAME or $SNAP_NAME.[options]"
	echo "Note:             root priviliage required"
	echo "Options:"
	echo "  debug:          debug the $SNAP_NAME with gdb"
	echo "  start:          start the $SNAP_NAME daemon"
	echo "  stop:           stop the $SNAP_NAME daemon"
	echo "  restart:        restart the $SNAP_NAME daemon"
	echo "  status:         get the $SNAP_NAME status"
	echo "  journal:        get the $SNAP_NAME logs"
	echo ""
	echo "  flexran:        run FLEXRAN as a process "
	echo "  sbi-port [port]:set the FLEXRAN SBI port  "
	echo "  nbi-port [port]:set the FLEXRAN NBI port"
	echo "  port            get the FLEXRAN SBI and NBI ports"
	
	echo "  help:           print this help"
	;;	
    *)
	export FLEXRAN_RTC_HOME=$FLEXRAN_DIR
	echo "$FLEXRAN_EXEC  $FLEXRAN_EXEC_ARGS"
	$FLEXRAN_EXEC  `echo $FLEXRAN_EXEC_ARGS` "$@"
	;;
esac
