#! /bin/bash
################################################################################
# Licensed to the Mosaic5G under one or more contributor license
# work for additional information regarding copyright ownership.
# Apache License, Version 2.0  (the "License");
# You may obtain a copy of the License at
#  
#    	http://www.apache.org/licenses/LICENSE-2.0
#  
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# -------------------------------------------------------------------------------
#   For more information about the Mosaic5G:
#   	contact@mosaic-5g.io
#
#
################################################################################
# file util
# brief util scripts and variables for flexran Snap
# author Navid Nikaein (navid.nikaein@eurecom.fr, navid.nikaein@mosaic-5g.io)


. $SNAP/common

black='[30m'
red='[31m'
green='[32m'
yellow='[33m'
blue='[1;34m'
magenta='[35m'
cyan='[36m'
white='[37m'
reset_color='[00m'
COLORIZE=1

cecho()  {  
    # Color-echo
    # arg1 = message
    # arg2 = color
    local default_msg="No Message."
    message=${1:-$default_msg}
    color=${2:-$green}
    [ "$COLORIZE" = "1" ] && message="$color$message$reset_color"
    echo -e "$message"
    return
}

echo_error()   { cecho "$*" $red          ;}
echo_fatal()   { cecho "$*" $red; exit -1 ;}
echo_warn()    { cecho "$*" $yellow       ;}
echo_success() { cecho "$*" $green        ;}
echo_info()    { cecho "$*" $blue         ;}

if_sudo(){

    if [ "$(id -u)" -eq 0 ] ; then
	return 0
    else
	echo "Please run as a sudoer!"
	exit 1
    fi
}

set_health(){
    
    status=$(snapctl services $SNAP_NAME.flexrand)
    case "$status" in
	*inactive*)
	    #echo "Service inactive"
	    snapctl set-health --code=ready blocked "$SNAP_NAME ready to be run"

	    ;;
	*active*)
	    #echo "Service active"
	    snapctl set-health okay
	    ;;
	*)
            #echo "Unknown service state"
	    snapctl set-health --code=error error "Execution failed. Checked the Journal"
	    ;;
    esac 
    
}

snap_isconnected(){

    echo_warn "Plug $1: snap connect $SNAP_NAME:$1"
    snapctl is-connected $1
    echo_success "$1 connected"
    
}

check_service(){

    if [ "$1" == "" ] ; then
	echo_error "service name is missing"
	return 3
    fi
    
    status=$(snapctl services $SNAP_NAME.$1)
    sleep 1
    case "$status" in
	*inactive*)
	    return 1
	;;
	*active*)
	    return 0
	    ;;
	*)
	    return 2
            ;;
    esac 
    
}

snap_info(){
    echo_info "Snap Name: $SNAP_NAME"
    echo_info "Snap Instance Name: $SNAP_INSTANCE_NAME"
    echo_info "Sanp Version: $SNAP_VERSION"
    echo_info "Sanp Revision: $SNAP_REVISION"
    echo_info "Snap Data: $SNAP_DATA"
    echo_info "Snap Conf : "
    snapctl get conf
    echo_warn 'Snap Permissions to be granted:
    	- log-observe
        - process-control'
	          
    echo ""
    echo_warn "Check current permissions: snap connection $SNAP_NAME"
}

snap_help(){
    echo_info "Usage:             sudo $SNAP_NAME or $SNAP_NAME.[options]"
    echo "Note:              root priviliage required"
    echo "Options:"
    echo "  info:            get $SNAP_NAME info"
    #	echo "  debug:          debug the $SNAP_NAME with gdb"
    echo "  start:           start the $SNAP_NAME daemon"
    echo "  stop:            stop the $SNAP_NAME daemon"
    echo "  restart:         restart the $SNAP_NAME daemon"
    echo "  status:          get the $SNAP_NAME status"
    echo "  journal:         get the $SNAP_NAME logs"
    echo ""
    echo "  flexran:         run FLEXRAN as a process "
    echo "  init:            reset the ports to their default values"
    echo "  check:           check the $SNAP_NAME configuration and execution"
    echo "  conf-get:        get log conf file"
    echo "  conf-list:       list log conf file"
    echo "  conf-show:       show the log conf file"
    echo "  conf-set:        set log conf file"
    echo ""
    echo "  ports            get the FLEXRAN ports  "
    echo "  addr             get the FLEXRAN addresses  "
    echo "  sbi-port [port]  set the FLEXRAN SBI port  "
    echo "  sbi-addr [addr]  set the FLEXRAN SBI address  "
    echo "  nbi-port [port]  set the FLEXRAN NBI port"
    echo "  nbi-addr [addr]  set the FLEXRAN NBI address"
    echo "  ports            get the FLEXRAN SBI and NBI ports"
    echo ""
    echo "  help:            print this help"
}
