#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file start 
# brief start oai-enb service, this happens after install or config changed hooks
# author  navid.nikaein@eurecom.fr and  A. B. Molini   

set -eux

source $CHARM_DIR/utils/common
rrh_active=`config-get rrh_active`
rrh_rel=`relation-ids rrh`
if [ -f $CHARM_DIR/.rrh_gw_running ]; then
  rrh_gw_running=`cat $CHARM_DIR/.rrh_gw_running`
else
  rrh_gw_running="no"
fi

if [ ! -z "$(relation-ids epc)" ]; then
  if [ "$rrh_active" == "no" ] || ([ "$rrh_active" == "yes" ] && [ "$rrh_gw_running" == "yes" ] && [  -n "$rrh_rel" ]); then
    service oaieNB restart || service oaieNB start
    check_oaieNB_process
    if [ $status -eq 1 ]; then
       juju-log "Trouble with OAIENB upstart file...try to upgrade the charm"
       status-set blocked "Trouble with OAIENB upstart file...try to upgrade the charm"
       exit 1
    fi 
  fi
   #check connection with MME   check_oaieNB_connection 

fi

