#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file config-change
# brief manage the config changes of oai-enb service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr

set -eux
source $CHARM_DIR/utils/common
set_env
status-set maintenance "Config-Changed hook"

if [ ! -f $hss_conf ] ; then
    juju-log "HSS config file does not exist $hss_conf"
fi

if [ "$(config-get snap)" != "$(cat $CHARM_DIR/.snap)" ]; then
    juju-log "snap channel changed, upgrade charm"
    echo "$(config-get snap)" > $CHARM_DIR/.snap
    $CHARM_DIR/hooks/upgrade-charm
fi


if [ "$(config-get realm)" != "$(cat $CHARM_DIR/.realm)" ]; then
    realm=`config-get realm`
    
    echo "$realm" > $CHARM_DIR/.realm

    sed -i "s/`hostname --fqdn`/`hostname`.$realm/" /etc/hosts
      
    fqdn=`hostname --fqdn`
  
    #sed the new identity in acl.conf and hss_fd.conf
    sed -r -i  "s/(Identity[ ]*=[ ]*)\".*\"/\1\"$fqdn\"/" $hss_fd_conf
    sed -r -i  "s/(Realm[ ]*=[ ]*)\".*\"/\1\"$realm\"/" $hss_fd_conf
    sed -r -i  "s/(^ALLOW_OLD_TLS[ ]*).*/\1*.$realm/" $acl_conf
    
    oai-cn.hss-init || true  #$snap_dir/run hss-certificate
    
fi

if [ -z "$(relation-ids db)" ]; then
   juju-log "HSS is built, but is waiting for active connection to gather the last info"
   juju-log "no db is found, so HSS process is not going to be run" 
else
   $CHARM_DIR/hooks/start
   #if hss relation exists
   for hss_id in $(relation-ids hss); do
       restart=`relation-get -r $hss_id trigger_restart $JUJU_UNIT_NAME`
       relation-set -r $hss_id trigger_restart=$(($((restart + 1)) % 10))
       relation-set -r $hss_id hss_running=yes
   done

fi

#sed -r -i "s/(OPERATOR_key[^\"]*)\".*\"/\1\"$oai_op_key\"/" $hss_conf
