#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file hss-relation-joined 
# brief called when the hss-epc relation is created 
# author navid.nikaein@eurecom.fr

status-set maintenance "hss-relation-joined hook"
set -eux
source $CHARM_DIR/utils/common

juju-log "Setting up HSS relation info for EPC"
relation-set hss_hostname=`hostname --fqdn`

hss_iface=`config-get eth`
hss_public_unit_ip=`unit-get public-address`
hss_public_ip=`get_eth_ip $hss_iface`

get_ip_address $hss_public_ip
status=$?
if [ "$status" == "1" ] ; then
    status-set error "nslookup failed for the mme host name ($hss_public_ip)"
    relation-set ip_address=$hss_public_ip
else
    relation-set ip_address=$validated_hss_public_ip
fi 

#if there is already a db relation, check whether hss is already running
#if [ -n "$(relation-ids db)" ]; then
    #add a check if it is really running
    #maybe we add a hss relation and right after a db relation and so
    #we have the db relation, but not HSS running yet.
    check_hss_process || true
    if [ "$status" -eq 0 ]; then
       relation-set hss_running=yes
    else
       relation-set hss_running=no
    fi
#fi

relation-set trigger_restart=0
relation-set mme_in_db=no


