#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file hss-relation-changed 
# brief called when the hss-epc relation is changed 
# author  navid.nikaein@eurecom.fr and A. B. Molini 

set -ex

status-set maintenance "hss-relation-changed hook"

juju-log "Retrieving MME relation info"
mme_fqdn=`relation-get mme_hostname`
IP_mme=`relation-get ip_address_mme`

if [ -z "$mme_fqdn" ]; then
   juju-log "Data not sent yet"
   exit 0 # exit silently to safely interrupt the execution of the hook without error
fi

#inserting the fqdn in the appropriate file together with the IP address
if [ -z "$(grep -o "$mme_fqdn" /etc/hosts)" ]; then
   echo "$IP_mme $mme_fqdn mme" >> /etc/hosts
fi

db_id=`relation-ids db`
if [ -z "$db_id" ] ; then
     juju-log "Can't add the MME in the database, db unit hasn't been observed yet by the HSS unit"
     exit 0
fi

db_unit=`relation-list -r $db_id`
if [ -z "$db_unit" ]; then
     juju-log "Can't add the MME in the database, database relation needed "
     exit 0
fi


#No cycle, only one database master.
db_user=`relation-get -r "$db_id" user $db_unit`
db_password=`relation-get -r "$db_id" password $db_unit`
db_host=`relation-get -r "$db_id" host $db_unit`
db_database=`relation-get -r "$db_id" database $db_unit`
#could be that the db-joined (mysql) has not been called yet
if [ -z "$db_user" ]; then
   juju-log "Data not sent yet"
   exit 0
fi
#Now we insert the mme info in mysql database

realm_mme=${mme_fqdn#*.}

#check if there is already the mme for idempotency

if [ -z "$(/usr/bin/mysql -u $db_user --password=$db_password -h $db_host $db_database -e "select mmehost from mmeidentity where mmehost='$mme_fqdn'";)" ]; then

#count how many in order to compute the right primary key

primary_key=`/usr/bin/mysql -u $db_user --password=$db_password -h $db_host $db_database -e "select max(idmmeidentity) from mmeidentity;" | egrep [0-9]+`

primary_key=$((primary_key + 1))

juju-log "Inserting the MME info in the mmeidentity table of oai_db database"
#Inserting the mme in the database to let epc connect to hss
/usr/bin/mysql -u $db_user --password=$db_password -h $db_host $db_database << EOF 
INSERT INTO mmeidentity (\`idmmeidentity\`, \`mmehost\`, \`mmerealm\`, \`UE-Reachability\`) VALUES ('$primary_key', '$mme_fqdn', '$realm_mme', 0);
EOF

fi

#let's force hss-relation-changed on epc side to run again, because now epc can actually be run.
relation-set mme_in_db=yes


 



