#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file hss-relation-departed
# brief called when the hss-epc relation is removed 
# author  navid.nikaein@eurecom.fr and A. B. Molini 

set -ex
mme_fqdn=`relation-get mme_hostname`

sed -r -i "/$mme_fqdn/ d" /etc/hosts

db_id=`relation-ids db`
#could be that the relation is up but the unit has been already gone
if [ -z "$db_id" ]; then
   juju-log "Database relation broken!!!...failed MME removal from db"
   exit 0
else
   db_unit=$(relation-list -r $db_id)
   if [ -z "$db_unit" ]; then
      exit 0
   fi
fi


#No cycle, only one database master.
db_user=`relation-get -r "$db_id" user $db_unit`
db_password=`relation-get -r "$db_id" password $db_unit`
db_host=`relation-get -r "$db_id" host $db_unit`
db_database=`relation-get -r "$db_id" database $db_unit`
#if [ -z "$db_user" ]; then
#
#   exit 0
#fi

if [ -n "$(/usr/bin/mysql -u $db_user --password=$db_password -h $db_host $db_database -e "select mmehost from mmeidentity where mmehost='$mme_fqdn'";)" ]; then

      /usr/bin/mysql -u $db_user --password=$db_password -h $db_host $db_database -e "delete from mmeidentity where mmehost='$mme_fqdn'";
fi
juju-log "MME departure"
status-set active "HSS is running"

#WATCH OUT: HSS can be connected to many MME(EPC) so we don't stop the service.


