#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file upgrade-charm
# brief called when each time a charm is upgraded after the new charm
# contents have been unpacked
# author  navid.nikaein@eurecom.fr 

# Best practice suggests you execute the hooks/install and
# hooks/config-changed to ensure all updates are processed

set -eux
status-set maintenance "Upgrade-charm  hook"
stop_hss 
$CHARM_DIR/hooks/install #Re-run install 

if [ -z "$(relation-ids db)" ]; then
   juju-log "HSS is built, but is waiting for active connection to gather the last info"
   juju-log "no db is found, so HSS process is not going to be run" 
   exit 0
fi

#Fill again the hss.conf file since it has been downloaded a fresh installation...don't want to lose db relation data in the configuration
#No cycle, only one database master.
db_id=`relation-ids db`
db_unit=`relation-list -r $db_id`
db_user=`relation-get -r "$db_id" user $db_unit`
db_password=`relation-get -r "$db_id" password $db_unit`
db_host=`relation-get -r "$db_id" host $db_unit`
db_database=`relation-get -r "$db_id" database $db_unit`
 
db_data_in_config_file $db_host $db_user $db_password $db_database


