openapi: "3.0.0"
info:
  version: 1.0.0
  title: Core Adapter Service
  description: An example for Core Adapter
servers:
  - url: http://localhost:9090/slicenet/ctrlplane/
  
paths:             
  '/coreadapter/v1/coreadapter-instance/{sliceId}/set_qos_on_core':

    put:
      summary: set QOS Constraints on Core Adapter
      description: To set QoS contraints to the corresponding network slice in the Core Network.
      tags:
        - Set QoS Constrants on Core
      operationId: core_api.core_adapter_api.put_QoSOnCore
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to CoreAdapter
          required: true
          schema:
            type: string
        - name: userEqId
          in: query
          required: true
          description: Identify the User Equipment Identity
          schema:
            type: string
        - name: epsBearerId
          in: query
          required: false
          description: Identify EPS Bearer Identity
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:             
                $ref: '#/components/schemas/CoreAdapterConstraints'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          
    post:
      summary: Add QOS Constraints on Core Adapter
      description: To add QoS contraints to the corresponding network slice in Core Network.
      tags:
        - Add QoS Constrants on Core
      operationId: core_api.core_adapter_api.post_QoSOnCore
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to CoreAdapter
          required: true
          schema:
            type: string
        - name: userEqId
          in: query
          required: true
          description: Identify the User Equipment Identity
          schema:
            type: string
        - name: epsBearerId
          in: query
          required: false
          description: Identify EPS Bearer Identity
          schema:
            type: integer
      requestBody:
        required: true
        description: slice to add to the system
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: "#/components/schemas/CoreAdapterConstraints"
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/corAdapterRoutes"
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error


components:
  schemas:
    corAdapterRoutes:
      type: object
      required:
        - userEqId
        - routes
      properties:
        userEqId:
          type: string
        routes:
          type: array
          items:
            $ref: '#/components/schemas/BearerIds'

    BearerIds:
      type: object
      properties:
        bearerIdFrom:
          type: integer
        bearerIdTo:
          type: integer
          
    CoreAdapterConstraints:
        type: object
        properties:
          bandIncDir:
            type: string
            enum:
               - UL
               - DL
               - ul
               - dl
          bandIncVal:
            type: string
          bandUnitScale:
            type: string
            enum:
               - MB
               - KB
               - mb
               - kb
        example:
            bandIncDir: ul
            bandIncVal: "10"
            bandUnitScale: "MB" 
            
