openapi: "3.0.0"
info:
  version: 1.0.0
  title: Core Adapter Service
  description: An example for Core Adapter
servers:
  - url: http://localhost:9090/coreadapter/all/v1
  
paths:             
  '/{sliceId}/set_qos_on_core':

    put:
      summary: set QOS Constraints on Core Adapter
      description: To set QoS contraints to the corresponding network slice in the Core Network.
      tags:
        - Set QoS Constrants on Core
      operationId: core_api.core_adapter_api.put_QoSOnCore
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to CoreAdapter
          required: true
          schema:
            type: string
            format: uuid
        - name: userEqId
          in: query
          required: true
          description: Identify the User Equipment Identity
          schema:
            type: string
        - name: epsBearerId
          in: query
          required: false
          description: Identify EPS Bearer Identity
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:             
                $ref: '#/components/schemas/CoreAdapterConstraints'
              minItems: 1
              maxItems: 2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/coreAdapterRoutes"
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
    post:
      summary: Add QOS Constraints on Core Adapter
      description: To add QoS contraints to the corresponding network slice in Core Network.
      tags:
        - Add QoS Constrants on Core
      operationId: core_api.core_adapter_api.post_QoSOnCore
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to CoreAdapter
          required: true
          schema:
            type: string
            format: uuid
        - name: userEqId
          in: query
          required: true
          description: Identify the User Equipment Identity
          schema:
            type: string
        - name: epsBearerId
          in: query
          required: false
          description: Identify EPS Bearer Identity
          schema:
            type: integer
      requestBody:
        required: true
        description: slice to add to the system
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: "#/components/schemas/CoreAdapterConstraints"
              minItems: 1
              maxItems: 2
      responses:
        '201':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/coreAdapterRoutes"
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  '/{sliceId}/redirect':
    post:
      summary: Redirect traffic flow from for one bearer one server to another
      description: To redirect traffic flow for one bearer identified by IMSI and EPS bearer id from one server to another server
      tags:
        - Redirect Traffic for one Bearer
      operationId: core_api.core_adapter_api.post_redirect_traffic
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to CoreAdapter
          required: true
          schema:
            type: string
            format: uuid
        - name: userEqId
          in: query
          required: true
          description: Identify the User Equipment Identity
          schema:
            type: string
        - name: epsBearerId
          in: query
          required: false
          description: Identify EPS Bearer Identity
          schema:
            type: integer
      requestBody:
        required: true
        description: Addresses of the servers (from/to)
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServerAddresses"
      responses:
        '201':
          description: Traffic redirected
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  '/set_slice_mapping':
        
    post:
      summary: Set the mapping between LL-MEC slice and Slicenet slice
      description: Set the mapping between LL-MEC slice and Slicenet slice.
      tags:
        - Set slice mapping on MEC-Core Adapter
      operationId: core_api.core_adapter_api.post_SliceMapping
      requestBody:
        required: true
        description: the mapping between LL-MEC slice id and slicenet slice id
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/SliceMapping"
                minItems: 1                
      responses:
        '201':
          description: Added
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

    put:
      summary: Modify the mapping between LL-MEC slice and Slicenet slice
      description: Modify the mapping between LL-MEC slice and Slicenet slice.
      tags:
        - Modify slice mapping on MEC-Core Adapter
      operationId: core_api.core_adapter_api.put_SliceMapping
      requestBody:
        required: true
        description: the mapping between LL-MEC slice id and slicenet slice id
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/SliceMapping"
                minItems: 1                
      responses:
        '201':
          description: Added
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
                
  '/remove_slice_mapping/{sliceId}':
    delete:
      summary: Remove the mapping between LL-MEC slice and Slicenet slice
      description: Remove the mapping between LL-MEC slice and Slicenet slice.
      tags:
        - Remove slice mapping on MEC-Core Adapter
      operationId: core_api.core_adapter_api.delete_SliceMapping
      description: Remove the mapping between LL-MEC slice id and slicenet slice id
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to MEC-Core Adapter
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: removed
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
        '404':
          description: Not Found
          
components:
  schemas:
    coreAdapterRoutes:
      type: object
      required:
        - userEqId
        - routes
      properties:
        userEqId:
          type: string
        routes:
          type: array
          items:
            $ref: '#/components/schemas/ServerAddresses'

    ServerAddresses:
      type: object
      properties:
        FromServer:
          type: string
        ToServer:
          type: string
          
    CoreAdapterConstraints:
        type: object
        properties:
          bandIncDir:
            type: string
            enum:
               - UL
               - DL
               - ul
               - dl
          bandIncVal:
            type: string
          bandUnitScale:
            type: string
            enum:
               - MB
               - KB
               - mb
               - kb
        example:
            bandIncDir: ul
            bandIncVal: "10"
            bandUnitScale: "MB" 
            
    SliceMapping:
        type: object
        properties:
          slicenetid:
            type: string
            format: uuid
          sid:
            type: string
            format: uuid          
        example:
            slicenetid: "f5b01594-520e-11e9-8647-d663bd873d93"
            sid: "1"  
