openapi: "3.0.0"
info:
  version: 1.0.0
  title: RAN Adapter Service
  description: An example for RAN Adapter
servers:
  - url: http://localhost:9090/ranadapter/all/v1
  
paths:             
  '/{sliceId}/set_qos_on_ran':

    put:
      summary: set QOS Constraints on RAN Adapter
      description: To set QoS contraints to the corresponding network slice in the access network.
      tags:
        - Set QoS Constrants on RAN
      operationId: ran_api.ran_adapter_api.put_QoSOnRAN
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to RanAdapter
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
               type: array
               items:            
                  $ref: '#/components/schemas/RanAdapterConstraints'
               minItems: 1
               maxItems: 2
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
    post:
      summary: Add QOS Constraints on RAN Adapter
      description: To add QoS contraints to the corresponding network slice in the access network.
      tags:
        - Add QoS Constrants on RAN
      operationId: ran_api.ran_adapter_api.post_QoSOnRAN
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to RanAdapter
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        description: slice to add to the system
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/RanAdapterConstraints"
                minItems: 1
                maxItems: 2
      responses:
        '201':
          description: Added
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  '/set_slice_mapping':
        
    post:
      summary: Set the mapping between FlexRAN slice and Slicenet slice
      description: Set the mapping between FlexRAN slice and Slicenet slice.
      tags:
        - Set slice mapping on RAN Adapter
      operationId: ran_api.ran_adapter_api.post_SliceMapping
      requestBody:
        required: true
        description: the mapping between FlexRAN slice id and slicenet slice id
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/SliceMapping"
                minItems: 1                
      responses:
        '201':
          description: Added
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

    put:
      summary: Modify the mapping between FlexRAN slice and Slicenet slice
      description: Modify the mapping between FlexRAN slice and Slicenet slice.
      tags:
        - Modify slice mapping on RAN Adapter
      operationId: ran_api.ran_adapter_api.put_SliceMapping
      requestBody:
        required: true
        description: the mapping between FlexRAN slice id and slicenet slice id
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/SliceMapping"
                minItems: 1                
      responses:
        '201':
          description: Added
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
                
  '/remove_slice_mapping/{sliceId}':
    delete:
      summary: Remove the mapping between FlexRAN slice and Slicenet slice
      description: Remove the mapping between FlexRAN slice and Slicenet slice.
      tags:
        - Remove slice mapping on RAN Adapter
      operationId: ran_api.ran_adapter_api.delete_SliceMapping
      description: Remove the mapping between FlexRAN slice id and slicenet slice id
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to RanAdapter
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: removed
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
        '404':
          description: Not Found

  '/trigger_ho/{sliceId}':

    put:
      summary: Triggers a network-initiated handover request
      description: Triggers a network-initiated handover request to perform the handover of the given UE from a source BS to the target BS.
      tags:
        - Trigger Handover
      operationId: ran_api.ran_adapter_api.put_trigger_ho
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to RanAdapter
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hoParameters'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
    post:
      summary: Triggers a network-initiated handover request
      description: Triggers a network-initiated handover request to perform the handover of the given UE from a source BS to the target BS.
      tags:
        - Trigger Handover
      operationId: ran_api.ran_adapter_api.post_trigger_ho
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to RanAdapter
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        description: slice to add to the system
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hoParameters'
      responses:
        '201':
          description: Added
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error        
          

  '/{sliceId}/set_slice_priority':
   
    post:
      summary: Set slice priority
      description: To set slice priority to the corresponding network slice in the access network.
      tags:
        - Set Slice Priority on RAN
      operationId: ran_api.ran_adapter_api.post_SetSlicePriority
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to RanAdapter
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        description: slice priority
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SlicePriority'
      responses:
        '201':
          description: Added
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
    put:
      summary: Set slice priority
      description: To set slice priority to the corresponding network slice in the access network.
      tags:
        - Set Slice Priority on RAN
      operationId: ran_api.ran_adapter_api.put_SetSlicePriority
      parameters:
        - name: sliceId
          in: path
          description: ID of the slice associated to RanAdapter
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        description: slice priority
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SlicePriority'
      responses:
        '201':
          description: Added
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error       
                   
components:
  schemas:
    RanAdapterConstraints:
        type: object
        properties:
          bandIncDir:
            type: string
            enum:
               - UL
               - DL
               - ul
               - dl
          bandIncVal:
            type: string
          bandUnitScale:
            type: string
            enum:
               - MB
               - KB
               - mb
               - kb
        example:
            bandIncDir: ul
            bandIncVal: "10"
            bandUnitScale: "MB" 

    SliceMapping:
        type: object
        properties:
          slicenetid:
            type: string
            format: uuid
          sid:
            type: string
            format: uuid          
        example:
            slicenetid: "f5b01594-520e-11e9-8647-d663bd873d93"
            sid: "1"                
    hoParameters:
        type: object
        properties:
          sid:
            type: integer
          ueid:
            type: string 
          tid:
            type: integer           
        example:
            sid: 1234567
            ueid: "208950000000003"
            tid: 9876543  
            
    SlicePriority:
        type: object
        properties:
          ul:
            type: integer
          dl:
            type: integer
        description: >
          Provide the priority of the slice for Uplink and Downlink. Higher priority means preferential scheduling. size range: 0-20  
        example:
            ul: 10
            dl: 1
        
