#!/bin/sh
export DEBIAN_FRONTEND=noninteractive
set -e

CONF_DIR="$SNAP_DATA"

UE_DIR="$SNAP/ue"
UE_EXEC="$UE_DIR/oai-ue"
USIM_EXEC="$UE_DIR/usim"
USIM_MULTI_EXEC="$UE_DIR/conf2uedata"
NVRAM_EXEC="$UE_DIR/nvram"

UE_CONF_FILE="$CONF_DIR/ue.conf"
UE_CMD_FILE="$CONF_DIR/ue.band7.25PRB.usrp210.cmd"
UESIM_CONF_FILE="$CONF_DIR/uesim.conf"
UESIM_CMD_FILE="$CONF_DIR/uesim.25PRB.cmd"
UESIM_L2SIM_CONF_FILE="$CONF_DIR/uesim.nfapi.conf"
UESIM_L2SIM_CMD_FILE="$CONF_DIR/uesim.50PRB.nfapi.cmd"

UE_USIM_CONF_FILE="$CONF_DIR/usim_default.conf"

UESIM_DIR="$SNAP/ue"
UESIM_CONF_FILE="$CONF_DIR/uesim.conf"
UESIM_EXEC="$UE_DIR/oai-ue"


UE_IP_DIR="$CONF_DIR/ue_ip"

MAKE_DIR="$SNAP"
MAKE_EXEC="$MAKE_DIR/make"
