#!/bin/sh

. $SNAP/common

#if [ ! -f $CONF_DIR/uesim.50PRB.conf ] ; then
    cp $SNAP/etc/* $CONF_DIR
    cp $SNAP/etc/.ue_emm.nvram0 $CONF_DIR
    cp $SNAP/etc/.ue.nvram0 $CONF_DIR
    cp $SNAP/etc/.usim.nvram0 $CONF_DIR
    
#fi

#if [ ! -f $UE_IP_CONF/makefile ]  ; then
    cp -r $SNAP/ue_ip $CONF_DIR        
    cp -r $SNAP/ue_ip $SNAP_USER_DATA        
#fi

# set the UE conf
$SNAP/conf set-ue $CONF_DIR/UE_config.xml
$SNAP/conf set-ue-cmd $CONF_DIR/ue.band7.25PRB.usrp210.cmd

#set the UE SIM  conf
$SNAP/conf set-uesim $CONF_DIR/uesim.conf
$SNAP/conf set-uesim-cmd $CONF_DIR/uesim.25PRB.cmd

#set the USIM conf
$SNAP/conf set-usim $CONF_DIR/usim_default.conf


# a copy for the user
cp $CONF_DIR/ue.band7.25PRB.usrp210.cmd $SNAP_USER_DATA
cp $CONF_DIR/UE_config.xml               $SNAP_USER_DATA
cp $CONF_DIR/usim_default.conf         $SNAP_USER_DATA
cp $CONF_DIR/uesim.25PRB.cmd          $SNAP_USER_DATA
cp $CONF_DIR/uesim.conf         $SNAP_USER_DATA


#$SNAP/run oip

echo "OAI-UE init: done"



