#!/bin/sh

. $SNAP/common

echo "Test Snap Service $1"

waiting_time1=1
waiting_time2=2

case "$1" in
    "ue" |  "all" )
	
	$SNAP/run status
	sleep $waiting_time1 
	$SNAP/run start
	sleep $waiting_time1
	$SNAP/run status
	sleep $waiting_time1
	$SNAP/run stop
	sleep $waiting_time1
	$SNAP/run status
	sleep $waiting_time1

	echo "get usim info"
	$SNAP/run  usim-print
	sleep $waiting_time2 
	echo "get nvram info"
	$SNAP/run  nvram-print
	sleep $waiting_time2
	echo "get UE config"
	$SNAP/conf echo
	sleep $waiting_time2
	echo "get UE command"
	$SNAP/conf echo-cmd
	sleep $waiting_time2
	echo "get usim configuration file"
	$SNAP/conf echo-usim
	sleep $waiting_time2
	
	

	;;
	
    * )
	echo "Unknown command: $1"
	;;

esac

	

