#!/bin/sh

. $SNAP/common

echo "Test Snap Service $1"

waiting_time1=1
waiting_time2=2

case "$1" in
     "all" )
	
	$SNAP/run status  ued
	sleep $waiting_time1 
	$SNAP/run start ued 
	sleep $waiting_time1
	$SNAP/run status ued
	sleep $waiting_time1
	$SNAP/run stop ued
	sleep $waiting_time1
	$SNAP/run status ued 
	sleep $waiting_time1

	sleep $waiting_time1
	$SNAP/run start uesimd
	sleep $waiting_time1
	$SNAP/run status uesimd
	sleep $waiting_time1
	$SNAP/run stop uesimd
	sleep $waiting_time1
	$SNAP/run status uesimd
		
	echo "1. get usim info"
	$SNAP/run  usim-print
	sleep $waiting_time2 
	echo "2. get nvram info"
	$SNAP/run  nvram-print
	sleep $waiting_time2
	echo "3. get UE config"
	$SNAP/conf echo-ue
	sleep $waiting_time2
	echo "4. get UE command"
	$SNAP/conf echo-ue-cmd
	sleep $waiting_time2
	echo "5. get usim configuration file"
	$SNAP/conf echo-usim

	
	;;
	"ue" | "uesim" )
		   
	;;
	
    * )
	echo "Unknown command: $1"
	;;

esac

	

