#!/bin/sh
set -e 
echo "OAI-CN install hook"
pwd

exit 0 

run import-db
run hss-certificate
run mme-certificate

echo "OAI-CN configure hook"
conf set-mme etc/mme.conf
cp $SNAP/mme/mme_fd.conf $SNAP_USER_DATA

conf set-spgw etc/spgw.conf

conf set-hss $frontend/etc/hss.conf
cp $SNAP/hss/hss_fd.conf $SNAP_USER_DATA
cp $SNAP/hss/acl.conf $SNAP_USER_DATA
