ccflags-y += -O2 

ccflags-y += -DRHEL_RELEASE_CODE=0 -DRRC_VERSION=3696 -DNAS_NETLINK -DPDCP_USE_NETLINK -DOAI_NW_DRIVER_USE_NETLINK   

obj-m += ue_ip.o
oip-objs += device.o
oip-objs += common.o
oip-objs += netlink.o

all:
		make -C /lib/modules/$k/build  M=$(PWD) modules