#!/bin/bash
#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */

################################################################################
# file oip
# brief loads the ue_ip module and sets up IP for the UE
# you may want to edit it to fit your settings (replace oip0 by oipX for
# instance)
# author Florian Kaltenberger and Navid Nikaein
#
#######################################

LTEIF=oip1

remove_module() {
  mod_name=${1##*/}
  mod_name=${mod_name%.*}
  if awk "/$mod_name/ {found=1 ;exit} END {if (found!=1) exit 1}" /proc/modules
    then
      echo "module $mod_name already loaded: I remove it first"
      sudo rmmod $mod_name
  fi
  #echo loading $mod_name
  #sudo insmod $1
}

#remove_module $2 || true 
rmmod ue_ip 2>&1 || true 

case "$1" in
    
    "add" )
	shift
	insmod $1 > insmod.log  2>&1
	if [ $? -eq 0 ]; then
	    rm -f /var/snap/oai-ue/current/ue_ip/ue_ip_$(uname -r | cut -d '.' -f1,2)*
	    cp $1 /var/snap/oai-ue/current/ue_ip/ue_ip_$(uname -r | cut -d '-' -f1,2).ko
	    cp $1 /lib/modules/$(uname -r)
	    depmod -a
	    echo "modinfo ue_ip: "
	    modinfo ue_ip 
	    
	    echo "bring up $LTEIF interface for UE"
	    ifconfig $LTEIF up
	    
	    ip route flush cache
	    sleep 1
	    sysctl -w net.ipv4.conf.all.log_martians=1
	    echo "Disabling reverse path filtering"
	    sysctl -w net.ipv4.conf.all.rp_filter=0
	    ip route flush cache
	    
	    # Check table 200 lte in /etc/iproute2/rt_tables
	    fgrep lte /etc/iproute2/rt_tables  > /dev/null 
	    if [ $? -ne 0 ]; then
		echo "200 lte " >> /etc/iproute2/rt_tables
	    fi
	    ip rule add fwmark 1 table lte
	    ip route add default dev $LTEIF table lte
	else
	    echo "Failed to insert the module $1 with err code $?"
	fi
	
	;;
    *)
	echo "not supported operation"
esac
	  
