#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file install hook
# brief install the ll-mec
# author  navid.nikaein@eurecom.fr

install_packages(){

    gitAlreadyInstalled=$(dpkg --get-selections snapd 2>/dev/null | grep -c 'install') || true
    if [ ! $gitAlreadyInstalled -eq 1 ]; then # If git is NOT installed
	apt-get install -y --force-yes snapd # Ensure necessary git dependency exist.
    fi

    gitAlreadyInstalled=$(dpkg --get-selections jq 2>/dev/null | grep -c 'install') || true
    if [ ! $gitAlreadyInstalled -eq 1 ]; then # If git is NOT installed
	apt-get install -y --force-yes jq # Ensure necessary git dependency exist.
    fi
    gitAlreadyInstalled=$(dpkg --get-selections git 2>/dev/null | grep -c 'install') || true
    if [ ! $gitAlreadyInstalled -eq 1 ]; then # If git is NOT installed
	apt-get install -y --force-yes git # Ensure necessary git dependency exist.
    fi
    atAlreadyInstalled=$(dpkg --get-selections at 2>/dev/null | grep -c 'install') || true
    if [ ! $atAlreadyInstalled -eq 1 ]; then 
	# If at command is NOT installed
	apt-get install -y --force-yes at
	# Ensure at command exists to let juju reschedule this hook after rebooting the machine.
    fi
    virtwhatAlreadyInstalled=$(dpkg --get-selections virt-what 2>/dev/null | grep -c 'install') || true
    if [ ! $virtwhatAlreadyInstalled -eq 1 ]; then 
	apt-get install -y --force-yes virt-what
    fi
}

clone_repro(){
    juju-log  "Fetching the Mosaic5G repository"
    
    echo -n | openssl s_client -showcerts -connect gitlab.eurecom.fr:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt

    #everytime refresh the installation 
    if [ -d "$mosaic_path" ]; then  
	cd $mosaic_path
	git reset --hard HEAD
	cd - 
    else
	git clone https://gitlab.eurecom.fr/mosaic5g/mosaic5g.git $mosaic_path
    fi
}

build_llmec(){
    cd $mosaic_path
    if [ "$snap" != "edge" ] || [ "snap" != "beta" ] ; then
	juju-log "channel $snap is not supported, use edge"
    else
	juju-log "Installing and building the LL-MEC from snap"
    fi
    ./build_m5g -L
}

init_llmec(){
    ll-mec.stop || true
    ll-mec.stop || true
    ll-mec.init || true 
    # just a flag for start script to run the service
    echo "yes" > $CHARM_DIR/.llmec_running_flag
}

status-set maintenance "Install hook"

set -eux
export DEBIAN_FRONTEND=noninteractive
source $CHARM_DIR/utils/common
set_env
echo "no"  > $CHARM_DIR/.llmec_running_flag

snap=`config-get snap`
bind_addr=`config-get bind_addr`
bind_port=`config-get bind_sbi_port`
rest_port=`config-get bind_nbi_port`
gw_mac_addr=`config-get gw_mac_addr`

open-port $bind_port/tcp
open-port $rest_port/tcp

echo "$snap"           >  $CHARM_DIR/.snap
echo ""      >  $CHARM_DIR/.bind_addr
echo ""      >  $CHARM_DIR/.bind_port
echo ""      >  $CHARM_DIR/.rest_port
echo ""      >  $CHARM_DIR/.gw_mac_addr


install_packages
machine_type=`virt-what`

clone_repro

build_llmec

init_llmec
