#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file start 
# brief start llmec service, this happens after install or config changed hooks
# author  navid.nikaein@eurecom.fr

set -eux

source $CHARM_DIR/utils/common
set_env

if [ -f $CHARM_DIR/.llmec_running_flag ]; then
    llmec_running_flag=`cat $CHARM_DIR/.llmec_running_flag`
else
    llmec_running_flag="no"
fi

if [ "$llmec_running_flag" == "yes" ] ; then 
    ll-mec.start || true 
    
    check_llmec_process || true 
    if [ $status -eq 1 ]; then
	status-set blocked "Not Running, check the config file"
	echo "no"  > $CHARM_DIR/.llmec_running
	exit 1	
    else
	echo "yes" > $CHARM_DIR/.llmec_running
	status-set active "Running"
    fi 
fi 
