#!/bin/sh

. $SNAP/common

case "$1" in
    "set-mme" )
	CONFIG_FILE=$2	
	if [ "$CONFIG_FILE" != "${CONFIG_FILE#/}" -a -f "$CONFIG_FILE" ]; then
	    echo "Setting the default config file to: $CONFIG_FILE"
	    
	elif [ -f "$CONF_DIR/$CONFIG_FILE" ]; then
	    CONFIG_FILE=$CONF_DIR/$CONFIG_FILE
	    echo "Config file found in the $CONF_DIR!"
	    echo "Resetting to the default config file: $CONFIG_FILE"
	    
	else
	    echo "[ERR] Config file $CONFIG_FILE not found, please provide an absolute path!"
	    echo "Reset to default config file: $MME_CONF_FILE"
	    CONFIG_FILE=$MME_CONF_FILE
	fi

	echo "MME_CONF_FILE2=$CONFIG_FILE" > $SNAP_DATA/config_mme.sh
	echo "MME_CONF_FILE2=$CONFIG_FILE" > $SNAP_USER_DATA/config_mme.sh
	;;

    
     "ls-mme" )
	if [ -r $SNAP_DATA/config_mme.sh ]; then
	    . $SNAP_DATA/config_mme.sh
	fi
	
	# default config file is (unless set in above config)
	MME_CONFIG=${MME_CONF_FILE2:-$MME_CONF_FILE}
	ls $(dirname $MME_CONFIG)/*
	;;

     "echo-mme" | "cat-mme" )
	
	if [ -r $SNAP_DATA/config_mme.sh ]; then
	    . $SNAP_DATA/config_mme.sh
	fi
	
	# default config file is (unless set in above config)
	MME_CONFIG=${MME_CONF_FILE2:-$MME_CONF_FILE}
	# echo (get), cat (show)
        `echo $1 | cut -d"-" -f1` $MME_CONFIG
	;;
      *)
       echo "unknown command $1"
       ;;
esac
    

