#! /bin/bash
################################################################################
# Licensed to the Mosaic5G under one or more contributor license
# work for additional information regarding copyright ownership.
# Apache License, Version 2.0  (the "License");
# You may obtain a copy of the License at
#  
#    	http://www.apache.org/licenses/LICENSE-2.0
#  
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# -------------------------------------------------------------------------------
#   For more information about the Mosaic5G:
#   	contact@mosaic-5g.io
#
#
################################################################################
# file conf
# brief conf scripts and variables for oai-mme Snap
# author Navid Nikaein (navid.nikaein@eurecom.fr, navid.nikaein@mosaic-5g.io)


. $SNAP/common
. $SNAP/util

case "$1" in
    "set-mme" )
	CONFIG_FILE=$2	
	if [ "$CONFIG_FILE" != "${CONFIG_FILE#/}" -a -f "$CONFIG_FILE" ]; then
	    echo_success "Setting the default config file to: $CONFIG_FILE"
	    
	elif [ -f "$CONF_DIR/$CONFIG_FILE" ]; then
	    CONFIG_FILE=$CONF_DIR/$CONFIG_FILE
	    echo_info "Config file found in the $CONF_DIR!"
	    echo_info "Resetting to the default config file: $CONFIG_FILE"
	    
	else
	    echo_error "[ERR] Config file $CONFIG_FILE not found, please provide an absolute path!"
	    echo_info "Reset to default config file: $MME_CONF_FILE"
	    CONFIG_FILE=$MME_CONF_FILE
	fi
	snapctl set conf.mme=$CONFIG_FILE
	echo "MME_CONF_FILE2=$CONFIG_FILE" > $SNAP_DATA/config_mme.sh
	echo "MME_CONF_FILE2=$CONFIG_FILE" > $SNAP_USER_DATA/config_mme.sh
	;;

    
     "ls-mme" )
	if [ -r $SNAP_DATA/config_mme.sh ]; then
	    . $SNAP_DATA/config_mme.sh
	fi
	
	# default config file is (unless set in above config)
	MME_CONFIG=${MME_CONF_FILE2:-$MME_CONF_FILE}
	ls $(dirname $MME_CONFIG)/*mme*.conf
	;;

     "echo-mme" | "cat-mme" )
	show_file=$2
	
	
	if [ -r $SNAP_DATA/config_mme.sh ]; then
	    . $SNAP_DATA/config_mme.sh
	fi
	
	# default config file is (unless set in above config)
	MME_CONFIG=${MME_CONF_FILE2:-$MME_CONF_FILE}
	# echo (get), cat (show)
        # `echo $1 | cut -d"-" -f1` $MME_CONFIG
	
	if [ "$show_file" != "" ]; then
		# echo "File to show $SNAP_DATA/$show_file"
		absolute_show_file=$SNAP_DATA/$show_file
		if [ ! -e $absolute_show_file ]; then
			echo "The file $absolute_show_file does not exist"
		else
			`echo $1 | cut -d"-" -f1` $absolute_show_file
		fi
	else
		# echo "File to show $MME_CONFIG"
		`echo $1 | cut -d"-" -f1` $MME_CONFIG
	fi

	;;
      *)
       echo "unknown command $1"
       ;;
esac
    
