#! /bin/bash
################################################################################
# Licensed to the Mosaic5G under one or more contributor license
# work for additional information regarding copyright ownership.
# Apache License, Version 2.0  (the "License");
# You may obtain a copy of the License at
#  
#    	http://www.apache.org/licenses/LICENSE-2.0
#  
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# -------------------------------------------------------------------------------
#   For more information about the Mosaic5G:
#   	contact@mosaic-5g.io
#
#
################################################################################
# file init
# brief init scripts and variables for oai-mme Snap
# author Navid Nikaein (navid.nikaein@eurecom.fr, navid.nikaein@mosaic-5g.io)


. $SNAP/common
. $SNAP/util

if_sudo

apiport=$(grep -m1 "api_port_default" $SNAP/apivars.py | cut -f3 -d " ")
mgrport=$(grep -m1 "api_manager_port_default" $SNAP/apivars.py | cut -f3 -d " ")
apiaddr=$(grep -m1 "api_host_default" $SNAP/apivars.py | cut -f3 -d " " | cut -f3 -d " " | tr -d "'")
mgraddr=$(grep -m1 "api_manager_host_default" $SNAP/apivars.py | cut -f3 -d " " | cut -f3 -d " " | tr -d "'")

if [ ! -z "$apiport" ] ; then 
    snapctl set conf.apiport=$apiport
    echo_info "Default API port :"  $(snapctl get conf.apiport)
else
    echo_error "Could not read api_port_default in apivars.py!"
fi

if [ ! -z "$mgrport" ] ; then 
    snapctl set conf.mgrport=$mgrport
    echo_info "Default MGR port :"  $(snapctl get conf.mgrport)
else
    echo_error "Could not read  api_manager_port_default in apivars.py!"
fi

if [ ! -z "$apiaddr" ] ; then 
    snapctl set conf.apiaddr=$apiaddr
    echo_info "Default API addr :"  $(snapctl get conf.apiaddr)
else
    echo_error "Could not read api_host_default in apivars.py!"
fi

if [ ! -z "$mgraddr" ] ; then 
    snapctl set conf.mgraddr=$mgraddr
    echo_info "Default MGR addr :"  $(snapctl get conf.mgraddr)
else
    echo_error "Could not read api_manager_host_default in apivars.py!"
fi

openapi="http://"$(snapctl get conf.apiaddr)":"$(snapctl get conf.apiport)
snapctl set conf.openapi=$openapi


#if [ ! -f $CONF_DIR/mme.conf ] ; then
cp $SNAP/etc/* $CONF_DIR
#fi
mme_set_vars
mme_print_vars

snapctl set conf.mme=$CONF_DIR/mme.conf
snapctl set conf.mmefd=$CONF_DIR/mme_fd.conf
$SNAP/conf set-mme $(snapctl get conf.mme) # $CONF_DIR/enb.band7.tm1.50PRB.usrpb210.conf
echo_info "Default MME conf:" $SNAP/conf echo-mme 


sed -i -e "s/hss/$HOSTNAME/g" $CONF_DIR/mme.conf 
sed -i -e "s/ubuntu/$HOSTNAME/g" $CONF_DIR/mme_fd.conf 

# a copy for the user
cp $CONF_DIR/mme.conf $SNAP_USER_DATA
cp $CONF_DIR/mme_fd.conf $SNAP_USER_DATA

snapctl set conf.realm="$REALM"
snapctl set conf.host="$HOSTNAME"

case "$1" in

    "mme" )
	
	$SNAP/run mme-certificate
	echo_info "MME certificate is generated"
	echo ""

	snap_isconnected network-control
	if [ -z "$(grep -o "$HOSTNAME.$REALM" /etc/hosts)" ]; then
	    
	    echo "Adding 127.0.0.1" $HOSTNAME.$REALM $HOSTNAME "mme to /etc/hosts"
	    sed -i '/mme/d' /etc/hosts
	    sed -i "1i127.0.0.1 $HOSTNAME.$REALM $HOSTNAME mme" /etc/hosts
	    
	fi

    	echo ""
	echo_success "MME is initialized"
	;;
    
    * )
	echo "MME init is not completed, run oai-mme.init"
	;;
    
esac

echo ""
echo "$SNAP_NAME snap info:"
snap_info 
