options:
   snap:
     default: "edge"
     description: |
      snap indicates which channel to use for installation hook. 
     type: string
   sgw-eth:
     default: "eth0"
     description: |
       This is usefull especially when you are in manual environment so you have your own machines. The default value is eth0. NO empty value.
     type: string
   pgw-eth:
     default: "eth0"
     description: |
       This is usefull especially when you are in manual environment so you have your own machines. The default value is eth0. NO empty value.
     type: string
   ipv4_list_start:
     default: "172.16.0.0/12"
     description: First IP address pool that will be assigned to UEs.
     type: string
   ipv4_list_end:
     default: "172.16.0.0/12"
     description: Second IPv4 address pool that will be assigned to UEs.
     type: string
   ipv6_list:
     default: "2014:02:26::0/120"
     description: First IPv6 addresse pool available to be assigned to UEs.
     type: string
   pgw_masquerade_sgi:
     default: "yes"
     description: enable P-GW masquerading for SGI interface
     type: string
   ue_mtu:
     default: 1428
     description: set the LTE UE MTU
     type: int
   DEFAULT_DNS_IPV4_ADDRESS:
     default: "8.8.8.8"
     description: IPv4 address of primary default DNS that can be queried by UEs.
     type: string
   DEFAULT_DNS_SEC_IPV4_ADDRESS:
     default: "8.8.8.8"
     description: IPv4 address of secondary default DNS that can be queried by UEs.
     type: string






