options:
   branch:
     default: "v0.1"
     description: |
       branch indicates which installation you want to do. 
     type: string
   revision: 
     default: "HEAD"   
     description: get a specific revison from the openairinterface5G git repository. 
     type: string
   kernel: 
     default: "generic"   
     description: set the default kerenl, generic or lowlatency. 
     type: string
   target_hardware:
     default: "usrp"
     description: |
       defines the target RF hardware. Available Options, usrp, bladerf, and sodera. Setting this option will require different configuration file and wil trigger different building process. 
     type: string
   config_file:
     default: "default"
     description: |
       takes the default configuration file based on the target hardware. It defines the specific RF configuration file. 
     type: string
   fronthaul_if:
     default: "eth0"
     description: |
       defines the fronthaul interface name. This is usefull especially when you are in manual environment so you have your own machines. The default value is the eth0. NO empty value.
     type: string
   fronthaul_port:
     default: 50000
     description: |
       defines the fronthaul port number for the RRH. 
     type: int
#   transport_mode:
#     default: "raw"
#     description: |
#        defines the I/Q sample transport mode. Available mode are udp and raw.
#     type: string
   verbosity:
     default: "none"
     description: sets the log level verbosity. Valid values are "none", "info", or "debug"
     type: string
   loopback: 
     default: "no"
     description: sets the rrh to operate on loopback mode
     type: string

