#!/bin/sh

export DEBIAN_FRONTEND=noninteractive
set -e


CONF_DIR="$SNAP_DATA"

OVS_DIR="$SNAP"
OVS_CONF_FILE="$CONF_DIR/ovs.conf"
# ovs-vsctl, ovsdb-server, ovs-vswitchd
OVS_EXEC="$OVS_DIR/$SNAP_NAME"

OVS_ETC="$CONF_DIR/etc/openvswitch"
OVS_RUN="$CONF_DIR/var/run/openvswitch"

export PATH="$SNAP/usr/local/sbin:$SNAP/usr/local/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/usr/local/lib"


os=$(grep "^ID=" /etc/os-release | sed "s/ID=//" | sed "s/\"//g")
os_release=$(grep "^VERSION_ID=" /etc/os-release | sed "s/VERSION_ID=//" | sed "s/\"//g")
os_dist=$os$os_release
