#!/bin/sh

. $SNAP/common

case "$1" in
    "set" )
	CONFIG_FILE=$2
	if [ -f $(dirname $(readlink -f $0))/$CONFIG_FILE ]; then
	    CONFIG_FILE=$(dirname $(readlink -f $0))/$CONFIG_FILE
	    echo "Setting the default config file to: $CONFIG_FILE"
	else
	    # may be absolute path 
	    if [ -f "$CONFIG_FILE" ]; then
		if [ -f $SNAP_DATA/$CONFIG_FILE ] ; then 
		    echo "Reset the config file to: $SNAP_DATA/$CONFIG_FILE"
		else
		    cp $CONFIG_FILE $SNAP_DATA/
		    CONFIG_FILE=$SNAP_DATA/$(basename $CONFIG_FILE)
		    echo "Adding and setting a new config file : $CONFIG_FILE"
		fi
	    else
		echo "Config file <$CONFIG_FILE> not found in $SNAP/current directory"
		echo "Reset to default config file: $OVS_CONF_FILE"
		CONFIG_FILE=$OVS_CONF_FILE
	    fi
	fi
	echo "OVS_CONF_FILE2=$CONFIG_FILE" > $CONF_DIR/config.sh
	echo "OVS_CONF_FILE2=$CONFIG_FILE" > $SNAP_USER_DATA/config.sh
	;;
    
    *)
	if [ -r $SNAP_DATA/config.sh ]; then
	    . $SNAP_DATA/config.sh
	fi
	
	# default config file is ovs.conf (unless set in above config)
	OVS_CONFIG=${OVS_CONF_FILE2:-$OVS_CONF_FILE}
	# echo (get), cat (show)
	$1 $OVS_CONFIG
	;;
esac
    

