#!/bin/sh

. $SNAP/common

#if [ ! -e $OVS_EXEC  ]; then
#    echo "Command $OVS_EXEC not found"
#    exit 127
#fi		   	   

if [ -r $CONF_DIR/config.sh ]; then
    . $CONF_DIR/config.sh
fi

# default config file is llmec_config.json (unless set in above config)
OVS_CONFIG=${OVS_CONF_FILE2:-$OVS_CONF_FILE}
# To let the service start automatically
# if ll-mec config file is not initialized, get the default 
if [ -e "$OVS_CONFIG" ] ; then
   . $OVS_CONFIG
else
    #$SNAP/init
    . $SNAP/etc/ovs.conf
    cp $SNAP/etc/ovs.conf $SNAP_USER_DATA
fi

case "$1" in
   
    "help" )
	echo "Usage:            sudo $SNAP_NAME or $SNAP_NAME.[options]"
	echo "Note:             root priviliage required"
	echo "Options:"
	echo "  ovs-gtp:        run $SNAP_NAME as a process"
	echo "  init:           initialize $SNAP_NAME (after the 1st installation)"
	echo "  clean:          remove the bridge from $SNAP_NAME"
	echo "  set-conf:       set the $SNAP_NAME configuration file"
	echo "  get-conf:       get the current $SNAP_NAME configuration file"
	echo "  show-conf:      show the path to the $SNAP_NAME configuration file"		
	echo "  help:           print this help"
	;;

    "clean" )
	echo "ovs-vsctl del-br edge"
	ovs-vsctl del-br edge
	sleep 1
	ifconfig $EXT_INTERFACE 0
	;;
    *)
      
      echo "ovs-vsctl add-br edge -- set bridge edge protocols=$OF_VERSION"
      ovs-vsctl add-br edge -- set bridge edge protocols=$OF_VERSION # -- set bridge edge other-config:datapath-id=0000000000000004
      sleep 1
      echo "ovs-vsctl add-port edge $EXT_INTERFACE"
      ovs-vsctl add-port edge $EXT_INTERFACE
      sleep 1
      echo "ovs-vsctl add-port edge s1u -- set Interface s1u type=gtp options:remote_ip=flow -- set Interface s1u type=gtp options:key=flow"
      ovs-vsctl add-port edge s1u -- set Interface s1u type=gtp options:remote_ip=flow -- set Interface s1u type=gtp options:key=flow
      
      ifconfig edge up
      sleep 1
      ifconfig $EXT_INTERFACE 0
      sleep 1
      ifconfig edge $EXT_IP
      
      echo "ovs-vsctl set-controller edge tcp:$CTRL_IP:$CTRL_PORT"
      ovs-vsctl set-controller edge tcp:$CTRL_IP:$CTRL_PORT
      
      ;;
esac
