#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file spgw-relation-joined 
# brief called when the spgw-mme relation is joined
# author navid.nikaein@eurecom.fr and A. B. Molini  

set -eux
source $CHARM_DIR/utils/common

status-set maintenance "spgw-relation-joined hook"

if [ -f $CHARM_DIR/.spgw_running ]; then
  spgw_running=`cat $CHARM_DIR/.spgw_running`
else
  spgw_running="no"
fi


sgw_iface=`config-get sgw-eth`
if [ "$sgw_iface" == "none" ] ; then
    ip_addr=`unit-get public-address`
    for interface in $(ls /sys/class/net); do
        if [ `ifconfig $interface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"` != "" ]; then      
          sgw_ipv4=`ifconfig $interface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`
          if [ $sgw_ipv4 == $ip_addr ] ; then
              sgw_iface=$interface
              
              break
          fi
        fi
    done
else
  sgw_ipv4=`get_eth_ip $sgw_iface`
fi

juju-log "Setting up SPGW relation info for MME"

relation-set  spgw_hostname=`hostname --fqdn`
relation-set SPGW_RUNNING=$spgw_running
relation-set spgw_s11_ipv4=$sgw_ipv4

