#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file start 
# brief start the oai-spgw service, this happens after install or config changed hooks
# author navid.nikaein@eurecom.fr and  A. B. Molini

set -eux
source $CHARM_DIR/utils/common
set_env

 
start_spgw
sleep 2 
check_spgw_process || true
if [ $status -eq 1 ]; then
    status-set blocked "Not Running, check the config file and logs"
    juju-log "Troubles in running SPGW...try to upgrade the charm"
    echo "no"  > $CHARM_DIR/.spgw_running
    exit 1
else
    echo "yes" > $CHARM_DIR/.spgw_running
    status-set active "Running"
fi

