#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file config-change
# brief manage the config changes of oai-enb service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr and A. B. Molini 

set -eux
source $CHARM_DIR/utils/common
set_env_paths

systemctl stop oai_hss || true


if [ "$(config-get branch)" != "$(cat $CHARM_DIR/.branch)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get realm)" != "$(cat $CHARM_DIR/.realm)" ]; then
    realm=`config-get realm` 
 
    sed -i "s/`hostname --fqdn`/`hostname`.$realm/" /etc/hosts
    #if [ -d /usr/lib/freeDiameter ]; then
    #    FREEDIAMETER_PREFIX=/usr
    #elif [ -d /usr/local/lib/freeDiameter ]; then
    #    FREEDIAMETER_PREFIX=/usr/local
    #fi
    if [ -d $freediameter_conf_path ]; then
	rm $freediameter_conf_path/hss.*.pem 
    fi 
    
    fqdn=`hostname --fqdn`
    $build_run_scripts/check_hss_s6a_certificate $freediameter_conf_path $fqdn

    #sed the new identity in acl.conf and hss_fd.conf
    sed -r -i  "s/(Identity[ ]*=[ ]*)\".*\"/\1\"$fqdn\"/" $freediameter_conf_path/hss_fd.conf
    sed -r -i  "s/(Realm[ ]*=[ ]*)\".*\"/\1\"$realm\"/" $freediameter_conf_path/hss_fd.conf
    sed -r -i  "s/(^ALLOW_OLD_TLS[ ]*).*/\1*.$realm/" $freediameter_conf_path/acl.conf

    $build_run_scripts/check_hss_s6a_certificate $freediameter_conf_path $fqdn
fi

if [ -z "$(relation-ids db)" ]; then
   juju-log "HSS is built, but is waiting for active connection to gather the last info"
   juju-log "no db is found, so HSS process is not going to be run" 
else
   $CHARM_DIR/hooks/start
   #if hss relation exists
   for hss_id in $(relation-ids hss); do
       restart=`relation-get -r $hss_id trigger_restart $JUJU_UNIT_NAME`
       relation-set -r $hss_id trigger_restart=$(($((restart + 1)) % 10))
       relation-set -r $hss_id hss_running=yes
   done

fi

sed -r -i "s/(OPERATOR_key[^\"]*)\".*\"/\1\"$oai_op_key\"/" $hss_conf/hss.conf


