#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file upgrade-charm
# brief called when each time a charm is upgraded after the new charm
# contents have been unpacked
# author  navid.nikaein@eurecom.fr and A. B. Molini 

# Best practice suggests you execute the hooks/install and
# hooks/config-changed to ensure all updates are processed

set -eux
systemctl stop  oai_hss || true
$CHARM_DIR/hooks/install #Re-run install 

if [ -z "$(relation-ids db)" ]; then
   juju-log "HSS is built, but is waiting for active connection to gather the last info"
   juju-log "no db is found, so HSS process is not going to be run" 
   exit 0
fi

#Fill again the hss.conf file since it has been downloaded a fresh installation...don't want to lose db relation data in the configuration
#No cycle, only one database master.
db_id=`relation-ids db`
db_unit=`relation-list -r $db_id`
db_user=`relation-get -r "$db_id" user $db_unit`
db_password=`relation-get -r "$db_id" password $db_unit`
db_host=`relation-get -r "$db_id" host $db_unit`
db_database=`relation-get -r "$db_id" database $db_unit`
 
db_data_in_config_file $db_host $db_user $db_password $db_database


