#!/bin/sh

. $SNAP/common

case "$1" in
    "set-hss" )
	CONFIG_FILE=$2
	if [ -f "$CONFIG_FILE" ]; then
	    echo "Setting the default config file to: $CONFIG_FILE"
	    
	elif [ -f "$(dirname $(readlink -f $0))/$CONFIG_FILE" ]; then
	    CONFIG_FILE=$(dirname $(readlink -f $0))/$CONFIG_FILE
	    echo "Config file <$CONFIG_FILE> not found in the local directory!"
	    echo "Resetting to the default config file: $CONFIG_FILE"
	    
	else
	    echo "Config file <$CONFIG_FILE> not found!"
	    echo "Resetting to the default config file: $HSS_CONF_FILE"
	    CONFIG_FILE=$HSS_CONF_FILE
	fi
	
	echo "HSS_CONF_FILE2=$CONFIG_FILE" > $SNAP_DATA/config_hss.sh
       	echo "HSS_CONF_FILE2=$CONFIG_FILE" > $SNAP_USER_DATA/config_hss.sh
	;;

    
     "ls-hss" )
	if [ -r $SNAP_DATA/config_hss.sh ]; then
	    . $SNAP_DATA/config_hss.sh
	fi
	
	# default config file is (unless set in above config)
	HSS_CONFIG=${HSS_CONF_FILE2:-$HSS_CONF_FILE}
	ls $(dirname $HSS_CONFIG)/hss*.conf
	;;

     "echo-hss" | "cat-hss" )
	
	if [ -r $SNAP_DATA/config_hss.sh ]; then
	    . $SNAP_DATA/config_hss.sh
	fi
	
	# default config file is (unless set in above config)
	HSS_CONFIG=${HSS_CONF_FILE2:-$HSS_CONF_FILE}
	# echo (get), cat (show)
        `echo $1 | cut -d"-" -f1` $HSS_CONFIG
	;;
      *)
       echo "unknown command $1"
       ;;
esac
    

