#!/usr/bin/python3

#Copyright (c) 2017 Sprint
################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under
# the Apache License, Version 2.0  (the "License"); you may not use this file
# except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################
# file data_provisioning_users
# brief
# main author Sprint
# company Sprint
# email:
# other author Lionel GAUTHIER for python conversion

import argparse
import logging
#import json
#import tempfile
from cassandra.cluster import Cluster


def main():

    #logger = logging.getLogger()
    #logger.setLevel(logging.DEBUG)

    parser = argparse.ArgumentParser()
    parser.add_argument('-C', '--cassandra-cluster', default='127.0.0.1',      help="Cassandra list of nodes")
    args = parser.parse_args()

    
    # This will attempt to connection to a Cassandra instance on your local machine (127.0.0.1)
    # The set of IP addresses we pass to the :class:`~.Cluster` is simply an initial set of contact points.
    # After the driver connects to one of these nodes it will automatically discover the rest of the nodes
    # in the cluster and connect to them, so you don't need to list every node in your cluster.
    cluster = Cluster([args.cassandra_cluster])

    session = cluster.connect()
    # session.set_keyspace('mykeyspace')

    # TODO pretty print
    rows = session.execute('SELECT imsi, msisdn, access_restriction, key, mmehost, mmeidentity_idmmeidentity, mmerealm, rand, sqn, subscription_data FROM vhss.users_imsi')
    count = 0
    print ('imsi | msisdn | access_restriction | key | mmehost | mmeidentity_idmmeidentity | mmerealm | rand | sqn | subscription_data |')
    for row in rows:
        #logging.info("%s %s %s %s %s %s %s %s %s %s" % (row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9]))
        print()
        print ('user_'+str(count)+': ', row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9])
        count +=1

if __name__ == "__main__":
    main()






