#!/bin/bash

revision=$1
cd ..
source /home/$USER/mosaic-5g/jox/joxenv
cd -
#declare -a bundles=("oai-5G-cran-mwc17" "oai-5G-cran-slice-mwc17" "oai-5G-cran-snap-mwc17")
declare -a bundle=("oai-5G-cran" "oai-5g-cran-slice" "oai-5g-cran-snap"  "oai-nfv-4g")

    cd $JUJU_REPOSITORY  #$s
    #for k in "${charms[@]}"
    for k in "${bundle[@]}"
    do
	  echo "bundle: " $k
	  url=`/usr/bin/charm push . cs:~navid-nikaein/bundle/$k | grep url | cut -f2 -d' '`
	  echo "pushed url: $url"
	  #/usr/bin/charm release $url
	  /usr/bin/charm publish $url
	  /usr/bin/charm grant $url everyone
	  cd ..
    done
    cd .. 
    


