#!/bin/bash

set -eux

source $CHARM_DIR/utils/common

if [ -f $CHARM_DIR/.dtn_running ]; then
  dtn_running=`cat $CHARM_DIR/.dtn_running`
else
  dtn_running="0"
fi

if [ "$dtn_running" == "1" ] ; then 
    service dtn restart || service dtn start
    
    check_dtn_process
    if [ $status -eq 1 ]; then
	juju-log "Trouble with dtn  upstart file...try to upgrade the charm"
	status-set blocked "Trouble with dtn upstart file...try to upgrade the charm"
	exit 1
    fi 
fi 


