#!/bin/bash
################################################################################

set -eux

source $CHARM_DIR/utils/common
set_env_paths

juju-log "Stopping dtn  service in this unit"
service dtn stop || true
juju-log "Done"

juju-log "Cleaning up the dtn installation directory..."
rm -rf $dtn_path
juju-log "dtn removed"

juju-log "Removing Upstart script from the system..."
rm -f /etc/init/dtn.conf
juju-log "Done"


