#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file config-change
# brief manage the config changes of oai-rru-snap service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr 

set -eux

node_func=`config-get node_function`
file_config=`cat $CHARM_DIR/.config_file`

if [ "$node_func" != "$(cat $CHARM_DIR/.node_func)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
    juju-log "node function changed"
fi

if [ "$(config-get target_hardware)" != "$(cat $CHARM_DIR/.hw)" ]; then
    juju-log "hw name changed"
    $CHARM_DIR/hooks/upgrade-charm
fi

# The installation runs unnecessarily multiple times for default config file
if [ "$(config-get config_file)" != "default" ] ; then
  if [ "$file_config" != "$(config-get config_file)" ]; then 
    # we don't know what is changed 
      $CHARM_DIR/hooks/upgrade-charm
      juju-log "config_file changed"
  fi  
fi

if [ "$(config-get eutra_band )" != "$(cat $CHARM_DIR/.band)" ]; then
    juju-log "EUTRA band changed"
    $CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get N_RB_DL )" != "$(cat $CHARM_DIR/.bw)" ]; then
    juju-log "bandwidth changed"
    $CHARM_DIR/hooks/upgrade-charm
fi


if [ "$(config-get fh_transport_mode)" != "$(cat $CHARM_DIR/.fh_tr_mode)" ]; then
    juju-log "fronthaul transport mode changed"
    $CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get user_name)" != "$(cat $CHARM_DIR/.user_name)" ]; then
    juju-log "user name changed"
    $CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get passwd)" != "$(cat $CHARM_DIR/.passwd)" ]; then
    juju-log "passwd changed"
    $CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get rru_ip)" != "$(cat $CHARM_DIR/.rru_ip)" ]; then
    juju-log "rru ip changed"
    $CHARM_DIR/hooks/upgrade-charm
fi


