#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file manage the config changes of oai-rrh service 
# brief config-changed occurs everytime a new configuration value is updated (juju set)
# author  navid.nikaein@eurecom.fr 

set -eux
source $CHARM_DIR/utils/common
set_env_paths


if [ "$(config-get branch)" != "$(cat $CHARM_DIR/.branch)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get target_hardware)" != "$(cat $CHARM_DIR/.hw)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get kernel)" != "$(cat $CHARM_DIR/.kernel)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
    juju-log "kernel changed"
fi

if [ "$(config-get fronthaul_if)" != "$(cat $CHARM_DIR/.fh_if)" ]; then
    echo "$(config-get fronthaul_if)" > $CHARM_DIR/.fh_if
    cp $CHARM_DIR/.fh_if $openair_path
    #Run RRH only if it was running previously
    if [ -f $CHARM_DIR/.rrh_running ] && [ "`cat $CHARM_DIR/.rrh_running`" == "yes" ]  ; then 
       $CHARM_DIR/hooks/start
    fi
    #$CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get config_file)" != "$(cat $CHARM_DIR/.config_file_rrh)" ]; then
    echo "$config_file_sodera_path/$(config-get config_file)" > $CHARM_DIR/.config_file_rrh
    cp $CHARM_DIR/.config_file_rrh $openair_path
    #Run RRH only if it was running previously
    if [ -f $CHARM_DIR/.rrh_running ] && [ "`cat $CHARM_DIR/.rrh_running`" == "yes" ]  ; then 
       $CHARM_DIR/hooks/start
    fi
fi

if [ "$(config-get loopback)" != "$(cat $CHARM_DIR/.loopback)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
fi



##############################################################################################
#if [ -n "$fh_if" ]; then
#   ipv4=`ifconfig $iface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`
#   juju-log "ipv4 address $ipv4 associated to interface $fh_if"
#fi
 
