#! /bin/bash
################################################################################
# Licensed to the Mosaic5G under one or more contributor license
# work for additional information regarding copyright ownership.
# Apache License, Version 2.0  (the "License");
# You may obtain a copy of the License at
#  
#    	http://www.apache.org/licenses/LICENSE-2.0
#  
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# -------------------------------------------------------------------------------
#   For more information about the Mosaic5G:
#   	contact@mosaic-5g.io
#
#
################################################################################
# file common
# brief common scripts and variables for oai-sim Snap
# author Navid Nikaein (navid.nikaein@eurecom.fr, navid.nikaein@mosaic-5g.io)

export DEBIAN_FRONTEND=noninteractive
set -e

CONF_DIR="$SNAP_DATA"

UE_DIR="$SNAP/sim"
UE_EXEC="$UE_DIR/oai-ue"
USIM_EXEC="$UE_DIR/usim"
USIM_MULTI_EXEC="$UE_DIR/conf2uedata"
NVRAM_EXEC="$UE_DIR/nvram"

UE_CONF_FILE="$CONF_DIR/ue.l2sim.conf"
UE_CMD_FILE="$CONF_DIR/ue.l2sim.cmd"
USIM_CONF_FILE="$CONF_DIR/usim_multi.conf"


ENB_DIR="$SNAP/sim"
ENB_EXEC="$UE_DIR/oai-enb"
ENB_CONF_FILE="$CONF_DIR/enb.l2sim.conf"
