#! /bin/bash
################################################################################
# Licensed to the Mosaic5G under one or more contributor license
# work for additional information regarding copyright ownership.
# Apache License, Version 2.0  (the "License");
# You may obtain a copy of the License at
#  
#    	http://www.apache.org/licenses/LICENSE-2.0
#  
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# -------------------------------------------------------------------------------
#   For more information about the Mosaic5G:
#   	contact@mosaic-5g.io
#
#
################################################################################
# file util
# brief util scripts and variables for oai-sim Snap
# author Navid Nikaein (navid.nikaein@eurecom.fr, navid.nikaein@mosaic-5g.io)


. $SNAP/common

# Echo 
black='[30m'
red='[31m'
green='[32m'
yellow='[33m'
blue='[1;34m'
magenta='[35m'
cyan='[36m'
white='[37m'
reset_color='[00m'
COLORIZE=1

cecho()  {  
    # Color-echo
    # arg1 = message
    # arg2 = color
    local default_msg="No Message."
    message=${1:-$default_msg}
    color=${2:-$green}
    [ "$COLORIZE" = "1" ] && message="$color$message$reset_color"
    echo -e "$message"
    return
}

echo_error()   { cecho "$*" $red          ;}
echo_fatal()   { cecho "$*" $red; exit -1 ;}
echo_warn()    { cecho "$*" $yellow       ;}
echo_success() { cecho "$*" $green        ;}
echo_info()    { cecho "$*" $blue         ;}


if_sudo(){

    if [ "$(id -u)" -eq 0 ] ; then
	return 0
    else
	echo "Please run as a sudoer!"
	exit 1
    fi
}

set_health(){
    
    status=$(snapctl services $SNAP_NAME.ued)
    case "$status" in
	*inactive*)
	    #echo "Service inactive"
	    snapctl set-health --code=ready blocked "$SNAP_NAME ready to be run"
	    ;;
	*active*)
	    #echo "Service active"
	    snapctl set-health okay
	    ;;
	*)
            #echo "Unknown service state"
	    snapctl set-health --code=error error "Execution failed. Checked the Journal"
	    ;;
    esac 
    
}

snap_isconnected(){

    echo_warn "Plug $1: snap connect $SNAP_NAME:$1"
    snapctl is-connected $1
    echo_success "$1 connected"
    
}

set_enb_vars(){
    
    ENB_CONFIG=$(snapctl get conf.enbsim)

    ENBUE_IF=`cat $ENB_CONFIG | grep "local_s_if_name" | cut -f2 -d= | tr -d '"' | tr -d " " | tr -d ";"`
    ENBUE_ADDR=`cat $ENB_CONFIG | grep "local_s_address" | cut -f2 -d= | tr -d '"' | tr -d " " | tr -d ";"`
  
}

dump_enb_vars(){
    
    echo_info "ENB-UE IF:"   $ENBUE_IF
    echo_info "ENB-UE ADDR:" $ENBUE_ADDR
  
}

snap_info(){
    echo_info "Snap Name: $SNAP_NAME"
    echo_info "Snap Instance Name: $SNAP_INSTANCE_NAME"
    echo_info "Sanp Version: $SNAP_VERSION"
    echo_info "Sanp Revision: $SNAP_REVISION"
    echo_info "Snap Data: $SNAP_DATA"
    echo_info "Snap Conf: "
    snapctl get conf
    echo_info 'Snap Permissions to be granted:
    	- log-observe
        - network-control
        - process-control
        - netlink-connector'
	          
 echo ""
 echo_warn "Check current permissions: snap connection $SNAP_NAME"
}

snap_help(){
	echo "Usage:                sudo  $SNAP_NAME.ue and $SNAP_NAME.enb args"
	echo "                       App [x] is ue or enb"
	echo ""
	echo "oai-sim.init           init the $SNAP_NAME"
	echo "oai-sim.info           get the info for the $SNAP_NAME"
	echo "oai-sim.check          check the commands, servies, and executions of the $SNAP_NAME"
	echo ""
	echo "oai-sim.[x]-journal    get the $SNAP_NAME.[x] daemon logs"
	echo "oai-sim.[x]-restart    restart the $SNAP_NAME.[x] daemon"
	echo "oai-sim.[x]-start      start the $SNAP_NAME.[x] daemon"
	echo "oai-sim.[x]-status     status the $SNAP_NAME.[x] daemon"
	echo "oai-sim.[x]-stop       stop the $SNAP_NAME.[x] daemon"
	echo ""
	echo "oai-sim.usim-gen:      generate usim data file for single or multi UEs"
	echo "oai-sim.usim-print:    print the usim configure data file"
	echo "oai-sim.nvram-print:   print the nvram data file"
	echo "oai-sim.debug:         debug the $SNAP_NAME UE with gdb"
	echo "oai-sim.usim-set:      set the USIM configuration file"
	echo "oai-sim.usim-get:      get the current USIM  configuration file"
	echo "oai-sim.usim-show:     show the current USIM configuration file"
	echo "oai-sim.usim-list:     list the USIM configuration files"
	echo ""
	echo "oai-sim.help:          print this help"
	
}
