#! /bin/bash
################################################################################
# Licensed to the Mosaic5G under one or more contributor license
# work for additional information regarding copyright ownership.
# Apache License, Version 2.0  (the "License");
# You may obtain a copy of the License at
#  
#    	http://www.apache.org/licenses/LICENSE-2.0
#  
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# -------------------------------------------------------------------------------
#   For more information about the Mosaic5G:
#   	contact@mosaic-5g.io
#
#
################################################################################
# file init
# brief init scripts and variables for oai-tracer Snap
# author Navid Nikaein (navid.nikaein@eurecom.fr, navid.nikaein@mosaic-5g.io)


. $SNAP/common
. $SNAP/util

if_sudo

cp $SNAP/T/tracer/T_messages.txt  $CONF_DIR
#cp $SNAP/etc/* $CONF_DIR


$SNAP/conf set $CONF_DIR/T_messages.txt
snapctl get conf.tracer

# a copy all the config files for the user
cp $CONF_DIR/* $SNAP_USER_DATA

echo_success "OAI Tracer init: done "

echo ""
echo_info "$SNAP_NAME snap info:"
snap_info 
