#!/bin/sh

. $SNAP/common

if [ ! -f $CONF_DIR/T_messages.txt ] ; then
    cp $SNAP/etc/* $CONF_DIR
fi


$SNAP/conf set-tracer $CONF_DIR/T_messages.txt
$SNAP/conf get-tracer

# a copy all the config files for the user
cp $CONF_DIR/* $SNAP_USER_DATA

echo "OAI Tracer init: done "
