#!/bin/sh

. $SNAP/common

if [ ! -e $T_EXEC ]; then
    echo "Cannot find $T_EXEC executable"
    exit 127
fi		   	   

if [ -r $SNAP_DATA/config.sh ]; then
    . $SNAP_DATA/config.sh
fi

T_CONFIG=${T_CONF_FILE2:-$T_CONF_FILE}
T_EXEC_ARGS=" -d $T_CONFIG"

case "$1" in
    
    "info" )
	snap info $SNAP_NAME
	;; 
    "help" )
	echo "Usage:                   $SNAP_NAME [-ip IP@OAI-RAN]"
	echo "Options:"
	echo "oai-tracer.info          get the info for this snap"            
	echo "oai-tracer.init          initialize $SNAP_NAME (after the 1st installation)"
	echo ""
	echo "oai-tracer               run $SNAP_NAME manually"
	echo "oai-tracer.conf-get      get the current $SNAP_NAME.[X] configuration file"
	echo "oai-tracer.conf-list     list the $SNAP_NAME.[x] configuration files"
	echo "oai-tracer.conf-set      set the $SNAP_NAME.[x] configuration file"
	echo "oai-tracer.conf-show     show the path to the $SNAP_NAME.[x] configuration file"
	echo ""
	echo "  help:                   print this help"
	;;

    * )
	echo "$T_EXEC  $T_EXEC_ARGS $@"
	$T_EXEC  `echo $T_EXEC_ARGS` "$@"
	;;

esac
