#! /bin/bash
################################################################################
# Licensed to the Mosaic5G under one or more contributor license
# work for additional information regarding copyright ownership.
# Apache License, Version 2.0  (the "License");
# You may obtain a copy of the License at
#  
#    	http://www.apache.org/licenses/LICENSE-2.0
#  
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# -------------------------------------------------------------------------------
#   For more information about the Mosaic5G:
#   	contact@mosaic-5g.io
#
#
################################################################################
# file run
# brief run scripts and variables for oai-tracer Snap
# author Navid Nikaein (navid.nikaein@eurecom.fr, navid.nikaein@mosaic-5g.io)


. $SNAP/common
. $SNAP/util

if [ ! -e $T_EXEC ]; then
    echo_error "Cannot find $T_EXEC executable"
    exit 127
fi		   	   

if [ -r $SNAP_DATA/config.sh ]; then
    . $SNAP_DATA/config.sh
fi

export LD_LIBRARY_PATH="$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"

T_CONFIG=${T_CONF_FILE2:-$T_CONF_FILE}
T_EXEC_ARGS=" -d $T_CONFIG"

case "$1" in
    
    "info" )
	snap_info
	;; 
    "help" )
	snap_help
	;;

    * )
	shift 
	
	if_user
	snap_isconnected desktop
	snap_isconnected network-bind
	snap_isconnected x11
       
	echo_info "$T_EXEC  $T_EXEC_ARGS $@"
	$T_EXEC  `echo $T_EXEC_ARGS` "$@"
	;;

esac
