options:
   branch:
     default: "master"
     description: |
       branch indicates which installation you want to do. If you want a stable installation, change this option to "master". 
     type: string
   revision: 
     default: "6a6ee500ce13df3ae37dc6671ffc9e144df92f45"   
     description: get a specific revison from the openair-cn git repository. 
     type: string
   sgw-eth:
     default: "eth0"
     description: |
       This is usefull especially when you are in manual environment so you have your own machines. The default value is eth0. NO empty value.
     type: string
   pgw-eth:
     default: "eth0"
     description: |
       This is usefull especially when you are in manual environment so you have your own machines. The default value is eth0. NO empty value.
     type: string
   ipv4_list_start:
     default: "192.188.1.0/24"
     description: First IP address pool that will be assigned to UEs.
     type: string
   ipv4_list_end:
     default: "192.188.2.0/24"
     description: Second IPv4 address pool that will be assigned to UEs.
     type: string
   ipv6_list:
     default: "2014:02:26::0/120"
     description: First IPv6 addresse pool available to be assigned to UEs.
     type: string
   DEFAULT_DNS_IPV4_ADDRESS:
     default: "8.8.8.8"
     description: IPv4 address of primary default DNS that can be queried by UEs.
     type: string
   DEFAULT_DNS_SEC_IPV4_ADDRESS:
     default: "8.8.8.8"
     description: IPv4 address of secondary default DNS that can be queried by UEs.
     type: string






