#! /bin/bash
################################################################################
# Licensed to the Mosaic5G under one or more contributor license
# work for additional information regarding copyright ownership.
# Apache License, Version 2.0  (the "License");
# You may obtain a copy of the License at
#  
#    	http://www.apache.org/licenses/LICENSE-2.0
#  
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# -------------------------------------------------------------------------------
#   For more information about the Mosaic5G:
#   	contact@mosaic-5g.io
#
#
################################################################################
# file common
# brief common scripts and variables for oai-cn Snap
# author Navid Nikaein (navid.nikaein@eurecom.fr, navid.nikaein@mosaic-5g.io)


export DEBIAN_FRONTEND=noninteractive
set -e
#export UHD_IMAGES_DIR=$SNAP/uhd_images


CONF_DIR="$SNAP_DATA"

MME_DIR="$SNAP/mme"
MME_CONF_FILE="$CONF_DIR/mme.conf"
MME_FD_CONF_FILE="$CONF_DIR/mme_fd.conf"
MME_EXEC="$MME_DIR/mme"


SPGW_DIR="$SNAP/spgw"
SPGW_CONF_FILE="$CONF_DIR/spgw.conf"
SPGW_EXEC="$SPGW_DIR/spgw"


HSS_DIR="$SNAP/hss"
HSS_CONF_FILE="$CONF_DIR/hss.conf"
HSS_FD_CONF_FILE="$CONF_DIR/hss_fd.conf"
HSS_ACL_CONF_FILE="$CONF_DIR/acl.conf"
#echo "$HSS_ACL_CONF_FILE"

HSS_EXEC="$HSS_DIR/oai_hss"
HSS_DB="$HSS_DIR/oai_db.sql"
MYSQL_SERVER="127.0.0.1"     # HSS S6a bind address
MYSQL_USER="root"  # Database server login
MYSQL_PW="linux"  # Database server password


# test command
# mysql -h 127.0.0.1 -u root --password=linux -e "DROP DATABASE IF EXISTS oai_db;"
#mysql -h 127.0.0.1 -u root --password=linux -e "CREATE DATABASE IF NOT EXISTS oai_db;"
#mysql -h 127.0.0.1 -u root -plinux oai_db < /snap/oai-cn/current/hss/oai_db.sql 

#REALM="openair4G.eur"
