#!/bin/sh

. $SNAP/common

echo "Init $1"

case "$1" in
    "hss" )
	if [ ! -f $CONF_DIR/hss.conf ] ; then
	    cp $SNAP/etc/hss.conf $CONF_DIR
	    cp $SNAP/etc/hss_fd.conf $CONF_DIR
	    cp $SNAP/etc/acl.conf $CONF_DIR
	fi
	# set the hss.conf
	echo "set-hss $CONF_DIR/hss.conf"
	$SNAP/conf set-hss $CONF_DIR/hss.conf
	
	# a copy for the user: with sudo, the user is root
	echo "copying the config file to $SNAP_USER_DATA"
	cp $CONF_DIR/hss.conf $SNAP_USER_DATA
	cp $CONF_DIR/hss_fd.conf $SNAP_USER_DATA
	cp $CONF_DIR/acl.conf $SNAP_USER_DATA

	# this part needs sudo privilage 
  	service mysql restart

	if [ -z "$(grep -o "`hostname`.$REALM" /etc/hosts)" ]; then
	    cp /etc/hosts /etc/hosts.orig
	    #echo 127.0.0.1 localhost > /etc/hosts
	    echo 127.0.0.1 `hostname`.$REALM `hostname` hss >> /etc/hosts
	    echo 127.0.0.1 `hostname`.$REALM `hostname` mme >> /etc/hosts
	fi

	$SNAP/run import-db
	$SNAP/run hss-certificate
	$SNAP/run hss-add-mme
	echo ""
	echo "HSS is initialized"
	echo "Now, it is the time to configure the hss_fd.conf"
	;;
    
    "mme" )

	if [ ! -f $CONF_DIR/mme.conf ] ; then
	    cp $SNAP/etc/mme.conf $CONF_DIR
	    cp $SNAP/etc/mme_fd.conf $CONF_DIR
	fi
	# set the mme.conf
	$SNAP/conf set-mme $CONF_DIR/mme.conf

	# a copy for the user
	cp $CONF_DIR/mme.conf $SNAP_USER_DATA
	cp $CONF_DIR/mme_fd.conf $SNAP_USER_DATA

	if [ -z "$(grep -o "`hostname`.$REALM" /etc/hosts)" ]; then
	    cp /etc/hosts /etc/hosts.orig
	    echo 127.0.0.1 localhost > /etc/hosts
	    echo 127.0.0.1 `hostname`.$REALM `hostname` hss >> /etc/hosts
	    echo 127.0.0.1 `hostname`.$REALM `hostname` mme >> /etc/hosts
	fi
	$SNAP/run mme-certificate
	echo ""
	echo "MME is initialized"
	echo "Now, it is the time to configure the mme.conf and mme_fd.conf"
	
	
	;;
    "spgw" )

	if [ ! -f $CONF_DIR/spgw.conf ] ; then
	    cp $SNAP/etc/spgw.conf $CONF_DIR
	fi
	# set the hss.conf
	$SNAP/conf set-spgw $CONF_DIR/spgw.conf

	# a copy for the user
	cp $CONF_DIR/spgw.conf $SNAP_USER_DATA
	echo""
	echo "SPGW is initialized"
	echo "Now, configure the mme.conf file (mainly the NETWORK_INTERFACES and P-GW sections)"
	;;
    * )
	echo "Unknown command: $1"
	;;

esac

	

