#! /bin/bash
################################################################################
# Licensed to the Mosaic5G under one or more contributor license
# work for additional information regarding copyright ownership.
# Apache License, Version 2.0  (the "License");
# You may obtain a copy of the License at
#  
#    	http://www.apache.org/licenses/LICENSE-2.0
#  
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# -------------------------------------------------------------------------------
#   For more information about the Mosaic5G:
#   	contact@mosaic-5g.io
#
#
################################################################################
# file test
# brief test scripts and variables for oai-cn Snap
# author Navid Nikaein (navid.nikaein@eurecom.fr, navid.nikaein@mosaic-5g.io)


. $SNAP/common

echo "Test Snap Service $1"

waiting_time=2
case "$1" in
    "hss-service" )
	$SNAP/run status hssd 
	sleep $waiting_time 
	$SNAP/run start hssd
	sleep $waiting_time 
	$SNAP/run status hssd
	sleep $waiting_time 
	$SNAP/run stop hssd
	sleep $waiting_time
	$SNAP/run status hssd
	sleep $waiting_time 

    ;;

    "all" )
	$SNAP/run status-all
	sleep $waiting_time 
	$SNAP/run start-all
	sleep $waiting_time 
	$SNAP/run status-all
	sleep $waiting_time 
	$SNAP/run stop-all
	sleep $waiting_time
	$SNAP/run status-all
	sleep $waiting_time 
	;;
	
    * )
	echo "Unknown command: $1"
	;;

esac

	
