name: ll-mec
version: '1.3' 
summary: Low Latency MEC platform
description: |
   LL-MEC is a Low Latency Multi-access Edge Computing platform licensed under Apache License V2.0. It is one of the projects of Mosaic5G inititive.
type: app
architectures:
  - amd64
  - i386
icon: meta/gui/icon.png  
grade: stable
confinement: devmode

apps:
  ll-mec:
    command: run
  info:
    command: run info
  init:
    command: init
  daemon:
    command: run
    daemon: simple
    stop-command: run stop
    stop-timeout: 10s
  start:
    command: run start
  stop:
    command: run stop
  restart:
    command: run restart
  status:
    command: run status
  journal:
    command: run journal
  help:
    command: run help
  debug:
    command: run gdb
  conf-set:
    command: conf set
  conf-get:
    command: conf echo
  conf-show:
    command: conf cat
  
hooks:
  install:
    plugs: [home, network]
  configure:
    plugs: [home, network]
parts:
  gdb:
    plugin: nil
    override-build: |
      sudo apt install gdb -y
      mkdir $SNAPCRAFT_PART_INSTALL/share 
      cp -r /usr/share/gdb $SNAPCRAFT_PART_INSTALL/share
      cp /usr/bin/gdb* $SNAPCRAFT_PART_INSTALL
    prime:
      - gdb*
      - share/*
      
  pistache:
    plugin: cmake
    source:  https://github.com/oktal/pistache.git
    override-build: |
      mkdir -p build
      cd build
      cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
      make
      sudo make install
      cd -
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      cp /usr/local/lib/libpistache.a $SNAPCRAFT_PART_INSTALL/lib
    prime:
      - lib/libpistache.a
  ll-mec:
    after: [ pistache, ]
    plugin: cmake
    source: https://gitlab.eurecom.fr/mosaic5g/ll-mec.git
    source-branch: develop
    build-packages: [build-essential, g++, libevent-dev, libssl-dev]
    stage-packages:
      - libssl1.0.0 
      - libevent-2.0-5 
    override-build: |
      ./build_ll-mec.sh
      #mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp ./llmec_config.json $SNAPCRAFT_PART_INSTALL
      cp ./ll-mec $SNAPCRAFT_PART_INSTALL
    stage:
      - ll-mec
      - llmec_config.json
      - usr/lib/*
      - lib/*
    prime:
      - ll-mec
      - llmec_config.json
      - usr/lib/*
      - lib/*

  frontend:
    plugin: dump
    source: frontend
