#!/bin/bash

. $SNAP/common
. $SNAP/util


if [ ! -f $CONF_DIR/llmec_config.json ] ; then
    cp $SNAP/etc/* $CONF_DIR
fi

snapctl set conf=$CONF_DIR/llmec_config.json
$SNAP/conf set $(snapctl get conf)
echo_info "default ll-mec conf:" $SNAP/conf echo

# a copy for the user
cp $CONF_DIR/llmec_config.json $SNAP_USER_DATA

echo_success "LLMEC init: done "
