#!/bin/sh

. $SNAP/common

if [ ! -f $CONF_DIR/llmec_config.json ] ; then
    cp $SNAP/etc/* $CONF_DIR
fi

# set the conf
$SNAP/conf set $CONF_DIR/llmec_config.json

# a copy for the user
cp $CONF_DIR/llmec_config.json $SNAP_USER_DATA

echo "LLMEC init: done "
