#!/bin/bash

. $SNAP/common
. $SNAP/util

export LD_LIBRARY_PATH="$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"

if [ ! -e $LLMEC_EXEC  ]; then
    echo_error "Command $LLMEC_EXEC not found"
    exit 127
fi		   	   

if [ -r $CONF_DIR/config.sh ]; then
    . $CONF_DIR/config.sh
fi

# default config file is llmec_config.json (unless set in above config)
LLMEC_CONFIG=${LLMEC_CONF_FILE2:-$LLMEC_CONF_FILE}
# To let the service start automatically
# if ll-mec config file is not initialized, get the default 
if [ -e "$LLMEC_CONFIG" ] ; then
    LLMEC_EXEC_ARGS=" -c $LLMEC_CONFIG"
else
    #$SNAP/init
    LLMEC_EXEC_ARGS=" -c $SNAP/etc/llmec_config.json"
    cp $SNAP/etc/llmec_config.json $SNAP_USER_DATA
fi


case "$1" in
    "gdb" )
	echo "Running $SNAP_NAME with the gdb"
	touch      $SNAP_DATA/.gdb_$SNAP_NAME
	chmod 777  $SNAP_DATA/.gdb_$SNAP_NAME
	echo "file $LLMEC_EXEC"           > $SNAP_DATA/.gdb_$SNAP_NAME
	echo "set args $LLMEC_EXEC_ARGS" >> $SNAP_DATA/.gdb_$SNAP_NAME
	echo "run"                       >> $SNAP_DATA/.gdb_$SNAP_NAME
	cat $SNAP_DATA/.gdb_$SNAP_NAME
	exec $SNAP/gdb --data-directory=$SNAP_DATA  -n -x $SNAP_DATA/.gdb_$SNAP_NAME
	;;
    "info" )
	shift 
	snap_info
	;;

    "start"  )
	daemon=$2
	shift 2
	if_sudo
	snapctl start --enable $SNAP_NAME.$daemon "$@"
	snapctl services $SNAP_NAME.$daemon
	;; 

    "start-all"  )
	daemon=$2
	shift
	if_sudo
	snapctl start --enable $SNAP_NAME "$@"
	snapctl services $SNAP_NAME	
	
	;;
    "stop" )
	daemon=$2
	shift 2
	if_sudo
	snapctl stop --disable $SNAP_NAME.$daemon "$@"
	snapctl services $SNAP_NAME.$daemon
	
	;;
    "stop-all" )
	daemon=$2
	shift
	if_sudo
	snapctl stop --disable $SNAP_NAME "$@"
	snapctl services $SNAP_NAME

	;;
    "restart" )
	daemon=$2
	shift 2
	if_sudo
	snapctl stop --disable $SNAP_NAME.$daemon "$@"
	snapctl start --enable $SNAP_NAME.$daemon "$@"
	snapctl services $SNAP_NAME.$daemon
	;;

    "status" )
	daemon=$2
	shift 2
	# echo "Please manually run: snap services $SNAP_NAME.$daemon" 
	snapctl services $SNAP_NAME.$daemon 
	#systemctl status --lines 0 snap.$SNAP_NAME.$2.service

		;; 
    "status-all"  )
	daemon=$2
	shift
	if_sudo
	snapctl services $SNAP_NAME
	;;

    "journal" )
	daemon=$2
	shift 2
	journalctl -u snap.$SNAP_NAME.$daemon.service "$@"
	;;


    "help" )
	snap_help
	;;
    *)
	echo_info "$LLMEC_EXEC  `echo $LLMEC_EXEC_ARGS` "$@"" 
	$LLMEC_EXEC  `echo $LLMEC_EXEC_ARGS` "$@"
	;;
esac


set_health
