#!/bin/sh

. $SNAP/common

case "$1" in

    "set-spgwu" )
	CONFIG_FILE=$2
	if [ "$CONFIG_FILE" != "${CONFIG_FILE#/}" -a -f "$CONFIG_FILE" ]; then
	    echo "Setting the default config file to: $CONFIG_FILE"
	    
	elif [ -f "$CONF_DIR/$CONFIG_FILE" ]; then
	    CONFIG_FILE=$CONF_DIR/$CONFIG_FILE
	    echo "Config file found in the $CONF_DIR!"
	    echo "Resetting to the default config file: $CONFIG_FILE"
	    
	else
	    echo "[ERR] Config file $CONFIG_FILE not found, please provide an absolute path!"
	    echo "Reset to default config file: $SPGWU_CONF_FILE"
	    CONFIG_FILE=$SPGWU_CONF_FILE
	fi

	echo "SPGWU_CONF_FILE2=$CONFIG_FILE" > $SNAP_DATA/config_spgwu.sh
	echo "SPGWU_CONF_FILE2=$CONFIG_FILE" > $SNAP_USER_DATA/config_spgwu.sh
	;;
    
     "ls-spgwu" )
        if [ -r $SNAP_DATA/config_spgwu.sh ]; then
	    . $SNAP_DATA/config_spgwu.sh
	fi
	
	# default config file is (unless set in above config)
	SPGWU_CONFIG=${SPGWU_CONF_FILE2:-$SPGWU_CONF_FILE}
	ls $(dirname $SPGWU_CONFIG)/*
	;;
     
      "echo-spgwu" | "cat-spgwu" )
	
	if [ -r $SNAP_DATA/config_spgwu.sh ]; then
	    . $SNAP_DATA/config_spgwu.sh
	fi
	
	# default config file is (unless set in above config)
	SPGWU_CONFIG=${SPGWU_CONF_FILE2:-$SPGWU_CONF_FILE}
	# echo (get), cat (show)
	`echo $1 | cut -d"-" -f1` $SPGWU_CONFIG
	;;
      
      *)
       echo "unknown command $1"
       ;;
esac
    

