#!/bin/sh

. $SNAP/common

case "$1" in

    "set-spgwu" )
	CONFIG_FILE=$2
	if [ -f $(dirname $(readlink -f $0))/$CONFIG_FILE ]; then
	    CONFIG_FILE=$(dirname $(readlink -f $0))/$CONFIG_FILE
	    echo "Setting the default config file to: $CONFIG_FILE"
	else
	    # may be absolute path 
	    if [ -f "$CONFIG_FILE" ]; then
		# $CONFIG_FILE already exist in the $SNAP_DATA
		if [ -f $SNAP_DATA/$(basename $CONFIG_FILE) ] ; then 
		    echo "Reset the config file to: $SNAP_DATA/$(basename $CONFIG_FILE)"
		else 
		    #echo "$SNAP_DATA/$CONFIG_FILE"
		    cp $CONFIG_FILE $SNAP_DATA/
		    echo "Adding and setting a new config file : $SNAP_DATA/$(basename $CONFIG_FILE)"
		fi
		CONFIG_FILE=$SNAP_DATA/$(basename $CONFIG_FILE)
	    else
		echo "Config file <$CONFIG_FILE> not found in $SNAP/current directory"
		echo "Reset to default config file: $SPGWU_CONF_FILE"
		CONFIG_FILE=$SPGWU_CONF_FILE
	    fi
	fi
	echo "SPGWU_CONF_FILE2=$CONFIG_FILE" > $SNAP_DATA/config_spgwu.sh
	#copy for the user
	echo "SPGWU_CONF_FILE2=$CONFIG_FILE" > $SNAP_USER_DATA/config_spgwu.sh
	;;
     "ls-spgwu" )
        if [ -r $SNAP_DATA/config_spgwu.sh ]; then
	    . $SNAP_DATA/config_spgwu.sh
	fi
	
	# default config file is (unless set in above config)
	SPGWU_CONFIG=${SPGWU_CONF_FILE2:-$SPGWU_CONF_FILE}
	ls $(dirname $SPGWU_CONFIG)/*spgw*.conf
	;;
     
	"echo-spgwu" | "cat-spgwu" )
	show_file=$2

	if [ -r $SNAP_DATA/config_spgwu.sh ]; then
	    . $SNAP_DATA/config_spgwu.sh
	fi
	
	# default config file is (unless set in above config)
	SPGWU_CONFIG=${SPGWU_CONF_FILE2:-$SPGWU_CONF_FILE}
	# echo (get), cat (show)
	# `echo $1 | cut -d"-" -f1` $SPGWU_CONFIG

	if [ "$show_file" != "" ]; then
		# echo "File to show $SNAP_DATA/$show_file"
		absolute_show_file=$SNAP_DATA/$show_file
		if [ ! -e $absolute_show_file ]; then
			echo "The file $absolute_show_file does not exist"
		else
			`echo $1 | cut -d"-" -f1` $absolute_show_file
		fi
	else
		# echo "File to show $SPGWU_CONFIG"
		`echo $1 | cut -d"-" -f1` $SPGWU_CONFIG
	fi
	
	;;
      
      *)
       echo "unknown command $1"
       ;;
esac
    

