#!/bin/sh

. $SNAP/common

if [ ! -e $SPGWU_EXEC ]; then
    echo "Cannot find $SPGWU_EXEC executable"
    exit -1
fi

if [ -r $SNAP_DATA/config_spgwu.sh ]; then
    . $SNAP_DATA/config_spgwu.sh
fi

SPGWU_CONFIG=${SPGWU_CONF_FILE2:-$SPGWU_CONF_FILE}
SPGWU_EXEC_ARGS=" -c $SPGWU_CONFIG "

case "$1" in
    "gdb" )
	echo "Running $2 with the gdb"
	touch      $SNAP_DATA/.gdb_$2
	chmod 777  $SNAP_DATA/.gdb_$2
	echo "file ${2^^}_EXEC"        > $SNAP_DATA/.gdb_$2
	echo "set args ${2^^}_EXEC_ARGS" >> $SNAP_DATA/.gdb_$2
	echo "run"                     >> $SNAP_DATA/.gdb_$2
	cat $SNAP_DATA/.gdb_$2
	exec $SNAP/gdb --data-directory=$SNAP_DATA  -n -x $SNAP_DATA/.gdb_$2
	;;
    
    "info" )
	snap info $SNAP_NAME
	;; 
      
     "start"  )
	snap start $SNAP_NAME
	;;
     
    "stop" )
	snap stop $SNAP_NAME
	;;

    "restart" )
	snap restart $SNAP_NAME
	;;
    
    "status" )
	snap services $SNAP_NAME
	;;

    "journal" )
	journalctl -u snap.$SNAP_NAME.service
	;;

    "help" )
	echo "Usage:   sudo  $SNAP_NAME.[options] args"
	echo "Note:    need root priviliage"
	echo "Options:"
	echo "  start:       start the $SNAP_NAME.spgwud daemon"
	echo "  stop:        stop the $SNAP_NAME.spgwud daemon"
	echo "  restart:     restart the $SNAP_NAME.spgwd daemon"
	echo "  status:      get the $SNAP_NAME.spgwud status"
	echo "  journal:     get the $SNAP_NAME.spgwud logs"
	echo ""
	echo "  init:       initialize SPGWU"
	echo "  conf-set:   set the SPGWU configuration file"
	echo "  conf-get:   get the current SPGWU configuration file (spgwu.conf)"
	echo "  conf-show:  show the path to the SPGWU configuration file (spgwu.conf)"
	echo "  conf-list:  list all the SPGWU configuration files (spgwu.conf)"
	echo ""
	echo "  help:       print this help"
	echo "  Example:    sudo oai-spgwu.init; sudo oai-spgwu;"
	
	;;
    
    "spgwu" | * )
	
	if [ -n "$LD_LIBRARY_PATH" ]; then
	    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/local/lib:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
	else
	    LD_LIBRARY_PATH=$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/local/lib:$SNAP/usr/local/lib/freeDiameter:$SNAP/usr/lib/x86_64-linux-gnu
	fi
	export LD_LIBRARY_PATH
	
        echo "$SPGWU_EXEC  $SPGWU_EXEC_ARGS" 
	$SPGWU_EXEC  `echo $SPGWU_EXEC_ARGS` "$@"
        ;;

esac


