name: oai-spgwu
version: '1.0' 
summary: OpenAirInterface spgwc entity Rel. 14 with LL-MEC Agent
description: |
    OAI-SPGWU is the openairinterface-based SPGWU with LL-MEC agent allowing to connect a 4G-comptaible BS and UEs to the core network. It is one of the projects of Mosaic5G inititive.

type: app
license: Apache-2.0
architectures:
  - amd64
  - i386
confinement: devmode
grade: stable
base: core18

apps:
  test:
    command : test
  info:
    command: run info
  oai-spgwu:
    command: run spgwu
  spgwud:
    command: run spgwu
    daemon: simple
    stop-command: run stop
    stop-timeout: 1s
  start:
    command: run start spgwud
  stop:
    command: run stop spgwud
  restart:
    command: run restart spgwud
  status:
    command: run status spgwud
  journal:
    command: run journal spgwud
  init:
    command: init spgwu
  help:
    command: run help
  debug:
    command: run gdb
  conf-set:
    command: conf set-spgwu
  conf-get:
    command: conf echo-spgwu
  conf-show:
    command: conf cat-spgwu
  conf-list:
    command: conf ls-spgwu
  api:
    command: run openapi
  apid:
    command: run openapi
    daemon: simple
    stop-command: run stop
    stop-timeout: 1s
  api-start:
    command: run start apid
  api-stop:
    command: run stop apid
  api-restart:
    command: run restart apid
  api-status:
    command: run status apid
  api-journal:
    command: run journal apid
      
hooks:
  install:
    plugs: [home, network]
  configure:
    plugs: [home, network]
    
parts:
  gdb:
    plugin: nil
    override-build: |
      sudo apt install gdb -y
      mkdir $SNAPCRAFT_PART_INSTALL/share 
      cp -r /usr/share/gdb $SNAPCRAFT_PART_INSTALL/share
      cp /usr/bin/gdb* $SNAPCRAFT_PART_INSTALL
    prime:
      - gdb*
      - share/*
      
  spgwu:
    plugin: cmake
    source: https://github.com/OPENAIRINTERFACE/openair-cn-cups.git
    source-branch: develop
    build-packages: [build-essential, ]
    stage-packages:
      - libstdc++6
      - libboost-system1.65.1
      - libconfig++9v5
      - libdouble-conversion1
      - libgflags2.2
      - libgoogle-glog0v5
      - libunwind8

    override-build: |
      cd ../src/build/scripts
      ./build_spgwu -I -f 
      ./build_spgwu -c -b Release
      cd ../..
      mkdir -p $SNAPCRAFT_PART_INSTALL/spgwu
      cp etc/spgw*  $SNAPCRAFT_PART_INSTALL/spgwu/
      cp build/spgw_u/build/*.*  $SNAPCRAFT_PART_INSTALL/spgwu
      cp build/spgw_u/build/spgwu  $SNAPCRAFT_PART_INSTALL/spgwu/
    stage:
      - spgwu/*
      - usr/*
      - lib/*
    prime:
      - spgwu/*
      - usr/*
      - lib/*
      
  frontend:
    plugin: dump
    source: frontend

  openapi:
    plugin: python
    python-version: python3
    python-packages:
      - flask
      - itsdangerous
      - Werkzeug==0.16.1
      - click
      - jinja2
      - MarkupSafe
      - requests
      - argparse
      - flask_restplus==0.13.0
      - aniso8601==8.0.0
      - pytz==2020.1
      - jsonschema==3.2.0
      - attrs==19.3.0
      - pyrsistent==0.16.0
      - importlib-metadata==1.7.0
      - importlib-resources==1.5.0
      - zipp==3.1.0
      # - pyrsistent==0.16.0
      # - cassandra-driver==3.24.0
    stage:
      - usr/lib/python3.6/*
      - usr/*
    prime:
      - usr/lib/python3.6/*
      - usr/*

layout:
  /usr/share/parameters:
    bind: $SNAP_DATA/usr/share/parameters

