options:
   snap:
     default: "edge"
     description: |
      snap indicates which channel to use for installation hook. 
     type: string
   bind_addr:
     default: "all"
     description: |
       defines the interface to which the flexran RTC is binded. By default, the RTC is listening across all the interfaces. 
     type: string
   bind_sbi_port: 
     default: 2210  
     description: |
       defines the network interface port to connect to the eNB agent/runtime.
     type: int
   bind_nbi_port:
     default: 9999
     description: |
       defines the network interface port for the REST API to issue a command to the controller.
     type: int

