#!/bin/bash

# $1 -->  <email>:           The login.ubuntu.com email to login as
if [ "$1" == "" ] ; then 
 snapcraft login $1
fi

declare -a snaps=("oai-cn" "oai-ran" "oai-ue" "oai-tracer" "flexran" "ll-mec")
declare -a snaps=("oai-cn")
declare -a snaps=("oai-ue")
declare -a snaps=("oai-hss" "oai-mme" "oai-spgwc" "oai-spgwu")
#declare -a snaps=("oai-hss")
declare -a channels=("edge,beta")

for s in "${channels[@]}"
do
    for k in "${snaps[@]}"
    do
	if [ -d $k ] ; then
          cd $k
          echo "Publshing $k snap, version $version, to channels: $s"
	  version=$(grep -m1 version: snap/snapcraft.yaml | cut -f2 -d: | tr -d "'" | tr -d " ")
	  snap=$k"_"$version"_multi.snap"
          echo "snapcraft push $snap --release $s"
          rev=`snapcraft push $snap --release $s | grep -m1 Revision | cut -f2 -d' '`
          echo "snapcraft release $k $rev $s"
	  if [ -z "$rev" ] ; then 
	      read -p "what is the revision of the snap to release (e.g. $rev)? " rev
	  fi
	 # echo "snapcraft release $k $rev $s"
	  
          snapcraft release $k $rev $s  
          cd ..
        fi
    done
done



