#!/bin/bash

# $1 -->  <email>:           The login.ubuntu.com email to login as
if [ "$1" == "" ] ; then 
 snapcraft login $1
fi

declare -a snaps=("oai-cn" "oai-ran" "oai-ue" "oai-tracer" "flexran" "ll-mec")
declare -a snaps=("oai-cn")
declare -a snaps=("oai-ue")
declare -a channels=("edge,beta")

for s in "${channels[@]}"
do
    for k in "${snaps[@]}"
    do
    read -p "what is the version of the $k snap you want to publish (e.g. 1.3)? " version
    echo "Release Snap $k to channels: $s"
    if [ -d $k ] ; then
          cd $k
          snap=$k"_"$version"_multi.snap"
          echo "snapcraft push $snap --release $s"
          rev=`snapcraft push $snap --release $s | grep -m1 Revision | cut -f2 -d' '`
          echo "snapcraft release $k $rev $s"
	  read -p "what is the revision of the snap to release (e.g. $rev)? " rev
	  echo "snapcraft release $k $rev $s"
	  
          snapcraft release $k $rev $s  
          cd ..
        fi
    done
done



