#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file common
# brief common functions and variables
# author  navid.nikaein@eurecom.fr and A. B. Molini

ubuntu_dist=$(lsb_release -si)$(lsb_release -sr)

set_env(){

    mosaic_path=/srv/mosaic5g
    export PATH=$PATH:/snap/bin
    conf_dir=/var/snap/oai-cn/current
    mme_conf=$conf_dir/mme.conf
    mme_fd_conf=$conf_dir/mme_fd.conf
    
    snap_dir=/snap/oai-cn/current/mme


}

check_mme_process(){

#  IS_RUNNING=`systemctl status mme.service`
#if [[ $IS_RUNNING =~ .*running.* ]]; then
#fi
    
    IS_ACTIVE=`systemctl is-active snap.oai-cn.mmed.service`

    if [ "$IS_ACTIVE" == "active" ]; then
	juju-log "OAI MME is running" 
	status=0
    else
	juju-log "OAI MME is not running"
	status=1
    fi
}
start_mme(){
    #oai-cn.mme-start
    snap start oai-cn.mmed
}

stop_mme(){
    #oai-cn.mme-stop
    snap stop oai-cn.mmed
}
restart_mme(){
    #oai-cn.mme-restart
    snap restart oai-cn.mmed
}
check_mme_connection(){

  COUNTER=0
  while [ $COUNTER -lt 30 ]; do
     sleep 1
     if [ "$(grep -c "is now connected" /srv/mme.out)" -gt 0 ]; then
        juju-log "MME is running and connected to HSS"
        status-set active "OAI MME is running"
        break
     fi
     COUNTER=$((COUNTER+1))
  done

  if [ "$COUNTER" -eq 30 ]; then

        status-set maintenance "Make sure HSS is running...or wait for hooks to finish the execution..."
     #juju-log "MME cannot connect to HSS...make sure the HSS service is running"
     #status-set blocked "MME cannot connect to HSS...resolve...and try to upgrade the charm"
     #exit 1
     #non devo stopparlo, ma dire di aspettare...
     ##status-set maintenance "just waiting for hss to be running..."
     

  fi
}

user_conf(){
  set_env
  juju-log "Setting up the config option chose by the user or the default ones"
  HOSTNAME=`hostname`
  if [ -f $CHARM_DIR/tac ]; then
      TAC=`cat $CHARM_DIR/tac`
  else
      TAC=1;
  fi
  # TBD: Check the number of digits in TAC and prepare ID accordingly 

  MCC=`config-get gummei_tai_mcc`
  MNC=`config-get gummei_tai_mnc`
  if [ "$MNC" -lt "99" ] ; then 
      MNC="0$MNC"
  fi
  ID="tac-lb0$TAC.tac-hb00.tac.epc.mnc$MNC.mcc$MCC.3gppnetwork.org"
  
  sed -r -i  "s/SGW_IPV4_ADDRESS_FOR_S11.*/SGW_IPV4_ADDRESS_FOR_S11=\"$spgw_s11_ipv4\/8\";/" $mme_conf

# if [ "$spgw_s11_ipv4" != "" ]; then  
#    sed -r -i  "s/SGW_IPV4_ADDRESS_FOR_S11.*/SGW_IPV4_ADDRESS_FOR_S11=\"$spgw_s11_ipv4\/8\";/" $mme_conf

#    sed -r -i  "s/mnc...\.mcc.../mnc$MNC\.mcc$MCC/" $mme_conf
    # add a new element if hanvn't done before
    #if [ "$(egrep -c $ID $mme_conf_path/mme.conf)" -le 0 ]; then
    #  echo "adding ID=$ID; SPGW_IP=$spgw_s11_ipv4/24; to mme.conf"
    #  sed -r -i "/S-GW_LIST_SELECTION/a {ID=\"$ID\" ; SGW_IPV4_ADDRESS_FOR_S11=\"$spgw_s11_ipv4\/24\";}," $mme_conf_path/mme.conf
    #fi
 # fi
#sed -r -i "/SGW_IPV4_ADDRESS_FOR_S11/ s-\".*\"-\"$spgw_s11_ipv4\"-" $mme_conf_path/mme.conf

  # update hss
  hss_hostname=${hss_fqdn%%.*}
  if [ -z "$hss_hostname" ]; then
    hss_hostname='hss'
  fi
  sed -i -e "s/ConnectTo = \".*\"; /ConnectTo = \"$hss_hostname.$realm\"; /" $mme_fd_conf
  sed -i -e "s/ConnectPeer= .* {/ConnectPeer= \"$hss_hostname.$realm\" {/" $mme_fd_conf
  # should be w/o realm
  sed -r -i "/HSS_HOSTNAME/ s/\".*\"/\"$hss_hostname\"/" $mme_conf

  # update realm
  sed -i -e "s/Identity = \".*\";/Identity = \"$HOSTNAME.$realm\";/" $mme_fd_conf
  sed -i -e "s/Realm = \".*\";/Realm = \"$realm\";/" $mme_fd_conf
  sed -i -e "s/realm = \".*\";/realm = \"$realm\";/" $mme_fd_conf
  sed -r -i "/REALM/ s/\".*\"/\"$realm\"/" $mme_conf

  # update other
  sed -r -i "/MAXENB/ s/[0-9]+/$max_enb/" $mme_conf
  sed -r -i "/MAXUE/ s/[0-9]+/$max_ue/" $mme_conf
  sed -r -i "/RELATIVE_CAPACITY/ s/[0-9]+/$relative_capacity/" $mme_conf
  sed -r -i "/MME_STATISTIC_TIMER/ s/[0-9]+/$mme_statistic_timer/" $mme_conf
  sed -r -i "/EMERGENCY_ATTACH_SUPPORTED/ s/\".+\"/\"$emergency_attach_supported\"/" $mme_conf
  sed -r -i "/UNAUTHENTICATED_IMSI_SUPPORTED/ s/\".+\"/\"$authenticated_imsi_supported\"/" $mme_conf
  sed -r -i "/ASN1_VERBOSITY/ s/\".+\"/\"$verbosity\"/" $mme_conf

  #sed -r -i  "s/MCC=\"[0-9]+\"/MCC=\"$gummei_tai_mcc\"/" $mme_conf
  #sed -r -i "s/MNC=\"[0-9]+\"/MNC=\"$gummei_tai_mnc\"/" $mme_conf
  #sed -r -i "s/TAC=\"[0-9]+\"/TAC=\"$gummei_tai_tac\"/" $mme_conf

  #NETWORK CONFIG
  juju-log "Setting up network configuration in the mme.conf file"

  ipv4=`get_eth_ip_net $iface`

  #INTERFACES
  sed -r -i "/MME_INTERFACE_NAME_FOR_S1_MME/ s/\".*\"/\"$iface\"/" $mme_conf
  sed -r -i "/MME_IPV4_ADDRESS_FOR_S1_MME/ s-\".*\"-\"$ipv4\"-" $mme_conf

  sed -r -i "/MME_INTERFACE_NAME_FOR_S11_MME/ s/\".*\"/\"$iface\"/" $mme_conf
  sed -r -i "/MME_IPV4_ADDRESS_FOR_S11_MME/ s-\".*\"-\"$ipv4\"-" $mme_conf

  sed -r -i "/OUTPUT/ s/\".*\"/\"CONSOLE\"/" $mme_conf

}

install_required_kernel(){
  version=3.19

  if [ "$(cat $CHARM_DIR/.kernel)" == "lowlatency" ]; then 
      wget -r -e robots=off --accept-regex "(.*lowlatency.*amd64)|(all).deb" http://kernel.ubuntu.com/~kernel-ppa/mainline/v${version}-vivid/
  else
      wget -r -e robots=off --accept-regex "(.*generic.*amd64)|(all).deb" http://kernel.ubuntu.com/~kernel-ppa/mainline/v${version}-vivid/
  fi

  dpkg -i kernel.ubuntu.com/*/*/*/*deb
}

check_current_kernel(){

  #required_kern_release=$(cat $tools_path/build_helper | egrep -o "check_kernel_release_and_install_xtables_addons_oai .+" | cut -d ' ' -f2)
  required_kern_release=3.19
  required_kern_version=`echo $required_kern_release | cut -d '.' -f1`
  required_kern_major_revision=`echo $required_kern_release | cut -d '.' -f2`
  current_kern_release=`uname -r`
  current_kern_version=`echo $current_kern_release | cut -d '.' -f1`
  current_kern_major_revision=`echo $current_kern_release | cut -d '.' -f2`
  if [ "$current_kern_version" -gt "$required_kern_version" ]; then
       REQUIRED_KERNEL_IS_INSTALLED="true"
  elif [ "$current_kern_version" -eq "$required_kern_version" ] && [ "$current_kern_major_revision" -ge "$required_kern_major_revision" ]; then
       REQUIRED_KERNEL_IS_INSTALLED="true"
  else
       REQUIRED_KERNEL_IS_INSTALLED="false"
  fi

}

# get from http://www.linuxjournal.com/content/validating-ip-address-bash-script
validate_ip() {

  local  ip=$1
  local  stat=1

  if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
      OIFS=$IFS
      IFS='.'
      ip=($ip)
      IFS=$OIFS
      [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
          && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
      stat=$?
  fi
  return $stat
}

validated_mme_public_ip=0

get_ip_address(){

  local  ip=$1
  local  status=1
  local  status_after=1

  if ! validate_ip $ip; then
      ip=`host $ip | awk '{ print $4 }'`
  fi

  validate_ip $ip

  status=$?
  if [ "$status" == "1" ] ; then 
      echo "doing nslookup for the mme host name $ip"
      juju-log "perfroming nslookup for the mme host name ($ip)"
      validated_mme_public_ip=`nslookup $ip | awk ' FNR == 5 {print $2 }'`
      status_after=$(validate_ip $ip)
      if [ "$status_after" == 1 ] ; then 
  	echo "nslookup failed for the mme host name $ip"
  	juju-log "nslookup failed for the mme host name ($ip)"
  	return $status_after
      else 
  	echo "MME ip address is $validated_public_mme_ip"
  	return 0
      fi
  else 
      validated_mme_public_ip=$ip
      echo "MME ip address is $validated_mme_public_ip"
      return 0
  fi 

}

get_eth_ip(){
  echo `ip addr show $1 | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | grep -o [0-9].*`
}

get_eth_ip_net(){
  echo `ip addr show $1 | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+/[0-9]\+' | grep -o [0-9].*`
}

set_google_dns_gw(){
    route add default dev eth0
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    echo "nameserver 8.8.8.8" > /etc/resolvconf/resolv.conf.d/base
}
