# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV["LC_ALL"] = "en_US.UTF-8"
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  #config.vagrant.plugins = ["vagrant-vbguest", "vagrant-hosts"]
  #config.vagrant.plugins = ["vagrant-vbguest", "vagrant-hosts", "landrush"]
  #config.landrush.enabled = true

  #config.landrush.host 'oaicn.mosaic-5g.io', '1.2.3.4'
  
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  config.vm.network "forwarded_port", guest: 2152, host: 2152, protocol: "udp"
  config.vm.network "forwarded_port", guest: 2126, host: 2126, protocol: "udp"
  config.vm.network "forwarded_port", guest: 2154, host: 2154, protocol: "udp"
  config.vm.network "forwarded_port", guest: 2123, host: 2123, protocol: "udp"
  config.vm.network "forwarded_port", guest: 36412, host: 36412

  # for LLMEC
  config.vm.network "forwarded_port", guest: 9999, host: 9999, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 9998, host: 9998, protocol: "tcp"
  

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  #config.vm.network "private_network", ip: "192.168.111.2"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # interface for S1 and SGI
  config.vm.network "public_network"
  # add a separate interface for Sgi
  #config.vm.network "public_network"
    

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.cpus = 2 
    vb.memory = "2048"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", run: "always", inline: <<-SHELL
      apt-get update
      sysctl -w net.ipv6.conf.all.disable_ipv6=1
      sysctl -w net.ipv6.conf.default.disable_ipv6=1
      snap remove oai-cn
      snap install oai-cn --beta --devmode
      oai-cn.stop-all
      date=$(date +%F)
      if [ ! -f ./oai-cn ] ; then 
        echo "oai-cn vm created: $date" > ./oai-cn
      else
        echo "oai-cn vm reloaded: $date" >> ./oai-cn
      fi
  SHELL
end
