name: flexran
version: '2.2.1' 
summary: FlexRAN SD-RAN platfrrom
description: |
   FlexRAN is a software-defined radio access network platform on the top of OpenAirInterface, licensed under Apache License V2.0. It is one of the projects of Mosaic5G inititive.
grade: stable
type: app
architectures:
  - amd64
  - i386
confinement: devmode
license: Apache-2.0
base: core18

apps:
  info:
    command: run info
  flexran:
    command: run
  sbi-port:
    command: conf sbi
  nbi-port:
    command: conf nbi
  ports:
    command: conf ports
  flexrand:
    command: run flexran
    daemon: simple
    stop-command: run stop
    stop-timeout: 1s
  start:
    command: run start flexrand
  stop:
    command: run stop flexrand
  restart:
    command: run restart flexrand
  status:
    command: run status flexrand
  journal:
    command: run journal flexrand
  help:
    command: run help
#  debug:
#    command: run gdb
hooks:
  install:
    plugs: [home, network]
  configure:
    plugs: [home, network]
parts:
#  gdb:
#    plugin: nil
#    stage-packages:
#      - libbabeltrace1
#     - libdw1
#      - libmpfr6
#    override-build: |
#      sudo apt install gdb -y
#      mkdir $SNAPCRAFT_PART_INSTALL/share 
#      cp -r /usr/share/gdb $SNAPCRAFT_PART_INSTALL/share
#      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
#      cp /usr/bin/gdb* $SNAPCRAFT_PART_INSTALL/bin
#    prime:
#      - bin/gdb*
#      - share/*
      
  pistache:
    plugin: cmake
    source:  https://github.com/oktal/pistache.git
    source-commit: 2ef937c434810858e05d446e97acbdd6cc1a5a36
    override-build: |
      cd ../src/
      mkdir -p build
      cd build
      cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
      make
      sudo make install
      cd -
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      cp /usr/local/lib/libpistache.a $SNAPCRAFT_PART_INSTALL/lib
    prime:
      - lib/libpistache.a
  protobuf:
    plugin: make
    source:  https://github.com/google/protobuf.git
    build-packages: [ autoconf, automake, libtool, curl, g++, unzip, ]
    override-build: |
      cd ../src/
      ./autogen.sh
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      #./configure --prefix=$SNAPCRAFT_PART_INSTALL/lib
      ./configure 
      make
      sudo make install
      sudo ldconfig
      #mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      cp /usr/local/lib/libproto* $SNAPCRAFT_PART_INSTALL/lib
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp /usr/local/bin/protoc* $SNAPCRAFT_PART_INSTALL/bin
    stage:
      - lib/*
      - bin/*
    prime:
      - lib/*
      - bin/*
  flexran:
    after: [ pistache, protobuf]
    plugin: cmake
    source: https://gitlab.eurecom.fr/flexran/flexran-rtc.git
    source-branch: develop
    build-packages: [build-essential, ]
    stage-packages:
      - libboost-all-dev
      - liblog4cxx-dev
      - liblog4cxx10v5
      - libcurl4-openssl-dev
      - libcurl3-gnutls
    override-build: |
      cd ../src/
      ./build_flexran_rtc.sh 
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp build/rt_controller $SNAPCRAFT_PART_INSTALL/bin/flexran
      #mv $SNAPCRAFT_PART_INSTALL/bin/rt_controller $SNAPCRAFT_PART_INSTALL/bin/flexran 	
      mkdir -p $SNAPCRAFT_PART_INSTALL/log_config
      cp -r log_config/* $SNAPCRAFT_PART_INSTALL/log_config
    stage:
      - bin/flexran
      - usr/lib/*
      - lib/*
      - log_config
    prime:
      - bin/flexran
      - usr/lib/*
      - lib/*
      - log_config

  frontend:
    plugin: dump
    source: frontend