#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file config-change
# brief manage the config changes of flexran service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr

set -eux
source $CHARM_DIR/utils/common
set_env

status-set maintenance "Config-Changed hook"
stop_flexran

if [ "$(config-get snap)" != "$(cat $CHARM_DIR/.snap)" ]; then
    juju-log "Snap channel changed"
    echo "$(config-get snap)" > $CHARM_DIR/.snap
    $CHARM_DIR/hooks/upgrade-charm
fi

bind_addr=`config-get bind_addr`
if [ "$bind_addr" != "$(cat $CHARM_DIR/.bind_addr)" ]; then
    juju-log "Set the FlexRAN bind address to 0.0.0.0 ($bind_addr)"
    echo "$bind_addr"      >  $CHARM_DIR/.bind_addr
fi


bind_port=`config-get bind_sbi_port`

if [ "$bind_port" != "$(cat $CHARM_DIR/.bind_port)" ]; then
    juju-log "changing the SBi bind port number to $bind_port"
    close-port $(cat $CHARM_DIR/.bind_port)/tcp || true
    open-port $bind_port/tcp
    flexran.sbi-port $bind_port
    echo "$bind_port"      >  $CHARM_DIR/.bind_port
fi

rest_port=`config-get bind_nbi_port`

if [ "$rest_port" != "$(cat $CHARM_DIR/.rest_port)" ]; then
    juju-log "changing the NBi bind port number to $rest_port"
    close-port $(cat $CHARM_DIR/.rest_port)/tcp || true
    open-port $rest_port/tcp
    flexran.nbi-port $rest_port
    echo "$rest_port"      >  $CHARM_DIR/.rest_port
    
fi


iface=`config-get eth`

if [ -n "$iface" ]; then
   ipv4=`ifconfig $iface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`
   juju-log "eth interface is $iface with ip address $ipv4"

fi


