#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file rtc-relation-changed
# brief called when a relation between an eNB and RTC is changed 
# author  navid.nikaein@eurecom.fr

set -ex
source $CHARM_DIR/utils/common
set_env
status-set maintenance "RTC-relation-changed hook"

#rel_ids=`relation-ids rtc`

#if [ -z "$rel_ids" ];then
#   juju-log "Data not available yet, exit silently"
#   exit 0
#fi

#agent_active=`relation-get -r $rel_ids AGENT_ACTIVE`

#if [ -z "$agent_active" ]; then
#   juju-log "Agent is not active yet, exit silently"
#   exit 0
#fi


#if [ "$agent_active" == "yes" ]; then  

 #   echo "$agent_active" >  $CHARM_DIR/.agent_active
    relation-set RTC_PORT=`config-get bind_sbi_port`
    
    rtc_public_ip=`unit-get public-address`
    get_ip_address $rtc_public_ip
    status=$?
	  
    if [ "$status" == "1" ] ; then
	juju-log "nslookup failed for the flexran host name ($rtc_public_ip)"
	relation-set RTC_PUBLIC_IP=$rtc_public_ip
    else
	relation-set RTC_PUBLIC_IP=$validated_public_ip
	juju-log  "Joined the RTC relation"
    fi 
    
    #$CHARM_DIR/hooks/start

#else 
#    status-set blocked "RAN/eNB Agent is not yet active"
#fi
