#!/bin/bash
# Copyright 2016-2018 Eurecom and Mosaic5G Platforms Authors
# Licensed to the Mosaic5G under one or more contributor license
# agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.
# The Mosaic5G licenses this file to You under the
# Apache License, Version 2.0  (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the Mosaic5G:
#      contact@mosaic5g.io
#
################################################################################
# file stop 
# brief stop the flexran service, this happens when the service is stopped/disabled
# author  navid.nikaein@eurecom.fr 

set -eux

source $CHARM_DIR/utils/common
set_env
status-set maintenance "Stop hook"

juju-log "Stopping flexran  service in this unit"
flexran.stop || true

juju-log "Removing the flexran snap "
snap remove flexran

juju-log "Cleaning up the mosaic-5g installation directory..."
rm -rf $mosaic_path
